### ISSUE TITLE
Azure Site Extension does not work in some scenarios

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1005]
**Description**

An issue has been reported by a customer where our Azure Site Extension does not work in some scenarios:

1. Azure Web Apps are arbitrarily assigned a `%HOME%` directory on the `C:` drive or `D:` drive. The New Relic Azure Site Extension installs the agent alongside customer application code properly in both scenarios, but the environment variables for our profiler are hardcoded to assume the `C:` drive. 
2. When an Azure Web App is configured to *[Run From a ZIP Package](https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package)*, the application directory has read only permissions. This prevents the .NET Agent from installing properly since our current strategy is to install the agent in this directory alongside the customer application

**Expected Behavior**
- The .NET Agent Azure Site Extension works in scenarios where the application home directory exists on the `D:` drive.
- The .NET Agent Azure Site Extension works in scenarios where the application is configured to run from a zip package.

**Comment by JcolemanNR** [comment]
After meeting with the team, the additional work still needs to be completed before releasing this:

- [ ] Implement graceful migration for filepath changes. Don't want to lose customized Newrelic.config and custom instrumentation.
- [ ] Update documentation to provide details on how the Site Extension installs agent. 
- [ ] Update documentation to clarify c/d root for nuget package use case.
- [ ] Clean up old agent deploy location
- [ ] Increase Site Extension Version to 2.0

**Comment by angelatan2** [comment]
Size - small (1) for remaining work.
