### ISSUE TITLE
Error Message Size Increase

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-dotnet-agent#1007]
**Problem** 
Errors Inbox groups errors by error message. 

Customers are reporting poor grouping because of truncated messages. Sometimes the truncated part is interesting but more often it is a result of variable length tokens that occur before the truncation making the remaining message hard to group.
Our current character limit is 256, causing the truncating of error messages and the grouping logic to fail, making Errors Inbox full of duplicate looking errors.

**What We Can Do About This**
Let's increase our character limit so that messages are not truncated. The advice from the errors inbox team is from 256 characters to 1024 characters. 

[Internal Link](https://newrelic.aha.io/features/DOTNET-362)

**Comment by jaffinito** [comment]
Note, this change does go against the attribute spec, which limits the values to 255 characters.  Traced errors should also have a 255 character limit per the Errors spec, but we don;t follow that.  We also decided to allow larger log messages as well in recent work.

Given the above, I am okay with implementing a change to increase the error.message size to 1024 characters.

**Comment by jaffinito** [comment]
Spec change PR: https://source.datanerd.us/agents/agent-specs/pull/572
