### ISSUE TITLE
Update to minimum version Microsoft.AspNetCore.Mvc.Core 2.0.0

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1011]
Update agent/blob/main/src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/AspNetCore.csproj)
to use Microsoft.AspNetCore.Mvc.Core 2.0.0 from Microsoft.AspNetCore.Mvc.Core 1.1.3

Dependencies - .NET Standard 2.0

**Comment by vuqtran88** [comment]
This was already done in https://github.com/newrelic/newrelic-dotnet-agent/pull/1108
