### ISSUE TITLE
.NET API to give a span a custom name

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-dotnet-agent#1023]
Customers would like the ability to dynamically name the current metric name for a method span name. The Java agent has this ability via the setMethodName API. Potentially, the ISpan interface could be enhanced to have a setSpanName API (or something comparable). The customer feels that adding this level of context to tracing would be extremely beneficial for triage activities.

**Comment by michaelgoin** [comment]
@elucus based on the Java the naming, this seems likely it is renaming both the segment and span names.

Are you intended to only update span names or should we really be updating the segment and span names?

**Comment by elucus** [comment]
@michaelgoin  both, the intent is to match the Java agent.

**Comment by JcolemanNR** [comment]
The branch from the previous work is: `jcoleman/custom-span-name-api`
