### ISSUE TITLE
Need to log deprecation/removal warning for the config property "transactionTracer.stackTraceThreshold"

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1026]
This config element exists in the agent's `Configuration.xsd` currently:

```
<transactionTracer ....
   stackTraceThreshold="500"
   ...
/>
```

Here it is: https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd#L918
and here it is in the generated `Configuration.cs` file: https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Core/Config/Configuration.cs#L2968

And here's where it gets combined with server-side config to make a property (`DefaultConfiguration.TransactionTracerStackThreshold`) that would be used in the agent internally to drive logic: https://github.com/newrelic/newrelic-dotnet-agent/blob/756fdddebe5b110b9c388d94703fab21b09fcad6/src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs#L1652

However, there are no references to the `TransactionTracerStackThreshold` property in the agent other than in basic config unit tests and in the place where we send the agent config up to the server on connect.  In other words, this config element doesn't actually do anything useful anymore.  And I checked, and it doesn't look like we're logging anything to warn customers that this is the case, like we do for other config elements that have been deprecated/disabled (for example, these here:  https://github.com/newrelic/newrelic-dotnet-agent/blob/756fdddebe5b110b9c388d94703fab21b09fcad6/src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs#L2150)

So, at a minimum, we should start logging a warning to the agent log when we detect that a customer's config file contains this element.

**Comment by jackdelamotte** [comment]
Putting this in the backlog until it can be revisited at next major release. (It sound like this property needs to be removed from the default config file)
