### ISSUE TITLE
Migration Guide to Major Release 10.0

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1035]
Please create a migration guide identifying methods and configs that we are removing and instructions to help our customers migrate to the next version.

See ref: https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/8x-to-9x-agent-migration-guide/

**Comment by nr-ahemsath** [comment]
Migration guide is live: https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/9x-to-10x-agent-migration-guide
