### ISSUE TITLE
Enabled Logging by Default

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1037]
Modify our default configuration to enable logging by default.

**Comment by angelatan2** [comment]
@rdhar thanks for sharing your thoughts! Can you share what logging framework do you use? We are currently in process of releasing this feature for Microsoft Extensions Logging, log4net and Serilog.  With the upcoming release, it won't be turn on by default.  The user will have to configure it to turn on.  We are very interested to hear feedback regarding this feature.

**Comment by angelatan2** [comment]
@rdhar The Log forwarding feature within the agent will be released in version 9.8.0 shortly.  In this version, the feature will be enabled by default. If you choose to disable it, you could do it through the configuration file or using the environment variables.

**Comment by rdhar** [comment]
Hi @angelatan2, thanks for the update, and I'm really for the delay in getting back to you. I've been following the conversation [on the forum](https://discuss.newrelic.com/t/183811) as well to better understand the scope of this feature in the [latest release v9.8.0](https://github.com/newrelic/newrelic-dotnet-agent/releases/tag/v9.8.0).

As it happens, at my organisation, there's already an alternative logging solution so there isn't a big push for this. That being said, I'm still keen to explore logs in context with the real-time observability already provided by APM. With any luck, we can organise a trial of the latest agent to kick the tyres.

To answer your question, it's predominantly log4net, though Serilog is on the cards as well. It's based on .NET Framework 4.5.1, which is far from modern - though the recent EOL from Microsoft might be enough to convince a broader upgrade across the board. 

Thanks to our outstanding customer success manager, we've been happy to beta-test/early-access and share feedback on new features released by NR. Just _really_ slow to get the ball rolling.
