### ISSUE TITLE
Most faster event harvest limits are overridden by using environment variables resulting in much higher limits that expected

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1043]
### Feature Description
Most faster event harvest limits are overridden by using environment variables resulting in much higher limits that expected.

What happens is that we override the limit provided by the server, but we still honor the faster harvest cycle.  The current harvest is set to 5000 MS.  The result is that customers can experience up to 12x the limit they set per minute.

This was not done with the recent application logging work to allow log forwarding to be disabled and to ensure the server values was honored.  There was some discussion about switching out the other settings, but we opted to keep the risk low.

To fix this  we just need to swap the server override and the environment override for the following.
* error_event_data
* custom_event_data
* analytic_event_data

Span events are handled very different;y so we should probably exclude those.

Example of the issue:

```csharp
public virtual int TransactionEventsMaximumSamplesStored
{
    get
    {
        var maxValue = _localConfiguration.transactionEvents.maximumSamplesStored;
        return (int)EnvironmentOverrides(
            ServerOverrides(_serverConfiguration.EventHarvestConfig?.TransactionEventHarvestLimit(), maxValue),
            "MAX_TRANSACTION_SAMPLES_STORED");
    }
}
```

Here is how we did this for logging:

```csharp
public virtual int LogEventsMaxSamplesStored
{
    get
    {
        return ServerOverrides(_serverConfiguration.EventHarvestConfig?.LogEventHarvestLimit(),
            EnvironmentOverrides(_localConfiguration.applicationLogging.forwarding.maxSamplesStored,
            "NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED").GetValueOrDefault(10000));
    }
}
```

### Priority
Really Want!

**Comment by angelatan2** [comment]
Closed with https://github.com/newrelic/newrelic-dotnet-agent/pull/1239
