### ISSUE TITLE
Archive Telemetry SDK repository for Dotnet

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1047]
Archive the repository https://github.com/newrelic/newrelic-telemetry-sdk-dotnet

- [x] Updated open issues to won't fix
- [x] Update the banner to archive
- [x] Update the readme to recommend appropriate OTel replacement (see https://github.com/newrelic/newrelic-opentelemetry-integration-java)
- [x] Update the [OTel exporter docs](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-legacy-new-relic-exporters/)

**Comment by jackdelamotte** [comment]
[Archived.](https://github.com/newrelic/newrelic-telemetry-sdk-dotnet) Did not find any needed changes in the linked Otel exporter docs.

**Comment by jackdelamotte** [comment]
Noting that [this](https://docs.newrelic.com/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data/) page lists the [Java](https://github.com/newrelic/newrelic-telemetry-sdk-java), [node](https://github.com/newrelic/newrelic-telemetry-sdk-node), [Python](https://github.com/newrelic/newrelic-telemetry-sdk-python), [Go](https://github.com/newrelic/newrelic-telemetry-sdk-go), [C](https://github.com/newrelic/newrelic-telemetry-sdk-c), and [Rust](https://github.com/newrelic/newrelic-telemetry-sdk-rust) telemetry SDKs, which I believe can all be archived in similar fashion.
