### ISSUE TITLE
Documentation wrong?

### ISSUE THREAD

**Issue by amweiss** [newrelic/newrelic-dotnet-agent#1050]
When looking at: https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all#2-decorate
```xml
<applicationLogging enabled="true">
  <logForwarding enabled="true" />
</applicationLogging>
```

it indicates the element name for log forwarding is `logForwarding` but the xsd schema file indicates it is `forwarding`.

One of these should be changed.

**Comment by nr-ahemsath** [comment]
I also fixed the name of the log fowarding config element in the main .NET agent config doc: https://github.com/newrelic/docs-website/pull/7035
