### ISSUE TITLE
Documentation: Memory usage to be reported on Linux

### ISSUE THREAD

**Issue by Lonli-Lokli** [newrelic/newrelic-dotnet-agent#1052]
According to docs
https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core/
Unavailable features are
 [Memory usage](https://docs.newrelic.com/docs/apm/applications-menu/monitoring/apm-overview-page#infra-server) on Linux due to [an ongoing .NET Core issue](https://github.com/dotnet/corefx/issues/23449) (try using [.NET performance metrics](https://docs.newrelic.com/docs/agents/net-agent/other-features/net-performance-metrics) to get this information)

As this issue is fixed, either documentation should be updated or some feature be created

**Comment by nr-ahemsath** [comment]
Yep, good call.  Should be fixed soon: https://github.com/newrelic/docs-website/pull/7066

**Comment by nr-ahemsath** [comment]
Docs PR has been merged, closing this.  Thanks again @Lonli-Lokli!
