### ISSUE TITLE
Log decorating not linking to APM

### ISSUE THREAD

**Issue by amweiss** [newrelic/newrelic-dotnet-agent#1054]
We have an existing log shipping setup and tried to use the new log decorating (the old serilog enricher worked fine as well). However, now the logs aren't linked in APM even though they show up in the infrastructure logs.

**Description**
Splunk log:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/30146/162957515-dfd58b9b-ce0f-401d-9944-2f1680b38c8e.png">

Infrastructure logs:
![image](https://user-images.githubusercontent.com/30146/162957854-33aff078-b0c1-4ce0-9d3e-33085789d3d7.png)

APM logs:
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/30146/162958010-7277769d-12ba-4749-918f-da9f42e113ed.png">

Serilog formatter changed from:
`NewRelic.LogEnrichers.Serilog.NewRelicFormatter, NewRelic.LogEnrichers.Serilog`
to
`Serilog.Formatting.Json.JsonFormatter, Serilog` with `renderMessage=true`
and `localDecorating enabled="true"` set in the config.

If you need diagnostic logs, I'll send them though a support ticket.

**Comment by nr-ahemsath** [comment]
@amweiss Thanks for bringing this to our attention.

Can you clarify what you mean by "infrastructure logs"?  Are they the same log messages from your application as the ones seen in Splunk, just in a different view in New Relic?

**Comment by amweiss** [comment]
Sorry, it used to be called that I think. It's the "logger" url of New Relic One from the fluentd log shipper: https://docs.newrelic.com/docs/logs/forward-logs/fluentd-plugin-log-forwarding

<img width="721" alt="image" src="https://user-images.githubusercontent.com/30146/163069576-e2e17501-7741-4324-b5d4-4df25229a8df.png">

Yep, it's the exact same log lines in splunk and new relic (I guess I should have not redacted the whole thing 🙃) trace id and all, they are just no longer connected to APM like they were before for logs-in-context when we used the enricher and formatter.

**Comment by nr-ahemsath** [comment]
@amweiss Thanks for clarifying.  At this point I think it would be better to work this issue through our support ticketing system (please reference this GH issue when creating the ticket though).  I'm not sure at this point whether the issue is with how our agent is sending the data, or with how the UI/backend is trying to find your logs for that APM logs view.

**Comment by amweiss** [comment]
@nr-ahemsath Case #00036857 created.
