### ISSUE TITLE
Verification of the account disable switch for Logging

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1063]
Run end to end testing to ensure that the "big red button" works
-Dependencies:  When the feature is available.

**Comment by jaffinito** [comment]
With feature flag enabled I can see the switch under "data management hub/log settings".
When disabling, after the agent restarts I no longer see log_event_data being called and the UI shows no logs.
When enabling, after the agent restarts I see new log_event_data calls and the UI shows new entries.
See here for data: https://staging.onenr.io/01qwLv21xj5
