### ISSUE TITLE
Release notes for 9.8.0

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1072]
- [x] Please update the last supported agent release in our public-facing doc to [.NET agent v8.28.0.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/net-agent-8280)
- [x] Please add deprecation of .NET Framework 4.6.1 older and .NET Core 3.0 and older

**Comment by jaffinito** [comment]
Release branch (compare):
https://github.com/newrelic/docs-website/compare/develop...jaffinito:dotnet-grass-valley-feature-pack
