### ISSUE TITLE
NServiceBus v6 + v7 Transaction trace links broken

### ISSUE THREAD

**Issue by TraGicCode** [newrelic/newrelic-dotnet-agent#1074]
Hello,

We upgraded to the latest version of the .NET NewRelic Agent in order to get NServiceBus v6 +v7 support.  We currently are seeing all transaction BUT when you click a transaction trace ( as shown below ) are are always presented with an error and are not taken to the transaction trace.  Is this a expected or is this a bug?  We currently have distributed tracing turned on.

![image](https://user-images.githubusercontent.com/6224270/165534912-f889d2e4-a912-4940-b54a-0f7be2e1cfb0.png)

**Comment by TraGicCode** [comment]
Hey @JcolemanNR ,

We talked to someone at newrelic support and they informed us when we toggle to use the "new view" on this page transaction traces are able to be shown without error but using the legacy/old view it errors.  If you have a detailed technical explanation of this that would be great. I assume the old view utilizes some older backend data that isn't being provided/populated when the nservicebus feature was added.

**Comment by JcolemanNR** [comment]
Hello @TraGicCode, 

This sounds like a UI specific error, and I wouldn't expect it to have anything to do with the .NET Agent. 

Nothing changed from a data format perspective in the release that included improved NServiceBus functionality that I'm aware of.

I'll followup with the team and let you know what I learn.

**Comment by JcolemanNR** [comment]
Hey @TraGicCode,

I spoke to the UI team and we are unsure why this is not currently working in the old UI. The agent team suspects a UI/web issue, and the web/UI team suspects an agent issue. 👉 👈 

Nothing changed in the Agent release that you upgraded to that would impact the underlying data model for transaction traces. 

If you need to get the old view working then please create another ticket with GTS.
