### ISSUE TITLE
MsiInstaller tests need to get a valid license key from a secret store

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#110]
The MsiInstaller tests have two test cases which require a valid license key to work.  They are failing because they are attempting to use a hardcoded, invalid license key.  These tests should be modified to use the same secrets store mechanism as the integration tests to get the license key.

**Comment by angelatan2** [comment]
This is part of the story when we do the installer step of our packages.
