### ISSUE TITLE
MySQL version 8.0.29 causes explain plans to break (and other unbounded tests to fail)

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1110]
**Description**
After rebuilding our unbounded services, I noticed that MySQL unbounded tests were consistently failing. After digging into this, I noticed that [Version 8.0.29 of MySQL had been released](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-29.html) in the past month. 

The integration test failures relate to explain plans not being present, and procedure creation failing (non agent related). 

The smoking gun here is that the [MySQL release notes](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-29.html) mention changes to explain plan functionality, and procedure creation.

When we go to resolve this issue, we should revert the changes introduced in: https://github.com/newrelic/newrelic-dotnet-agent/pull/1111

**Expected Behavior**
Explain plans work, and all unbounded integration tests pass

**Steps to Reproduce**
Run unbounded integration tests against MySQL v8.0.29

**Comment by angelatan2** [comment]
Severity on not supporting retrieval of explain plan - Medium.  

** Community developers, if you disagree with this statement please thumbs down so that we can prioritize accordingly **.
