### ISSUE TITLE
Remove #if NET45 and #if NETSTANDARD2_0 preprocessors where appropriate

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#1115]
Since we now only support .Net Framework >=462 and .Net Framework >=462 support netstandard2.0, a lot of the #if NET45 conditions become irrelevant.

Acceptance Criteria:
Test pass.
8T works on both .NET Core >=3.0 and Framework >=4.6.2
Put comments around remaining directives.

**Comment by chynesNR** [comment]
Looks like these have all been addressed already.
