### ISSUE TITLE
Review and Update .NET supported versions documentation change

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#1118]
Documents breaking change: 
1. Drop support on .NET Framework < 4.6.2 and .NET Core 2.0/2.1/3.0.
2. Need to confirm the supported version for the following third party libraries:
      log4Net
      log4net.Ext.Json
      Serilog
      Microsoft.Extensions.Logging
      NLog
      RabbitMQ.Client
        NServiceBus

**Comment by angelatan2** [comment]
Completed with Major Release 10.0.0
