### ISSUE TITLE
Add `SMSvcHost.exe` to Agent internal ignore list

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1120]
### Feature Description
There was a recent customer escalation where they were getting proxy errors for an agent that had been spun up for `SMSvcHost.exe`. After investigating we realized that this was a Microsoft system service that the customer had no interest in profiling. Ideally this windows service would not be profiled by default when environment variables are globally enabled for the agent.

### Additional context
SMSvcHost.exe is a Microsoft system service which manages TCP port sharing functionality. https://answers.microsoft.com/en-us/ie/forum/all/what-is-smsvchostexe/74ca4bbc-99b6-4e86-8a65-080e2c9061f2

### Priority
Nice to have. Will eliminate customer confusion, and support cases related to `SMSvcHost.exe` in the future.

Note: This is a .NET core app.

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):* P3
*Suggested T-Shirt size (S, M, L, XL, Unknown):* S

**Comment by vuqtran88** [comment]
After investigation, SMSvcHost.exe is a .NET FW app (not .NET Core). The reason why it got instrumented from the first place is a customer specifically specify to instrument it. However, it appears instrumenting this process is problematic, it is still a good idea to ignore it by all cost.
