### ISSUE TITLE
Allow instrumentation to be ignored via configuration file (not newrelic.config)

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1121]
### Feature Description
During a recent deprecation of some instrumentation, we encountered an issue where the instrumentation that had been deprecated by New Relic was still in the agent `extensions` folder for some install/deploy use cases. This resulted in the deprecated instrumentation being loaded and double instrumentation taking place. 

While we updated all of our installers to explicitly remove this deprecated instrumentation during upgrade, there still exists custom deployment/fringe use cases where deprecated instrumentation can be present in the `extensions` folder. To accommodate these scenarios (and any scenario where an installer fails to remove deprecated instrumentation), an internal list of ignored instrumentation xml files was introduced in the profiler [HERE](https://github.com/newrelic/newrelic-dotnet-agent/pull/1097/files#diff-09c8cb6746d79f9853b402e7f398f71a7edea14ad8411adc892a89f11ea9f58f).

When the team discussed this implementation, the consensus was that this list of ignored instrumentation should be externalized to a file to make this feature more extensible, and customer accessible. As mentioned in the title, this should be a **new** file that is overwritten by the installer every time, and not included in **newrelic.config** (as that file is NOT overwritten by the installer if it already exists).

This feature should be engineered in a way so that neither deprecated instrumentation XML files, or deprecated wrapper assemblies are loaded when they are flagged in the new ignore list. (the current internal implementation only prevents the instrumentation xml from being loaded).

### Priority
Nice to Have. Product saw some potential customer use cases for this file (though it should be noted that this file WILL be overwritten every time an agent is upgraded).

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):* P5
*Suggested T-Shirt size (S, M, L, XL, Unknown):* L

**Comment by angelatan2** [comment]
This feature allows ease of discoverability of deprecated instrumentation.
