### ISSUE TITLE
Faster Event Harvest limits are not respected during Agent reconnect

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1122]
**Description**
When the agent is issued a reconnect request from the server, the faster event harvest configuration previously issued by the server is wiped out until a new connect request completes. In this period, more (or fewer) events than intended may be gathered and sent up by aggregators on a faster event harvest. 

**Expected Behavior**
Even if the agent is requested to reconnect, the previously communicated event limits will be respected (or not harvested at all) until a new connect request completes.

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):* P4
*Suggested T-Shirt size (S, M, L, XL, Unknown):* M

**Comment by angelatan2** [comment]
The issue has a higher impact if the following connect is to disable the feature.  If no change in config such as limits or enable/disable: no impact. If enabling a feature, we may miss data during the connect window latency.
