### ISSUE TITLE
Newrelic reports an error when running on the arm64 server.

### ISSUE THREAD

**Issue by gyuvyuh2** [newrelic/newrelic-dotnet-agent#1145]
On the arm64 server, install newrelic, start the dotnetcore program, and the profiler log reports an error：
[Error] ReJIT failed for (Module:***/Microsoft.AspNetCore.Hosting.dll, AppDomain: clrhost)[Microsoft.AspNetCore.Hosting]Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(Microsoft.Extensions.Hosting.IHostBuilder,System.Action`1[Microsoft.AspNetCore.Hosting.IWebHostBuilder]).

After looking at the source code of the profiler project, I found that the error occurred in "HRESULT RejitFunction(Function& function)",When calling method "_corProfilerInfo4->RequestReJIT(1, &moduleIds, &methodIds)".

Environment:
Arm64 Server | Ubuntu 18.04 | dotnet core3.1 | newrelic-netcore20-agent_9.9.0.0_arm64.deb

**Comment by JcolemanNR** [comment]
Hello @gyuvyuh2, thanks the report! Unfortunately the New Relic .NET Agent only supports ARM64 on .NET 5+. This is a known limitation and there are currently no plans to add ARM64 support for .NET Core 3.1.

We spent some time trying to get the ARM64 version of the Agent working on .NET Core 3.1 but believed there was a bug in the native profiler API for .NET Core 3.1 applications preventing the ReJit from working properly.

That being said, we would be happy to receive any community contribution to add this functionality, if it is in fact possible.

**Comment by gyuvyuh2** [comment]
This is indeed the case, thanks.
