### ISSUE TITLE
SMBv2 signing

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1147]
Please address the issue detailed in this internal ticket.
Internal Only:
[NOTE]: (https://newrelic.atlassian.net/browse/DOTNET-4826)

**Comment by jaffinito** [comment]
The server is used infrequently for testing.  This server has been shutdown, for the near-term.  We will address this the next time we start it up.

**Comment by angelatan2** [comment]
The server is internal and within VPN walls.  The communication is in the internal ticket.  Closing this as "won't fix" until further response.
