### ISSUE TITLE
The .NET Core agent should have a fallback logging mechanism

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1158]
### Is your feature request related to a problem? Please describe.
When using the framework agent on Windows, the agent is able to write its log messages to the Windows Event log if it has an error attempting to log to a file.  With the core agent, particularly on Linux, there is no such fallback logging functionality, leading to a lack of troubleshooting information and confused, unhappy customers.

See relevant code: https://github.com/newrelic/newrelic-dotnet-agent/blob/07c303d0221e1e2c35e2f9132fcc2030a16e5049/src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs#L266-L280 

### Feature Description
The core agent should have the same ability to log to an alternate location in case the configured log file can't be written to.

The difficulty is that the core agent can be run on Linux, where the Windows event log will never be available.  Linux does have the equivalent `syslogd` but it's not as guaranteed to be there and running as the event log.

Log4Net and Serilog (which we've been considering switching to using in the agent for logging) both have appenders/sinks for syslogd.

### Describe Alternatives
Could just fall back to logging to the console on Linux if file logging doesn't work.
Maybe we can write to a file in a location guaranteed to be writable on the system like `tmp`.

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by angelatan2** [comment]
This story needs some discovery and is better suited for when we refactor the "ifdefs" or unify the agent.
