### ISSUE TITLE
Need docs.newrelic.com documentation for datastore segment naming feature

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1160]
### Is your feature request related to a problem? Please describe.

We need to describe the feature for custom naming datastore segments with a SQL comment in our agent docs at docs.newrelic.com.  The PR for the feature is currently the most comprehensive source of information about the feature and how it works: https://github.com/newrelic/newrelic-dotnet-agent/pull/799

### Feature Description

In discussion with the docs team about where it would make the most sense to document this feature in our current agent docs structure, we agreed it probably goes under the general area of "Custom Instrumentation" since it requires users to make code changes.  It probably needs a new, separate page in that category.

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have]

**Comment by jackdelamotte** [comment]
Added this documentation [here](https://github.com/newrelic/docs-website/pull/8599).
