### ISSUE TITLE
Reduce string allocations in BrowserMonitoringWriter

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#117]
String allocations are expensive. There are ways to reduce this performance hit when working with strings in .NET. This issue is to examine and improve use of strings in a specific place in the Agent code - BrowserMonitoringWriter.

**Description**
Examples of inefficient use of strings:
- This [method](https://github.com/newrelic/newrelic-dotnet-agent/blob/e53d916fe0dff11abca5665a50412a8f7195bb1a/src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringWriter.cs#L38-L50) sets a string `bodyWithJsHeader` to String.Empty at the start, but it gets replaced later if method returns early. An improvement would be to return String.Empty from the early return and return constructed string otherwise, avoiding allocation of String.Empty.
- In same method, rather than allocating `jsScriptWithBodyPrefix` and using `content.Replace`, use string interpolation and a const.
- In same method, return the constructed string from above directly instead of storing it in a local string variable.
- Where possible, use consts (which occur at compile-time instead of run-time) for strings that will not change.

**Expected Behavior**
Current functioning should not change. Ideally, these changes would improve performance for apps using this feature of the Agent. See "Additional context: Testing" below.

**Steps to Reproduce**
N/A

**Your Environment**
Instrumented app using Agent's browser injection.

**Additional context**
Testing: Existing unit tests should be sufficient for this Issue to find regressions. Additionally, a test app making heavy use of the browser monitoring feature of the agent could be used to compare before and after scenarios for memory use and garbage collection.

**Comment by bgrainger** [comment]
> This method sets a string bodyWithJsHeader to String.Empty at the start, but it gets replaced later if method returns early. An improvement would be to return String.Empty from the early return and return constructed string otherwise, avoiding allocation of String.Empty.

Assigning `var bodyWithJsHeader = string.Empty;` doesn't cause an allocation (it's just an assignment of a reference to a static field).

**Comment by bgrainger** [comment]
The `AttemptInsertionPriorToBodyTag` method is only called if `WriteScriptHeaders` doesn't find a `<HEAD>` tag (which is implied to be uncommon). `WriteScriptHeaders` then uses a `Regex` (to find a `X_UA_COMPATIBLE` meta tag), which (in my experience) is much more expensive than string concatenation.

It doesn't seem worthwhile worrying about possible inefficiencies in `AttemptInsertionPriorToBodyTag`; profiling `WriteScriptHeaders` (and fixing any problems that reveals) would be more useful.

**Comment by angelatan2** [comment]
The performance impact or inefficiencies of this change is limited.  We will not be making this change.
