### ISSUE TITLE
Update guided install for Linux to work with new package names

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1183]
Once 10.0.0 is released with the change of Linux install package names, the guided install process will need to be updated to install the new package name: https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/dotNet/linux-systemd.yml

We need to clarify whether the guided install process is expected to be used for new installs only, or if it's expected to handle upgrades from 9.x to 10.x.

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Must Have]

**Comment by vuqtran88** [comment]
The recipe update PR is done here https://github.com/newrelic/open-install-library/pull/757 but it won't be merged until the new package is released and the recipe is tested.

**Comment by vuqtran88** [comment]
I manually tested the new recipe locally and it worked as expected. It still need to be tested again after the ver 10.0 release.

This source also needs to be updated with the new package name after the agent ver 10.0 release.
