### ISSUE TITLE
Include Exception message, and stack trace in all logging instrumentation

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1184]
### Feature Description
Multiple logging frameworks include the ability to supply an exception. This exception object is inspected and typically the message, stack trace, and any inner exceptions are reported on. The .NET agent should do in depth inspection/reporting of instrumented log methods that include a customer supplied exception object. 

### Priority
Really Want

Size: M
Priority: P4

**Comment by elucus** [comment]
A similar request for Java https://github.com/newrelic/newrelic-java-agent/issues/802

**Comment by jasonjkeller** [comment]
@elucus @jaffinito I have a PR here to implement this for the Java agent: https://github.com/newrelic/newrelic-java-agent/pull/968

**Comment by JcolemanNR** [comment]
@jaffinito Answers below! :)

> @JcolemanNR Can we get an example of this? What should we do with the exception? Does the logging backend support sending up more detail?

**Examples:**
Most logging libraries provide overloaded methods that allow strongly typed `Exception`s to be supplied separately from the log message. Displaying this information is dependent on configured output formatters in most cases. 
- Log4net: https://logging.apache.org/log4net/release/sdk/html/M_log4net_ILog_Info_1.htm
- Serilog: https://github.com/serilog/serilog/blob/5307e3572a9d6b393ac3ada7719b5c4c6af6a811/src/Serilog/Log.cs#L777-L789
- NLog: https://nlog-project.org/documentation/v4.0.0/html/M_NLog_Logger_Warn_25.htm
- Microsoft Logging Extensions: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logerror?view=dotnet-plat-ext-6.0#microsoft-extensions-logging-loggerextensions-logerror(microsoft-extensions-logging-ilogger-system-exception-system-string-system-object())

**What should we do?**
We should observe the exceptions when present, and send up the message, stack trace, and error class to New Relic. 

**Does the backend support this?**
It appears so. This spec PR shows how this can be accomplished: https://source.datanerd.us/agents/agent-specs/pull/579

**Comment by JcolemanNR** [comment]
This has been implemented in Agent Release 10.1.0
