### ISSUE TITLE
Support structured log properties in logs captured by the APM agent.

### ISSUE THREAD

**Issue by Julian-Robinson** [newrelic/newrelic-dotnet-agent#1216]
### Feature Description
I'm not sure if this is meant to 'just work' but it would be great if the logs captured automatically by the APM agent included structured log properties and not just the log message. We often use additional log properties to add context to logs that allow us to easily trace, filter or group messages and it would be great if we could do this all within New Relic. 

Without these additional properties I'm finding the logs collected by APM aren't that useful and we end up having to look up our other log sinks to find the detail we need when troubleshooting. (the lack of exception info also doesn't help https://github.com/newrelic/newrelic-dotnet-agent/issues/1184) 

### Describe Alternatives
Haven't looked too deeply into alternatives yet, but planning to investigate:
- Whether fully structured logs are included as part of the [AWS Cloudwatch integration](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream). Our logs also end up in CloudWatch now so if they come across as part of that we may just need to add the New Relic trace properties. 
- Manually decorating and forwarding logs. Either using a New Relic Serilog sink, or standalone log forwarder. Ideally I'd like to avoid this, though - it's always a bit of a hassle.  

### Additional context
There's a couple of ways we add these properties to the logs: 
- Within the message template itself. eg https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#log-message-template. 
- With Serilog specifically we use enrichers or the log context to add detail, and this property then applies to all log messages within that scope. I'm not sure the default dotnet logger has this functionality, but some other logging packages (like NLog) do. https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext 

We're installing and using the APM agent for Linux on our docker images running on AWS ECS based on [this guide](https://docs.newrelic.com/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container). 

### Priority
Really Want 

Thanks team! If there's any additional info you want or need happy to provide what I can. 

Cheers

**Comment by JcolemanNR** [comment]
Hey @Julian-Robinson, 

Thanks for creating this feature request! As you've noticed, we don't support structured logging in the currently released version of in-Agent log forwarding. We are discussing including both exception information (#1184), and structured logging properties in the future as this has been requested from many different agents.

**Comment by dolivanu** [comment]
Hi @Julian-Robinson, you mention "in the currently released version of **in-Agent log forwarding**." Is there an alternative way for the structured log properties being captured by the APM agent? We are focusing in the Serilog log framework.

**Comment by JcolemanNR** [comment]
Hello @dolivanu, I believe the structured logging properties will be available if if you use our legacy log enrichment solution for logs in context (requires setting up a separate log uploader). 

This is 'option 3' in the following document: https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#3-old-formatter

**Comment by chynesNR** [comment]
We were going through the backlog and saw that this was still open. Our automatic log forwarding now supports context data, as do our log enrichers, so I think we can close this. If there is still missing functionality please feel free to file a new issue.
