### ISSUE TITLE
InstrumentationWatcher can cause ThreadAbortException

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#122]
InstrumentationWatcher uses a worker thread to monitor for instrumentation configuration changes. It uses `SignableAction` to request a Rejit when a change is detected. The worker thread gets aborted on Dispose.

**Description**
This exception creates an annoying distraction in the Agent log, and Exceptions are a performance hit. In this case, the work is already done, the worker thread is no longer needed, and the exception is moot. [Dispose()](https://github.com/newrelic/newrelic-dotnet-agent/blob/e53d916fe0dff11abca5665a50412a8f7195bb1a/src/Agent/NewRelic/Agent/Core/Utilities/SignalableAction.cs#L52) should not abort the worker thread.

Suggested implementation: Instead of `_worker.Abort();` in `Dispose()` do something like
```
_doShutdown = true;
Monitor.Pulse(_lock);
```
then check `_doShutdown` in the `Action`'s `while`-loop.

**Expected Behavior**
Dispose() shuts down worker thread gracefully; no ThreadAbortException appears in Agent log.

**Steps to Reproduce**
- Create Agent-monitored app and add [custom instrumentation](https://docs.newrelic.com/docs/agents/net-agent/custom-instrumentation/introduction-net-custom-instrumentation) using the 'XML custom instrumentation' method. You may want to have at least 2 methods in the app for which you will add custom instrumentation because you will need to add and/or remove instrumentation while it is running.
- Run the app. While it is running, change the custom instrumentation to add or remove an instrumented method by editing your <customInstrumentation>.xml file.
- The ThreadAbortException may be intermittent and depend on timing, so if you don't see it in the Agent log, try changing custom instrumentation several times while the app is running to have a better chance of generating the exception.

**Your Environment**
This issue can occur with any instrumented application utilizing custom instrumentation regardless of framework (.NET or .NET Core) and app type (Console, Web, Mvc, etc.)

**Additional context**
Testing: Add unit test in `SignalableActionTests`.

**Comment by tehbio** [comment]
I've done some extensive testing and could not get any exceptions generated by changing the instrumentation files while the Agent was actively running.

Furthermore, after more research with @vuqtran88, the `InstrumentationWatcher` and its `SignableAction` have lifetimes that span the Agent and should not be `Dispose()`d with any instrumentation file changes.
