### ISSUE TITLE
Add support for instrumentation of async methods with `ValueTask` return type

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#1231]
### Feature Description
The .NET agent currently only supports instrumentation of async methods with a `Task` or `Task<T>` return type. A recent customer escalation involved an attempt to use `Parallel.ForEachAsync(...)` while instrumenting the action. This did not work properly as the supplied function must return `ValueTask` instead of `Task` or `Task<T>` to be used by `Parallel.ForEachAsync(...)`.

The current behavior is that the agent attempts to wrap the function with a `ValueTask` return type, but only successfully injects bytecode to start a segment (which never ends).

Here is some sample code to reproduce the issue:
```
[Transaction]
[MethodImpl(MethodImplOptions.NoInlining)]
private async ValueTask DoAsyncThing(int id, CancellationToken cancellationToken)
{
    Console.WriteLine($"Doing thing {id}");
    await Task.Delay(500, cancellationToken);
}

private async Task DoParallelAsyncThings()
{
    var things = new int[10];
    for (int i = 0; i < things.Length; i++)
    {
        things[i] = i;
    }
    await Parallel.ForEachAsync(things, DoAsyncThing);
}

// This is the MVC controller action that does the async things
public IActionResult Privacy()
{
    _ = DoParallelAsyncThings();
    return View();
}
```

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to Have

**Comment by visdmin** [comment]
Hi,
Is there any updates regarding this feature request, any idea if somebody is already working on this ?
