### ISSUE TITLE
Create a slack notification bot "Dotty" that detects and alerts the team on new versions of Core Tech

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#1232]
The process of figuring out when there are newer versions of Core Technologies is manual, time-consuming, and easily missed. Let's create a slack bot that discovers when there is a more recent version of Core Tech. As we update our core technologies next quarter,  the bot will let us know when they continue to get outdated based on external roadmaps.  
Please create a bot that lets us know that there is a new version and alert the team. 

### Acceptance Criteria

1. Detect when there is a new version of core tech
2. Send an alert message to dotnet team channel (or another more appropriate channel).
3. [Stretch goal]: If already alerted of a new version number, do not alert again with the same version number (to avoid spamming our channels.

Estimates:
M - 1 sprint and pairing with  @hannahramadan when available/possible.

**Comment by jackdelamotte** [comment]
#1240 Creates Dotty and #1245 makes some improvements based on team feedback. Dotty is now scheduled to run nightly, updating team on non-dev releases of our core technologies.
