### ISSUE TITLE
v10.1.0 broke agent log forwarding feature with log4net 1.2.15

### ISSUE THREAD

**Issue by pbering** [newrelic/newrelic-dotnet-agent#1252]
https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all states that *log4net: 1.2.10+ (.NET Framework)* is supported, but on one of my solutions that has a hard dependency to log4net 1.2.15 has started to fail when I upgraded the agent from 10.0.0 to 10.1.0. The error seen in the New Relic agent log is:

```text
2022-09-29 08:16:13,591 NewRelic  ERROR: [pid: 17472, tid: 64] Tracer invocation error: System.NullReferenceException: Object reference not set to an instance of an object.
   at NewRelic.Agent.Core.Agent.RecordLogMessage(String frameworkName, Object logEvent, Func`2 getTimestamp, Func`2 getLevel, Func`2 getLogMessage, Func`2 getLogException, String spanId, String traceId)
   at NewRelic.Providers.Wrapper.Logging.Log4netWrapper.RecordLogMessage(Object logEvent, Type logEventType, IAgent agent)
   at NewRelic.Providers.Wrapper.Logging.Log4netWrapper.BeforeWrappedMethod(InstrumentedMethodCall instrumentedMethodCall, IAgent agent, ITransaction transaction)
   at NewRelic.Agent.Core.Wrapper.WrapperService.BeforeWrappedMethod(Type type, String methodName, String argumentSignature, Object invocationTarget, Object[] methodArguments, String tracerFactoryName, String metricName, UInt32 tracerArguments, UInt64 fu
nctionId)
   at NewRelic.Agent.Core.AgentManager.GetTracerImpl(String tracerFactoryName, UInt32 tracerArguments, String metricName, String assemblyName, Type type, String typeName, String methodName, String argumentSignature, Object invocationTarget, Object[] argu
ments, UInt64 functionId)
```

I noticed a change in 10.1.0 https://github.com/newrelic/newrelic-dotnet-agent/pull/1228/files#diff-25a73084b562e9910081a3264247a8bcf21898057deddbba65b88e1260ca4d21R58 this is likely the problem as log4net 1.2.x does NOT have a `ExceptionObject` property, but it does have `private readonly Exception m_thrownException`, maby this can be used as fallback when `ExceptionObject` is not present?

This issues is a blocker for us as we can not upgrade to later versions of log4net, we need this to be fixed to be able to upgrade to newer agent versions.

**Comment by pbering** [comment]
Hi ahemsath, you are indeed correct about `ExceptionObject` is present in 1.2.10 which means that I'm using an even older version than I though. I use a "special" log4net version embedded in another assembly from this package: https://sitecore.myget.org/feed/sc-packages/package/nuget/Sitecore.Logging/10.2.0 which does not have `ExceptionObject` property, but it does have the `m_thrownException` field, same as 1.2.10/1.2.15.

Is there any possibility that you are willing to do some kind of fallback to the `m_thrownException` field so it would work also in my case (Sitecore is a commonly used enterprise CMS) ?

To actually get New Relic to use the embedded log4net from Sitecore.Logging.dll I have overriden `NewRelic.Providers.Wrapper.Log4NetLogging.Instrumentation.xml` with:

```xml
<?xml version="1.0" encoding="utf-8"?>
<extension xmlns="urn:newrelic-extension">
  <instrumentation>
    <tracerFactory name="log4net">
      <match assemblyName="Sitecore.Logging" className="log4net.Repository.Hierarchy.Logger">
        <exactMethodMatcher methodName="CallAppenders" />
      </match>
      <match assemblyName="log4net" className="log4net.Repository.Hierarchy.Logger">
        <exactMethodMatcher methodName="CallAppenders" />
      </match>
    </tracerFactory>
  </instrumentation>
</extension>
```

Kind of a hack but worked until 10.1.0 ;-) and way easier that setting up some other log shipping solution.

I understand if you do not want to do fallback to `m_thrownException` as it is quite an edge case and out of scope of the supported 1.2.0+ version... If this is the case, feel free to close this issue.

**Comment by nr-ahemsath** [comment]
@pbering Thanks for the detailed reply.  Our team thinks it is commendable that you took the initiative to modify the instrumentation XML to work with Sitecore, and we are interested in supporting users who take such steps to make our agent work in their environment.  We don't currently support Sitecore's version of log4net, but we have had at least one other customer show interest in it.  I've converted both this issue and our internal JIRA issue to be a feature request, which I hope can be scheduled in a reasonable timeframe.

We encourage PRs from community members, and if you are willing to take on the effort of making the modifications you suggest to use `m_thrownException` instead of the `ExceptionObject` property we will do our best to support you.

**Comment by chynesNR** [comment]
Support for Sitecore.Logging was added in 10.14.0
