### ISSUE TITLE
Automatic Instrumentation & Distributed Tracing for MassTransit

### ISSUE THREAD

**Issue by noahtrilling** [newrelic/newrelic-dotnet-agent#1282]
Our organization uses MassTransit over RabbitMQ extensively. New Relic does not automatically instrument MassTransit with Transactions or support distributed tracing between producers and consumers of messages.

### Feature Description
We would like the New Relic .NET Agent to automatically instrument MassTransit producers and consumers and support distributed tracing between them. It looks like the New Relic .NET Agent already supports this feature for NServiceBus (another ESB implementation) so our use case is likely identical.

[NServiceBus](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBusHelpers.cs#L88)

### Describe Alternatives
MassTransit recently added support for OpenTelemetry in Version 8. However, the New Relic Agent more easily correlates logs to trace spans without modification to our source code/logging mechanism. The .NET Agent may also be able to more easily support distributed tracing in older versions of MassTransit.

### Priority
Must Have

**Comment by noahtrilling** [comment]
Thanks for taking a look into this request and for the prompt reply.

1) We also suspected that the RabbitMQ instrumentation should cover this use case, but as far as I know, we are not seeing any distributed tracing or segments being created from the RabbitMQ instrumentation. If these Release Notes establish the correct minimum versions for RMQ and the .NET Agent, we would expect to see at least some tracing, but we have not. 

https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/net-agent-83700/

2) We have many MassTransit applications here. I'd guess some are as old as Version 2 or Version 3  and some are a recent as the latest (Version 8)

3) We also use AWS SNS/SQS as a transport.

4) We use most of the API surface, but our immediate concern is distributed tracing for the basic messaging functions. Publish and Send for Producers. Receive for Consumers. We have some usage of the more advanced features of MassTransit, including Sagas, Scheduling, but instrumentation of those features would be a lower priority.

**Comment by jaffinito** [comment]
Based on what you have posted, it does sound like our instrumentation should at least cover a bit of the calls from MassTransit going over RabbitMQ.  Given this, I think it might be best if you file a support request so that this can be examined in more detail.

**Comment by noahtrilling** [comment]
We have previously opened a support case with our account representatives on this subject and met with them in person today but they still could not provide us with a clear best path forward between OpenTelemetry and the New Relic .NET Agent for MassTransit monitoring. We have a very large number of APM installations for the New Relic Agent and a mass migration to OpenTelemetry would be complex and costly for our organization. On the other hand, the absence of automatically instrumented observability is a massive black hole in our observability stack that makes the OpenTelemetry agent an appealing option.

The ideal solution in the short term is for this feature to be implemented on the New Relic Agent so no migration to OpenTelemetry is necessary.

Will you please consider prioritizing this feature? MassTransit has a big user base in the .NET community. I doubt we are the only New Relic customers who would enormously benefit from automatic instrumentation of MassTransit.

**Comment by noahtrilling** [comment]
Thank you for considering this feature. I'm confident it will be an enormous help to many of New Relic's .NET customers.

**Comment by nr-ahemsath** [comment]
This has been implemented and will be released soon in agent version 10.19.0.
