### ISSUE TITLE
misuse of ArgumentNullException in LambdaTracer.Extract

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-dotnet-agent#1283]
https://github.com/newrelic/newrelic-dotnet-agent/blob/721825bcad66bb1036a00752de2c2c989e1114d0/src/AwsLambda/AwsLambdaOpenTracer/LambdaTracer.cs#L110-L115

The parameter for `ArgumentNullException` is supposed to be the name of the parameter that was null, not a message. Furthermore, `ArgumentNullException` is intended for when one of the function parameters is null. Please change it to `ArgumentException` or `InvalidOperationException` instead.

**Comment by jaffinito** [comment]
Just  quick update, the PR has been merged and when we release the Lambda agent again, it will have the updated error type.  I am go ahead and close this issue.  Thank you again for helping to improve our agent!
