### ISSUE TITLE
Support dotConnect for PostgreSQL

### ISSUE THREAD

**Issue by cunhaw** [newrelic/newrelic-dotnet-agent#1298]
dotConnect for PostgreSQL is a high-performance ORM enabled data provider for PostgreSQL that builds on ADO.NET technology to present a complete solution for developing PostgreSQL-based database applications.
https://www.devart.com/dotconnect/postgresql/

### Feature Description
Supporting this library out-of-the-box. 

### Describe Alternatives
- An alternative would be the instrumentation of the ORM (EntityFramework) instead of every specific database driver.
- Instrumenting via configuration is a possibility? (XML files)

### Priority
Must have in our scenario. Monitoring transactions without database times is not acceptable.

**Comment by cunhaw** [comment]
https://www.devart.com/dotconnect/postgresql/

**Comment by jaffinito** [comment]
Hi @cunhaw,
Thank you for submitting this!  We haven't instrumented ORMs directly in the past, but there is no technical reason why we couldn't in the future.  I have updated the Jira issue associated with this to be a feature request and handed it off to our PM to have a look and prioritize as part of our usual process.
