### ISSUE TITLE
Stop using Exceptions for flow control

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#131]
Using exceptions for flow control is an anti-pattern. 

**Description**
This Issue is to refactor [MetricNameService](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Core/Metrics/MetricNameService.cs) to remove the use of `IgnoreTransactionException` in `RenameUsingRegexRules()`.

**Expected Behavior**
Behavior should not change.

**Your Environment**
This issue can occur with any instrumented application regardless of framework (.NET or .NET Core) and app type (Console, Web, Mvc, etc.)

**Additional context**
It is possible the IgnoreTransactionException can be eliminated completely, it appears to only be used in this context.
Testing: Existing MetricNameServiceTest will need to be adjusted.

**Comment by geekexplorer** [comment]
@lspangler584 I've submitted a PR for this change.

**Comment by angelatan2** [comment]
The value of this change is limited and does not justify for the refactoring effort.
