### ISSUE TITLE
Add Lambda Example

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#134]
This issue is to create an example app demonstrating the Agent's support of Lambda.

### Additional context
The example app should be located in the `examples` folder at the top of the repo. At the time of this writing, `examples` folder does not exist so this Issue would include creating it.

### Priority
An example would help the Lambda community understand how to use the Agent for such applications. New Relic welcomes contributions from the community for this purpose and looks to an interested contributor to give it a go!

**Comment by tanaka-takayoshi** [comment]
Hi, now New Relic Lambda extension is introduced. The [document](https://docs.newrelic.co.jp/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-using-lambda-layer) links to the following example code.
https://github.com/newrelic/newrelic-lambda-extension/tree/main/examples/dotnet

Do you still need another type of example? If so, can I help it?

**Comment by angelatan2** [comment]
@tanaka-takayoshi, a heads up that the above link is no longer valid.
Please use the example on the documentation site: https://github.com/newrelic/newrelic-lambda-extension/tree/main/examples/dotnet
