### ISSUE TITLE
NewRelic.Agent.Api 10.5.0 NuGet package is missing the binaries

### ISSUE THREAD

**Issue by RobinsonWM** [newrelic/newrelic-dotnet-agent#1346]
**Description**
The `NewRelic.Agent.Api` NuGet package version 10.5.0 is missing the `NewRelic.Api.Agent.dll` binary.

https://www.nuget.org/packages/NewRelic.Agent.Api shows the file size is only 19.5 KB.  The `lib` directory inside the package is missing.

**Expected Behavior**
The `10.5.0` package should contain `lib\netstandard2.0\NewRelic.Api.Agent.dll` like the `10.4.0` package did.

**For Maintainers Only or Hero Triaging this bug**
*Priority (P1,P2,P3,P4,P5):* P2

**Comment by JcolemanNR** [comment]
Hello @RobinsonWM, thanks for the report. We are currently investigating and should have a resolution soon.

**Comment by angelatan2** [comment]
Hello @RobinsonWM, thanks again for bringing this issue to our attention so promptly.  We have delisted 10.5.0 due to the incomplete Nuget package and released a patch version 10.5.1.
