### ISSUE TITLE
Add option to write agent logs to /dev/stdout only

### ISSUE THREAD

**Issue by musukvl** [newrelic/newrelic-dotnet-agent#1373]
I'm always frustrated when I see "Unable to initialize the New Relic .NET Agent log file.  Please make sure the logs directory is writeable." in securely proteced pod with readOnlyRootFilesystem. There is no way to configure .Net NewRelic Agent writing it's own logs to `stdout` only and not to write logs to `NewRelic.Profiler.1.log` `newrelic_agent_XXX.log` files.

### Feature Description
Support NEWRELIC_LOG_FILE=/dev/stdout the same as it is done for newrelic php agent newrelic.logfile = "/dev/stdout"
Or implement some other option to disable writing agent logs to file system.

### Priority
Must Have: 
" .NET Agent requires a writeable directory for logging in order to function" requirement should be removed.
It is not possible to increase k8s cluster securty with enforing readOnlyRootFilesystem for all containers. We need to mount writable volumes to all applications we have only because of the Newrelic Agent requirement.

**Comment by chynesNR** [comment]
Hi @musukvl - thanks for your request! This is something that's been on our radar, and is likely to be in a future release, though I don't have a timeframe for you at the moment. I don't see an existing issue here for this, though, so I'll leave this open for tracking.
