### ISSUE TITLE
Error Fingerprinting: Setup attribute system

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1399]
### Describe the story, please be clear on scope of the story.
Setup the attribute definitions and enums for the error fingerprinting.

ApiSupportabilityMetricCounters.cs

1. Update ApiMethod enum to add “ErrorGroupCallback” method.

AttributeDefinitionService.cs

1. Add definition for ErrorGroup with a private backing field. Name of attribute is "error_group".  Type should be AttributeDefinition<string, string>.  Destinations should be ErrorEvent and.ErrorTrace. AttributeClassification should be AgentAttributes.
2. Add ErrorGroupFingerprint  to IAttributeDefinitions

### Acceptance Criteria

- Agent should build
- new definition is available from interface.

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
S

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-dotnet-agent/1399?planning-poker) with Zenhub @jaffinito

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-dotnet-agent/1399?planning-poker) with Zenhub @JcolemanNR

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1399?planning-poker) with Zenhub @tippmar-nr

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1399?planning-poker) with Zenhub @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1399?planning-poker) with Zenhub @chynesNR
