### ISSUE TITLE
Make Spans More useful - Parent Attributes

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#140]
### Is your feature request related to a problem? Please describe.
A clear and concise description of the problem. For example, "I'm always frustrated when [...]".

### Additional context
Originated from DOTNET-4755 
The reporter of the problem was Jason F.

### Priority
[Nice to Have]

**Comment by angelatan2** [comment]
@jifeingo please add a description to this issue.  The information here is what originated from DOTNET-4755 and it's pretty limited.

**Comment by lspangler584** [comment]
Closing after 90 days. No details. Low priority.
