### ISSUE TITLE
Error Fingerprinting: Plumb ErrorFingerprintingCallback into API and Agent

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1400]
### Describe the story, please be clear on scope of the story.
Setup the agent API with for ErrorGroupCallback. The method will takes “Func<Exception, string> callback” as its only parameter.

Don’t forget to add documentation summaries!

Core/Agent.cs

1. Add Property called ErrorGroupCallback, type of Func<Exception, string>, backer of _errorGroupCallback.
2. Getter should check for null and if null, return and set a delegate that returns a string.Empty.
3. Example: return _errorGroupCallback ??= delegate (Exception x) { return string.Empty; };

IAgentApi.cs

1. Add ErrorGroupCallback with Func<Exception, string> as parameter.

AgentApi.cs

1. Add ErrorGroupCallback with Func<Exception, string> as parameter.
2. Setup similarly to “SetApplicationName” (use const, and work)
3. Calls InternalApi.ErrorGroupCallback

InternalApi.cs

1. Add ErrorGroupCallback with Func<Exception, string> as parameter.
2. Calls “AgentApiImplementation.ErrorGroupCallback”

AgentApiImplementation.cs

1. Add ErrorGroupCallback with Func<Exception, string> as parameter.
2. Casts IAgent to Agent and uses ErrorGroupCallback property to set the callback.

### Acceptance Criteria

- Agent should build
- Smoke test: Load API into app and make sure methods are available - they won’t do anything currently

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
S

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1400?planning-poker) with Zenhub @jaffinito @JcolemanNR @tippmar-nr

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1400?planning-poker) with Zenhub @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1400?planning-poker) with Zenhub @chynesNR
