### ISSUE TITLE
Error Fingerprinting: Update error types with new callback

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1401]
### Describe the story, please be clear on scope of the story.
Update the ErrorData to store the fingerprint, ErrorService to invoke the callback and set the fingerprint, and the makers to set the attribute.

ErrorData.cs

1. Add a string Property called “ErrorGroup” that only has a getter.
2. Update constructor to take an errorGroup and assign it.
3. There will be several tests that need fixed to use the updated constructor

ErrorService.cs

1. Update FromExceptionInternal to invoke the Agent.Instance.ErrorGroupCallback callback and pass it into the ErrorData constructor.

ErrorEventMaker.cs

Note: if the string is null or empty, do not add the attrtibute!

1. Add a “SetErrorGroup” method that takes “ErrorData errorData, IAttributeValueCollection attribValues” and sets the _attribDefs.ErrorGroup to the errorData.ErrorGroup value.
2. SetErrorGroupshould be called immediately before “return new ErrorEventWireModel” in both GetErrorEvent methods.

ErrorTraceMaker.cs

Note: if the string is null or empty, do not add the attrtibute!

1. Update constructor to take in IAttributeDefinitionService so that we can access the definitions. Similar to other uses of this class, recommend using a field that calls “_attribDefs => _attribDefSvc.AttributeDefs” to access the definitions.
2. Update GetErrorTraceAttributes signature to take in an ErrorData and use that to set the _attribDefs.ErrorGroup to the errorData.ErrorGroup value.

### Acceptance Criteria

- Agent should build
- Smoke test: Load API into app and make sure methods are available and work

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
S

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1401?planning-poker) with Zenhub @jaffinito @JcolemanNR @tippmar-nr

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1401?planning-poker) with Zenhub @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1401?planning-poker) with Zenhub @chynesNR
