### ISSUE TITLE
User Tracking: Setup attribute system

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1404]
### Describe the story, please be clear on scope of the story.
Setup the attribute definitions and enums for the error user tracking.

ApiSupportabilityMetricCounters.cs

1. Update ApiMethod enum to add “EndUserId” method.

AttributeDefinitionService.cs

1. Add definition for EndUserId with a private backing field. Name of attribute is "enduser.id". Type should be AttributeDefinition<string, string>.  Destinations should be ErrorEvent and.ErrorTrace as well as TransactionTrace and TransactionEvent . AttributeClassification should be AgentAttributes.
2. Add EndUserId  to IAttributeDefinitions

### Acceptance Criteria

- Agent should build
- new definition is available from interface.

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
S

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1404?planning-poker) with Zenhub @jaffinito @JcolemanNR @tippmar-nr

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1404?planning-poker) with Zenhub @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1404?planning-poker) with Zenhub @chynesNR
