### ISSUE TITLE
User Tracking: Plumb SetUserId into Core/Transaction classes

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1405]
### Describe the story, please be clear on scope of the story.
Add the SetUserId method to Transaction

Extensions/ITransaction.cs

1. Add “SetUserId”, taking a string and returning void to the interface.

Core/Transaction.cs

1. Add “SetUserId” taking a string and returning void
2. In SetUserId, call “TransactionMetadata.UserAndRequestAttributes.TrySetValue” with the EndUserId definition and the userid value.

Core/NoOpTransaction.cs

1. Add “SetUserId” taking a string and returning void
2. The body should just “return;” like the other methods.

CustomErrorDataTransformer.cs

Note: if the string is null or empty, do not add the attrtibute!

1. Update the “ICustomErrorDataTransformer.Transform” interface to add a string parameter named, userid.
2. Update “CustomErrorDataTransformer.Transform” to add a string parameter named, userid.
3. In “Transform”, just before the calls to the *makers,  set the EndUserId definition to the userid.
4. Some tests will need to updated with the new signature.

AgentApiImplementation.cs

Note: if the string is null or empty, do not add the attrtibute!

1. Update “ProcessNoticedError” to take a new string parameter named, userid.
2. Add a new private “ProcessNoticedError”, using the same signature as the existing one, without the userid parameter.  
3. In the new “ProcessNoticedError”, call the updated ProcessNoticedError (with userid) using string.Empty for the missing userid.
4. In updated “ProcessNoticedError” and inside the “transaction != null” if, add a call to transaction.SetUserId using the userid.
5. In updated “ProcessNoticedError” and after the if block, update the call to _customErrorDataTransformer.Transform to include the user id.

### Acceptance Criteria
- Agent should build

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
S

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1405?planning-poker) with Zenhub @tippmar-nr @jaffinito @JcolemanNR

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1405?planning-poker) with Zenhub @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1405?planning-poker) with Zenhub @chynesNR
