### ISSUE TITLE
User Tracking: API plumbing

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1406]
### Describe the story, please be clear on scope of the story.
Add the new duplicate NoticeError methods and the SetUserId API calls.

TransactionBridgeApi.cs

1. Add a new method called “SetUserId” that takes a string and returns void.
2. In “SetUserId”, use _apiSupportabilityMetricCounters to record ApiMethod.SetUserId
3. Call _transaction.SetUserId with the userid
4. Wrap the above in a try-catch matching how the other methods in this class are set up.

API/ITransaction.cs

1. Add “SetUserId”, taking a string and returning void to the interface.

API/Transaction.cs

1. Add a private  static bool called “_isSetUserIdAvailable” and set it to true.
2. Add a new method called “SetUserId” that takes a string and returns void.
3. In “SetUserId, check if _isSetUserIdAvailable is true and return if false.
4. In “SetUserId, and inside a try-catch, check if userid is null or whitespace.
5. If null/whitespace,  call _wrappedTransaction.SetUserId using string.Empty
6. Else, call _wrappedTransaction.SetUserId with the userid
7. In “SetUserId, set up the catch in the same manner as the other methods.

API/NoOpTransaction.cs

1. Add a new method called “SetUserId” that takes a string and returns void.
2. Leave the method empty, same as the other methods

~~.NoticeError~~  We will not be implementing this.

~~1. All of the existing NoticeError API methods will need to be duplicated and the duplicates updated with a new string parameter named userid.~~
~~2. This is a lot of work.~~
~~3. I didn’t get far enough to include this in the branch since its a lot of work.~~

### Acceptance Criteria

- Agent should build
- Smoke test: Load API into app and make sure methods are available and work

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
M

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1406?planning-poker) with Zenhub @jaffinito @JcolemanNR @tippmar-nr

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1406?planning-poker) with Zenhub @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1406?planning-poker) with Zenhub @chynesNR
