### ISSUE TITLE
User Tracking: Tests

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1407]
### Describe the story, please be clear on scope of the story.
Add Unit and/or Integration tests for the new API call.

### Acceptance Criteria

- Agent should build
- new and old test should pass

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
M

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1407?planning-poker) with Zenhub @jaffinito @JcolemanNR @tippmar-nr

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1407?planning-poker) with Zenhub @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1407?planning-poker) with Zenhub @chynesNR
