### ISSUE TITLE
User Tracking: Documentation

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#1408]
### Describe the story, please be clear on scope of the story.
Update our API documentation to add pages for the new API call. Make sure the docs match the method summaries in code. 

This also includes updating our NoticeError documentation to include the new userid parameter.

### Acceptance Criteria
Docs are deployed.

### Additional context
**Feature Branch: feature/errorsinbox-fingerprinting-usertracking**

Experimental branch: https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental-errorsinbox-improvements

### Estimates
S

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1408?planning-poker) with Zenhub @JcolemanNR @tippmar-nr @nrcventura

**Comment by jaffinito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/1408?planning-poker) with Zenhub @chynesNR
