### ISSUE TITLE
Postgres Instrumentation - Instrument NpgSqlCmd.ExecuteReaderAsync

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#142]
### Is your feature request related to a problem? Please describe.
Need to instrument an additional path for NpgSql 4.1.3.1

### Feature Description
NpgSql 4.1.3.1

<pre>
using (var connection = new NpgsqlConnection(_connectionString))
           using (var command = new NpgsqlCommand("SELECT * FROM public.TestGTSE1877(:arg0,:arg1,:arg2);", connection))
			{
				connection.Open();
				command.Parameters.AddWithValue(":arg0", "Jason");
				command.Parameters.AddWithValue(":arg1", "Jason");
				command.Parameters.AddWithValue(":arg2", 32);

				using (var reader = command.ExecuteReader())
				{
</pre>
The above sample code did not get instrumented by default.
Upon following the execution path, it seems that

<pre>
NpgSqlCmd.ExecuteReader() 
   NpgSqlCmd.ExecuteReader(CmdBehavior)
      NpgSqlCmd.ExecuteReaderAsync(CmdBehavior, bool, CancellationToken)
</pre>
This path is not being instrumented.

### Describe Alternatives
N/A

### Additional context
Originated from DOTNET 4668
The reporter was Jason F.

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by lspangler584** [comment]
Feature request, assigning to PM for evaluation.
