### ISSUE TITLE
Validate release note metadata

### ISSUE THREAD

**Issue by chynesNR** [newrelic/newrelic-dotnet-agent#1454]
After completion of the other stories, validate that the docs site has picked up and parsed the metadata correctly.

### Acceptance Criteria
All release notes should validate.

### Estimates
S/M

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/APM-Agent-Overview-614b054ff9a50b000f9039d7/issues/newrelic/newrelic-dotnet-agent/1454?planning-poker) with Zenhub @chynesNR @JcolemanNR
