### ISSUE TITLE
v10.8.0 nlog structured logs are not enriched by agent for APM Logs with Context

### ISSUE THREAD

**Issue by JanHergenhan** [newrelic/newrelic-dotnet-agent#1459]
**Description**
I just updated to the NewRelic.Agent v10.8.0 and noticed that some of my logs are no longer enriched for APM Logs with Context by the agent (eg no entity.guid).
Digging deeper into the problem I found out that this only concerns logs that rely on the nlog structured logging feature https://github.com/NLog/NLog/wiki/How-to-use-structured-logging. Logs like `_logger.LogDebug("Start Request: {@request}", request);` are no longer enriched by the APM agent and accordingly cannot be traced. 

In #1393 changes were made regarding nlog and LogEventInfo

**Expected Behavior**
The logs that were enriched in v10.7.0 shall be enriched in newer versions.

**Steps to Reproduce**
Hopefully you can reproduce this by simply creating logs where nlog is asked to serialize an object to json: `_logger.LogDebug("Start Request: {@request}", request);`

**Your Environment**
.NET 6
nLog 5.1
NewRelic.Agent v10.8.0

```
    <target type='WebService'
                name='fluentd'
                url='https://....'
                protocol='JsonPost'
                encoding='UTF-8'   >

      <parameter name="datetime" layout="${date}" />
      <parameter name="level" layout="${level}" />
      <parameter name="application" layout="${environment:APP_NAME:whenEmpty=${hostname}}" />
      <parameter name="environment" layout="${aspnet-environment}" />
      <parameter name="loggername" layout="${logger}" />
      <parameter name="message" layout="${message}" />
      <parameter name="exception" layout="${exception:format=@}" />

      <!-- former MDLC parameters -->
      <parameter name="scope.connection.id" layout="${scopeproperty:item=ConnectionId}" />
      <parameter name="scope.request.id" layout="${scopeproperty:item=RequestId}" />
      <parameter name="scope.request.path" layout="${scopeproperty:item=RequestPath}" />
      <parameter name="scope.action.id" layout="${scopeproperty:item=ActionId}" />
      <parameter name="scope.action.name" layout="${scopeproperty:item=ActionName}" />

    </target>
```

**Comment by nrcventura** [comment]
@JanHergenhan thank you for letting us know about this regression. I was able to reproduce it and identify the problem. 

We are still working towards improving our support for log decoration especially when both NLog and Microsoft.Extensions.Logging are both involved. As an example `_logger.LogDebug("Start Request: {@request}", request);` previously worked but `_logger.LogDebug("Start Request: {request}", request);` did not and still does not work.  

I want to see this usage added to our test coverage so that we can protect against a future regression.

**Comment by JanHergenhan** [comment]
@nrcventura 
I assume the fix will be rather part of 10.9 than 10.8.1?

**Comment by the-Hill** [comment]
> but `_logger.LogDebug("Start Request: {request}", request);` did not and still does not work

@nrcventura When will this be fixed?

**Comment by nrcventura** [comment]
> > but `_logger.LogDebug("Start Request: {request}", request);` did not and still does not work
> 
> @nrcventura When will this be fixed?

I don't have any information about when that will be addressed. I recommend submitting a feature request for it so that you can follow it.
