### ISSUE TITLE
Wcf.Client.Self integration test instability issues

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1500]
### Describe the story, please be clear on scope of the story.

Recently, several PRs have been held up for as long as a day because the `Wcf.Client.Self` integration tests have failed repeatedly, requiring as many as six re-runs to get them to pass.  Solving this issue should be a high priority to improve team productivity.

Example PRs:
https://github.com/newrelic/newrelic-dotnet-agent/pull/1489
https://github.com/newrelic/newrelic-dotnet-agent/pull/1470

Since we started tracking overnight test run failures again last month, there have been failures in the `Wcf.Client.Self` namespace in 10 out of 35 runs.  (17/35 if we consider all Wcf integration test namespaces)

The nature of the failures, as far as they are currently detected by the test harness, are mismatched between the expected number of examples of some data being generated by the agent and what is actually observed.  Examples:
```
Assertion #1: TrueException on line 95: Metric named DotNet/ConsoleMultiFunctionApplicationFW.NetFrameworkLibraries.WCF.WCFClient/ThrowException scoped to OtherTransaction/Custom/ConsoleMultiFunctionApplicationFW.NetFrameworkLibraries.WCF.WCFClient/ThrowException had an unexpected count of 7 (Expected 8)

Metric named OtherTransaction/Custom/ConsoleMultiFunctionApplicationFW.NetFrameworkLibraries.WCF.WCFClient/ThrowException scoped to nothing had an unexpected count of 7 (Expected 8)

Metric named DurationByCaller/Unknown/Unknown/Unknown/Unknown/all scoped to nothing had an unexpected count of 11 (Expected 12)

Incorrect Number of Spans, Expected 30, Actual 32
Client Transaction Count - Expected 12, Actual 11
```

Note that it isn't always that the number of metrics/events/spans/whatever is too low.

We don't know the root cause of the mismatches at this point.

### Acceptance Criteria
Wcf.Client.Self integration tests pass reliably in CI, both overnight and on PRs.

### Describe Design Consideration/Limitations
We are testing WCF instrumentation fairly exhaustively.  It might be worth considering how much value this is bringing relative to the amount of toil.

### Estimates
L

**Comment by nrcventura** [comment]
In some of the runs, a whole transaction was missed (not sure if it was missed or just not transformed and transmitted before the application exited). Just adding this here as a breadcrumb for when this issue is worked on.
