### ISSUE TITLE
Documentation: Run UnboundedIntegrationTests locally

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#152]
The process for running UnboundedIntegrationTests locally will change with this Milestone. Formerly, services required for running these tests were maintained on a server(s) in Jenkins. With this Milestone, scripts will create local Docker containers for the various services required.

New scripts and Docker files have been added to the repo. Documentation will describe how to use these scripts to set up the local environment for running these tests.

One thing that will be useful to document is how to run each service individually instead of having to launch them all and wait 10 minutes if they're testing something that only needs one service: https://docs.docker.com/compose/reference/run/  (especially the --service-ports option)

**Comment by nr-ahemsath** [comment]
Documentation has been added to `tests/Agent/IntegrationTests/UnboundedServices/README.md`
