### ISSUE TITLE
Memory leak in agent 10.9.1

### ISSUE THREAD

**Issue by MrSmoke** [newrelic/newrelic-dotnet-agent#1539]
**Description**
It seems that after upgrading from `10.5.1` to `10.9.1` we are seeing increased memory usage. I know there was some work done recently to fix the memory leak in the redis wrapper in 10.9.1 (https://github.com/newrelic/newrelic-dotnet-agent/commit/925d016c145b50b75a3b3401de303f5fa9a64609) but it still seems to be happening.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag/) results**
I took memory dumps of our services running and noticed there are a lot of `NewRelic.Agent.Core.Segments.Segment` objects sitting in memory, mostly in Gen2 heap. The session cache in the `StackExchangeRedis2Plus` seemed to be holding on to quite a few of these references.

This is a list of all objects in gen2 ordered by inclusive size. All top objects are mostly new relic related:
![Screenshot from 2023-04-13 11-16-03](https://user-images.githubusercontent.com/709976/231623217-edf4cc2c-c83f-493d-aa90-8128ac10741a.png)

**Steps to Reproduce**
- I found this was happening with agent `10.7.0` and `10.9.1`. Rolling back to `10.5.1` seems to have fixed it.

**Your Environment**
- .NET Core 6
- Docker

**Comment by MrSmoke** [comment]
Here are some memory usage graphs

This is after upgrading to `10.9.1`
![image](https://user-images.githubusercontent.com/709976/231624175-f42c320e-cc67-4ab9-b5e8-aeeffbdb688c.png)


This is after downgrading from `10.9.1` to `10.5.1`
![image](https://user-images.githubusercontent.com/709976/231624291-e667c712-4f48-4c41-9fc1-2f7a554fa791.png)

**Comment by tippmar-nr** [comment]
Thanks for your report, @MrSmoke! 

We're currently investigating and will update the status of this issue as soon as possible. 

Could you let us know what version of the `StackExchange.Redis` NuGet package you're using? 

Also, if you could provide some sample code that demonstrates the behavior you're seeing, that would be a great help!

**Comment by MrSmoke** [comment]
Hey @tippmar-nr,

We were previously on `2.6.48` and then upgraded to `2.6.104` to see if that would fix anything but it did not.

As for sample code, that may bit a bit difficult as its on a large API of ours :sweat_smile:, however its not doing anything to radical. Just using redis for caching API calls to other services.

**Comment by tippmar-nr** [comment]
Hi @MrSmoke 

After taking a look, I believe [New Relic Support](https://github.com/newrelic/newrelic-dotnet-agent#support) would be the best place to take next steps on this issue.
You can engage the [New Relic Support Community](https://discuss.newrelic.com/) or open a [support ticket](https://support.newrelic.com/new-ticket), depending on your support level.  Please provide a link to this GitHub issue when submitting your community post or support ticket.

**Comment by satuday** [comment]
I'm also seeing memory leak with version `10.0.0`  after upgraded our app from .net core 2.1 to .net core 6.

![image](https://github.com/newrelic/newrelic-dotnet-agent/assets/4556198/d8a055cb-997f-45c1-911c-579f44947cba)

**Comment by satuday** [comment]
for future viewers. I was able to fix the memory leak after switching back to `newrelic-netcore20-agent` from `newrelic-dotnet-agent`. My app is a .net core 6 console app, so it does not support Automatic instrumentation. I have to use [Custom instrumentation via attributes (.NET)](https://docs.newrelic.com/docs/apm/agents/net-agent/custom-instrumentation/custom-instrumentation-attributes-net/) to add instrumentation to my app. After updating the agent to  `newrelic-dotnet-agent` from `newrelic-netcore20-agent`, it started to leak memory.

**Comment by sean-cimpress** [comment]
I also noticed a memory leak in one of our net7 applications when running on version `10.9.1` and on `10.11.0`. Once we reverted to `10.5.1` memory stabilized again (as noted in [this comment](https://github.com/newrelic/newrelic-dotnet-agent/issues/1539#issuecomment-1506197661) above).
