### ISSUE TITLE
MVC Invalid Action for valid Controller can cause MGI

### ISSUE THREAD

**Issue by nrcventura** [newrelic/newrelic-dotnet-agent#155]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
If an invalid method (controller action) is specified in a route, but the controller is valid, the system records a transaction.   This can be problematic when there are phishing attempts and/or security audits of sites looking for vulnerabilities.

**Expected Behavior**
This is something that still needs to be decided. Should we just not apply the MVC controller-action naming, or should we provide some sort of "invalid" controller-action name that allows these types of requests to be rolled up. I do not think that these types of requests should be marked as ignored.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
N/A

**Steps to Reproduce**
Simply make a request that is routed to a valid controller but doesn't have a method for the action that's requested.

**Your Environment**
N/A

**Additional context**
See [internal link](https://newrelic.atlassian.net/browse/DOTNET-4087) for the original issue.

For example:
Account/Edit/32, Valid controller, valid action

Account/XYZABDCDRE, Valid controller, invalid action  → still

CONT1234/Edit, invalid controller  →  Should double check, but likely covered by current agent behavior

**Impact**

While this does not happen very often, there isn’t really a workaround to help customer experiencing issue.

**Comment by tehbio** [comment]
After some testing and discussion with @vuqtran88, there does not seem to be any issues with routing and MGI generation with the default MVC pipeline.

Depending on user code and other middleware being included this can change, but is not an issue with MVC instrumentation.
