### ISSUE TITLE
NLog 5.1.3 structured logs are not enriched by agent for APM Logs with Context

### ISSUE THREAD

**Issue by the-Hill** [newrelic/newrelic-dotnet-agent#1609]
**Description**
I just updated NLog from version 4.7.15 to 5.1.3 and noticed that some of my logs are no longer enriched for APM Logs with Context by the agent (eg no entity.guid).
Some structured NLog logs (https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#using-structured-logging) are no longer enriched by the APM agent and accordingly cannot be traced. Sample log format: `_logger.LogDebug("Start Request: {request}", request);`
Also many logs from System and Microsoft which has variable context are no longer enriched. Sample: `Hosting environment: Development` from logger `Microsoft.Hosting.Lifetime`.

**Expected Behavior**
The logs that were enriched with NLog 4.7.15 shall be enriched with NLog 5.1.3.

**Steps to Reproduce**
Write structured NLog (https://github.com/NLog/NLog/wiki/How-to-use-structured-logging#using-structured-logging) like:
`_logger.LogDebug("Start Request: {request}", request);`

**Your Environment**
.NET 6
NLog 5.1.3
NLog.Extensions.Logging 5.2.3
NLog.Web.AspNetCore 5.2.3
Microsoft.Extensions.Logging 6.0.0
NewRelic.Agent 10.10.0

NLog config:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="internal-nlog.txt">

    <extensions>
        <add assembly="NLog.Web.AspNetCore" />
    </extensions>

    <targets async="true">

        <target name="logconsole" xsi:type="Console">

            <layout xsi:type="JsonLayout">
                <attribute name="datetime" layout="${date}" />
                <attribute name="level" layout="${level}" />
                <attribute name="application" layout="${environment:APP_NAME:whenEmpty=${hostname}}" />
                <attribute name="environment" layout="${aspnet-environment}" />
                <attribute name="loggername" layout="${logger}" />
                <attribute name="message" layout="${message}" />
                <attribute name="exception" layout="${exception:format=@}" />

                <!--MDLC Properties-->
                <attribute name="scope.connection.id" layout="${scopeproperty:item=ConnectionId}" />
                <attribute name="scope.request.id" layout="${scopeproperty:item=RequestId}" />
                <attribute name="scope.request.path" layout="${scopeproperty:item=RequestPath}" />
                <attribute name="scope.action.id" layout="${scopeproperty:item=ActionId}" />
                <attribute name="scope.action.name" layout="${scopeproperty:item=ActionName}" />
            </layout>
        </target>

    </targets>
    <rules>
        <logger name="System.*" finalMinLevel="Warn" writeTo="logconsole" />
        <logger name="System.Net.Http.*" finalMinLevel="Info" writeTo="logconsole" />
        <logger name="Microsoft.*" finalMinLevel="Warn" writeTo="logconsole" />
        <logger name="Microsoft.Hosting.Lifetime*" finalMinLevel="Info" writeTo="logconsole" />

        <logger name="*" minlevel="Trace" writeTo="logconsole" />
    </rules>
</nlog>
```

Docker build file:
```
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-bullseye-slim-arm64v8

WORKDIR /app
COPY ./app .

ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
ENV CORECLR_NEWRELIC_HOME=/app/newrelic
ENV CORECLR_PROFILER_PATH="/app/newrelic/linux-arm64/libNewRelicProfiler.so"

ENV NEW_RELIC_APPLICATION_LOGGING_ENABLED=true
ENV NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=false
ENV NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=true

EXPOSE 7190

ENTRYPOINT ["./com.Sample"]
```

**Additional context**
Related to #1459

**Comment by nr-ahemsath** [comment]
Thanks for taking the time to create an issue in our repo, @the-Hill.   Based on the previous conversation in issue #1459, I believe this is a feature request for our agent, not a bug.  I'll make sure our product management is aware of our agent's functionality gap for your use case and they will consider that when prioritizing our roadmap.

**Comment by the-Hill** [comment]
Hello @nr-ahemsath according to [.NET agent logs in context](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/) NLog 4.5+ (.NET Core) with .NET Agent v9.7.0+ should be supported.
`NLog: 4.1+ (.NET Framework), 4.5+ (.NET Core). Requires .NET Agent v9.7.0+.`
