### ISSUE TITLE
Remove localhost from secrets

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#163]
### Description
With the move of services for UnboundedIntegrationTests to local Docker containers, references to the Jenkins database server ip addrs have been replaced with 127.0.0.1. These host addresses are no longer 'secrets' and can be moved back into the configuration in the solution.

This change implies changes to test configuration code and changes to the secrets stored in Jenkins (and LastPass).

**Comment by nr-ahemsath** [comment]
We've decided to maintain the current architecture as it gives us the flexibility to easily change how these tests connect to their external resources.
