### ISSUE TITLE
External Calls create MGI

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#164]
**Description**
```^(External)(App|Transaction){0,1}(/)[^/]+(/.*)$

External/12000etreshumains-rh.profils.org/Stream/GET
ExternalApp/webhelp.talent-soft.com/252541#17467371/all
ExternalTransaction/zebulon.talent-soft.com/252541#17467271/WebTransaction/WebAPI/Statistics/GetUiCultureOfUsers

->

External/*/Stream/GET
ExternalApp/*/252541#17467371/all
ExternalTransaction/*/252541#17467271/WebTransaction/WebAPI/Statistics/GetUiCultureOfUsers
```
**Expected Behavior**

**Troubleshooting **

**Steps to Reproduce**

**Your Environment**

**Additional context**

** MISC **
[Internal Process]
[Zendesk](https://newrelic.zendesk.com/agent/tickets/332732)

The initial investigation leads to this as more of an agent spec problem with CAT

**Comment by angelatan2** [comment]
This issue is inherent in how CAT works.  It will not apply with Distributed Tracing.

**Comment by tehbio** [comment]
Trying to solve this issue would go against [agent specifications](https://source.datanerd.us/agents/agent-specs/blob/main/Cross-Application-Tracing-PORTED.md) and is part of the reason why CAT is deprecated in favor of DT, so it seems very unlikely we'd ever prioritize this work.
