### ISSUE TITLE
When transactionTracer.enabled = false, we generate explain plans w/ no data

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#168]
**Description**
When transactionTracer.enabled = false, we grab a SqlObfuscator that returns null for all values. This results in time being spent generating explain plans but then we null out everything. See TransactionTransformer.TryGenerateExplainPlans() and DataStoreSegmentBuilder.ExecuteExplainPlan()

This behavior seems like a bug. 

**Expected Behavior**
although explain plans are put into transaction traces, the main purpose is to put them into slow-sqls (aka slow query traces).  So if your agent creates slow-sqls when `transactionTracer.enabled = false`, I think you should still generate an explain plan.  (the relationship between slow-sql configuration and transaction-trace configuration is murky:  some agents have all slow-sql configuration under the transactionTracer namespace (I think))

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]

**Steps to Reproduce**

**Your Environment**

**Additional context**
Migrated from an original issue.

**Comment by jaffinito** [comment]
Other agents have SlowSQL under transaction tracer or not at all (Java, PHP, Python). Ruby does have a distinct SlowSQL setting, with its own explain plan settings that are distinct from TransactionTracer. Go has everything under the DataStoreTracer. NodeJS is more similar to our implementation, though the docs call out that this does not affect transaction traces.
Our implementation does not match the other agents or the description of the feature in the docs.
