### ISSUE TITLE
NLog log forwarding does not capture logs passed directly to an NLog logger

### ISSUE THREAD

**Issue by nrcventura** [newrelic/newrelic-dotnet-agent#1680]
### Is your feature request related to a problem? Please describe.

The application log forwarding implementation when both MEL and NLog are present is incomplete. The current implementation will capture the log messages that pass through a MEL logger, but it does not capture the log messages that pass through a NLog logger.

### Feature Description
When both MEL and NLog are present log messages written to a MEL logger or a NLog logger should both be captured by the agent. We need to ensure that duplicate log messages are not forwarded.

### Describe Alternatives

The current alternatives approaches are:

1. Send all log messages through the MEL logger instead of the NLog logger.
2. Do not use agent application log forwarding support to send the logs to New Relic

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 

Must Have

**Comment by chynesNR** [comment]
This was addressed in 10.15.0
