### ISSUE TITLE
MongoDb ops / min query for metrics stopped reporting since Jun 8 2023

### ISSUE THREAD

**Issue by vmandic** [newrelic/newrelic-dotnet-agent#1719]
## Description

Since Jun 8th 4:15 AM UTC we stopped receiving metrics data for our MongoDb ops / min chart, the query is:

```sql
SELECT 
sum(mongodb_top_getmore_count), 
sum(mongodb_top_insert_count), 
sum(mongodb_top_updates_count), 
sum(mongodb_top_remove_count), 
sum(mongodb_top_commands_count), 
sum(mongodb_top_queries_count) 
FROM Metric 
SINCE 1 HOUR AGO TIMESERIES 1 minute
```

We DID NOT DO ANY CHANGES in this period, so no code deploy and neither hosting related or network changes that we know of. Other metrics did not suffer from not reporting, we did not observe any other change. We observed a drop in our "manage your data" view data ingestion for metrics for somewhat 6-8 GB less daily since Jun 8th.

As far as we have explored we have NOT done any changes that might impact this.

Our latest big change was 7 days earlier, an upgrade from .NET 3.1 to .NET7 SDK and TFM.

Agent nuget version is: 10.9.1 and we install it as sidecar in our docker containers via shell.

## Expected Behavior

We expect to see metrics data in the chart ie. the query to return MongoDB ops / min data.

## Resulting Behavior

MongoDb ops / min metric is not reported and not seen in our main dashboard chart.

There are no logs to provide.

## Steps to Reproduce

Log in to our account and open the problematic chart in our main dashboard. Filter out the period from 5th to 9th June 2023 to see the drop.

Chart name is "MongoDB Ops Per Minute".

https://one.newrelic.com/dashboards/detail/NjMzOTg3fFZJWnxEQVNIQk9BUkR8ZGE6Mjk1MjIxMA?account=633987&begin=1685976817021&end=1686263361702&state=31e95b16-b060-b9a3-d8d6-f6260ccea15c

## Your Environment

- paying user, account ID: 633987
- .NET7
- SDK 7.0.203
- docker runtime image: `mcr.microsoft.com/dotnet/runtime-deps:7.0-alpine`, runs under swarm, multi-services using this Agent and reporting metrics for years now
- Agent ` <PackageReference Include="NewRelic.Agent.Api" Version="10.9.1" />`

## Additional context

This stopped out of the blue on that Thursday without us interacting anyhow?

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by vmandic** [comment]
What can I do? Do I need to report this elsewhere? Thanks.

**Comment by jaffinito** [comment]
This [link](https://support.newrelic.com/s/) should get you to the right place to submit a ticket and get the process started.  Support will be able to work with you to gather logs and other sensitive data so that we can troubleshoot the issue.

**Comment by vmandic** [comment]
OK, our account does not have specialized support access I think so I opened this ticket here: https://forum.newrelic.com/s/hubtopic/aAX8W0000015B6UWAU/mongodb-ops-min-query-for-metrics-stopped-reporting-since-jun-8-2023

You folks sure no changes on your side in that period?

**Comment by nrcventura** [comment]
This repo is for the New Relic .NET agent, so the only way for there to be a change would be if you installed a different agent version during that time window. However, you mentioned that you did not change which agent version was used during that time. The forum post you opened gets more visibility than tickets opened in this repo which should help with getting the most appropriate people to see your question and come up with an answer sooner. I'm also not certain that those metrics you are referring to come from the .net agent. The .net agent typically doesn't capture metrics with names like the ones you mentioned in your query.

**Comment by vmandic** [comment]
Thanks for reaching out @nrcventura. You got me thinking so there is a possiblity one thing changes as we get latest with our script and thats the sidecar agent we install in docker like:

```docker
...
# Install the New Relic agent
RUN mkdir /usr/local/newrelic-dotnet-agent \
&& cd /usr/local \
&& export NEW_RELIC_DOWNLOAD_URI=https://download.newrelic.com/$(wget -qO - "https://nr-downloads-main.s3.amazonaws.com/?delimiter=/&prefix=dot_net_agent/latest_release/newrelic-dotnet-agent" | grep -E -o 'dot_net_agent/latest_release/newrelic-dotnet-agent_[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}_amd64\.tar\.gz') \
&& echo "Downloading: $NEW_RELIC_DOWNLOAD_URI into $(pwd)" \
&& wget -O - "$NEW_RELIC_DOWNLOAD_URI" | gzip -dc | tar xf -

# Enable the New Relic agent
ENV CORECLR_ENABLE_PROFILING=1
...
``` 

Looking at our build logs we can confirm that the agent stayed in same version like with the release few days earlier (2023-06-01), the logs on 5th evaluated like:

```log
...
#34 1.302 Downloading: https://download.newrelic.com/dot_net_agent/latest_release/newrelic-dotnet-agent_10.10.0_amd64.tar.gz into /usr/local
#34 1.305 --2023-06-05 09:48:58--  https://download.newrelic.com/dot_net_agent/latest_release/newrelic-dotnet-agent_10.10.0_amd64.tar.gz
...
```

Our next release a week later (after this incident is noticed) takes a newer version of sidecar NR dotnet agent but we notice NO changes, ie. the metrics are still NOT reported.

Note that 3 days passed since the release we made on 5th till 8th and then as said out of the blue metrics stop, without our interventions as much as we know so far.

The log for next release (made on 2023-06-14) evaluates as:

```log
...
#31 1.029 Downloading: https://download.newrelic.com/dot_net_agent/latest_release/newrelic-dotnet-agent_10.11.0_amd64.tar.gz into /usr/local
#31 1.031 --2023-06-14 12:15:20--  https://download.newrelic.com/dot_net_agent/latest_release/newrelic-dotnet-agent_10.11.0_amd64.tar.gz
...
```

This is still ongoing in our dashboard.

Looking detailed in our data ingestion we can see that the drop actually starts on the 6th of June per screenshot:

<img width="977" alt="image" src="https://github.com/newrelic/newrelic-dotnet-agent/assets/1390895/4cc0d54a-d831-4770-ad55-2810ad19f9af">

**Comment by nrcventura** [comment]
I'm wondering if you also rely on infrastructure monitoring or kubernetes monitoring, or use some plugin to gather telemetry directly from mongodb. To see that large a drop in data, it makes me think that something other than the agent changed. Unfortunately, I do not have visibility into that, but the support team that monitors the forum should be able to help you track that down.

**Comment by tippmar-nr** [comment]
@vmandic Since you are getting assistance via our support forum, I'm going to go ahead and close this ticket. Please utilize the forum for additional assistance on this issue. Thanks!
