### ISSUE TITLE
Automated Linux Smoke Testing

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#1777]
### What we want

We want to have some automated testing of the agent for the various Linux distros and CPU architectures we support running the agent on.  This should include, at least:

`amd64` (Intel 64-bit) distros
Latest Ubuntu LTS version (22.04)
Latest Alpine version (3.18)
Latest Debian version (12)
Latest Centos/RHEL version

`arm64` distros
Latest Amazon Linux version
Latest Ubuntu LTS (22.04) 

This list is based, in part, on what platforms Microsoft provides prebuilt Docker images for .NET 7: https://hub.docker.com/_/microsoft-dotnet-sdk/
It is also based on what distros are supported by AWS Gravitron (hence the Amazon Linux requirement)

### How to do it

- We run our CI in GHA
- GHA only has a limited number of Linux distros available natively as runners (see list here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)
- Therefore, we need to figure out how to run the integration tests in Docker containers that can be launched from a GHA-hosted runner
- Since we will be running these tests on many platforms, we don't want to run the full integration test suite.  Therefore, we need a way to filter the tests that will be executed down to a small subset sufficient to "smoke test" the agent on each platform.  We currently use some XUnit attributes for filtering `NetCore` vs. `NetFramework` and we could create a similar attribute called something like `LinuxSmokeTest` and apply it to the tests we want included.

Prototype branch here: https://github.com/newrelic/newrelic-dotnet-agent/tree/exp/dockerized-linux-integration-tests

### Acceptance Criteria
Smoke test running successfully in GHA for the list of distros/architectures above.
Note: not sure if this needs to run on every PR.  Probably not, in fact.  Could be part of release workflow, nightly workflow, or any profiler changes (profiler changes tend to be what cause problems for the agent on Linux)

### Estimates
Please provide initial t-shirt size: XL

**Comment by nrcventura** [comment]
This work was completed in #1801.
