### ISSUE TITLE
.net 5 support

### ISSUE THREAD

**Issue by mangod9** [newrelic/newrelic-dotnet-agent#179]
.net 5 RC1 would be releasing soon, hoping the .net agent is being validated with preview builds of .net 5. 

Also Hi @nr-ahemsath @alanwest @nrcventura @jaffinito @jifeingo @lspangler584 @vuqtran88 @elucus :).

**Comment by nr-ahemsath** [comment]
Yes, we are doing that as they come out.  Thanks for checking in!
