### ISSUE TITLE
Release automation: Validate apt/yum packages

### ISSUE THREAD

**Issue by chynesNR** [newrelic/newrelic-dotnet-agent#1806]
Part of our release process involves manually checking to make sure the new build is available on apt/yum. It would be nice if we could automate this validation. Validating the contents is not necessary; just make sure the new build version is there.

### Estimates
S/M

**Comment by jaffinito** [comment]
The download site/S3 side of this will be handled via https://github.com/newrelic/newrelic-dotnet-agent/pull/1811

As for validating the packages and repo were not broken, we can add a job to a workflow that attempts to pull in NR and download the package. We don't have a workflow for this job just yet - will discuss.
