### ISSUE TITLE
MSMQ instrumentation shuts down after too many exceptions

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#184]
We don't deal with the QueueName Property in MSMQ properly.
Without doing so, Agent exceptions can be thrown, that we don't handle well, and eventually shut down.

**[Troubleshooting]

 10:55:43,394 NewRelic ERROR: Tracer invocation error: System.Messaging.MessageQueueException (0x80004005): The specified format name does not support the requested operation. For example, a direct queue format name cannot be deleted.2019-09-23 11:23:19,616 NewRelic ERROR: Wrapper 
..
..
..
NewRelic.Providers.Wrapper.Msmq.SendInternalWrapper is being disabled for SendInternal due to too many consecutive exceptions. All other methods using this wrapper will continue to be instrumented. This will reduce the functionality of the agent until the agent is restarted.

**Steps to Reproduce**

**Your Environment**

**Additional context**

**Comment by angelatan2** [comment]
Moved to Github Issues
https://github.com/newrelic/newrelic-dotnet-agent/issues/184

**Comment by angelatan2** [comment]
We do not have a reproduction of this issue and no supporting ticket to track details.  We also have not observed recent issues with MSMQ.

**Comment by mesteves** [comment]
Hi @angelatan2 

I'm also getting the same error.

`2022-05-24 14:13:15,799 NewRelic  ERROR: [pid: 8776, tid: 23] Tracer invocation error: System.Messaging.MessageQueueException (0x80004005): The specified format name does not support the requested operation. For example, a direct queue format name cannot be deleted.
   at System.Messaging.MessageQueue.**GenerateQueueProperties**()
   at System.Messaging.MessageQueue.**get_QueuePath**()
   at System.Messaging.MessageQueue.**get_QueueName**()
   **at NewRelic.Providers.Wrapper.Msmq.SendInternalWrapper.BeforeWrappedMetho**d(InstrumentedMethodCall instrumentedMethodCall, IAgent agent, ITransaction transaction)
   at NewRelic.Agent.Core.Wrapper.WrapperService.BeforeWrappedMethod(Type type, String methodName, String argumentSignature, Object invocationTarget, Object[] methodArguments, String tracerFactoryName, String metricName, UInt32 tracerArguments, UInt64 functionId)
   at NewRelic.Agent.Core.AgentManager.GetTracerImpl(String tracerFactoryName, UInt32 tracerArguments, String metricName, String assemblyName, Type type, String typeName, String methodName, String argumentSignature, Object invocationTarget, Object[] arguments, UInt64 functionId)
`

Is this of any help to troubleshoot ? 

APM Agent Version: 8.41.0.0

Best regards,
Manuel

**Comment by vuqtran88** [comment]
@mesteves 
Thanks for reporting this to us. We would like to get more information from you so that we can reproduce this behavior. Could you provide the followings ?

1. What is the runtime that your application is targeting ?
2. What is the version of the `System.Message` assembly your app is using ?
3. A sample of your code app that would trigger this instrumentation.

Thank you,
