### ISSUE TITLE
Agent fails to execute explain plan - MS SQL

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#185]
**Description**
The agent fails to execute the explain plan for the following scenarios:

**Scenario 1:** 
The agent can fail to execute explain plan for parameterized stored procedure. This occurs where the parameters are not included in the command text. Because of this, the agent fails to generate correct sql queries to run explain plan. The repro code is as follows. 

```
var connectionString = ApplicationConfiguration.MSSQLConnectionString;

		using (var connection = new SqlConnection(connectionString))
			{
				connection.Open();

				using (var command = new SqlCommand(@"storedprocedurename", connection))
				{
					command.CommandType = CommandType.StoredProcedure;

					command.Parameters.Add(new SqlParameter("@parameter1", 123));
					command.Parameters.Add(new SqlParameter("@parameter2", 456));

					return command.ExecuteNonQuery();
				}
			}
```

**Scenario 2:**
The agent fails to execute explain plan for parameterized sql queries that has parameters of "rowversion" or other special types. The agent incorrectly parses the explain plan queries for these types.

Suggestion: Look into Config setting about this to see if this is part of the issue.

**Expected Behavior**

**Comment by jaffinito** [comment]
Partially improved the second scenario in #477 by not running explain plans when we cannot efficient;y or properly get a serialized version of the parameter value.  The amount of errors generated by incorrect explain plans should go down by a good amount.
