### ISSUE TITLE
RabbitMQ instrumentation does not support distributed tracing when using BasicGet()

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#187]
**Description**
BasicGetWrapper.cs wraps Rabbit method _Private_BasicGet, which does not return or provide access to the Rabbit message. Therefore, the result parameter in AfterWrapped(dynamic result) is always null, which causes an early exit, bypassing the processing of AcceptDistributedTracePayload(). _Private_BasicGet will never provide access to the header required for AcceptDistributedTracePayload(). Perhaps the wrapper should be instrumenting the Rabbit method 'BasicGet' and the other method that calls _Private_BasicGet - Autorecovering...something.

The other Rabbit wrapper that instruments incoming messages is HandleBasicDeliverWrapper.cs. The Rabbit method HandleBasicDeliver provides access to the message (& headers) via a parameter, so AcceptDistributedTracePayload() can be successfully called from BeforeWrappedMethod().

The UnboundedIntegrationTest RabbitMqDistributedTracingTests.cs only checks that a distributed trace payload header was added to a Rabbit message (in the  RabbitMqBasicMvcApplication and RabbitMqLegacyBasicMvcApplication via the controller methods RabbitMQ_SendReceive... by calling BasicPublish), and that the same header was received via a call to BasicGet. The tests should be augmented or new tests added to verify that the received header was indeed processed by the Agent (via a call the AcceptDistributedTracePayload()).

When implementing a fix to this bug, verify whether the fix will work for both legacy (3.5.2) and current (5.1.0) versions of RabbitMQ.Client. UnboundedIntegrationTests exist for both versions.

**Notes**
Aside from what this opened issue is trying to achieve, it is worth to point out that the `AcceptDistributedTracePayload()` and `CreateDistributedTracePayload()` apis are deprecated and being replaced by the `AcceptDistributedTraceHeaders()` and `InsertDistributedTraceHeaders()` apis.

**Comment by angelatan2** [comment]
@vuqtran88 please add your comment about the API that was deprecated in the issue.  You shared this in our discussion with Ted.

**Comment by vuqtran88** [comment]
@angelatan2  updated.

**Comment by angelatan2** [comment]
@lspangler584 with the upcoming RabbitMQ feature support for 6.2.x and 3.1,  how does it impact this issue?  Could you take a look and comment?

**Comment by lspangler584** [comment]
Implementing this feature would require investigation of additional instrumentation points within the RabbitMQ.Client library since the current instrumentation point (_Private_BasicGet) does not provide the headers needed (see Description). This work would likely take enough time to not be worth it without a specific customer request.

BasicGet is a polling API, considered inefficient, and its use is discouraged. It is likely used for testing and prototyping scenarios, and unlikely in a production environment. Therefore, the impact of this work is considered minimal.
