### ISSUE TITLE
Spike: Support for read-only filesystems

### ISSUE THREAD

**Issue by chynesNR** [newrelic/newrelic-dotnet-agent#1874]
Currently both the Agent and Profiler require a writeable location for logs. However, there are some environments where this is not possible. The solution here might be a new config option to skip writing logs altogether; the ability to write to stdout instead; or both.

### Acceptance Criteria
A document describing our options and next steps.

### Estimates
M

**Comment by nr-ahemsath** [comment]
Related issue: https://github.com/newrelic/newrelic-dotnet-agent/issues/1373

**Comment by nr-ahemsath** [comment]
Spike is complete, closing this issue.
