### ISSUE TITLE
Spike: .NET 8 RC1 support

### ISSUE THREAD

**Issue by chynesNR** [newrelic/newrelic-dotnet-agent#1937]
Download the [latest .NET 8 release](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) (currently RC1) and test against our [existing experimental branch](https://github.com/newrelic/newrelic-dotnet-agent/tree/experimental/net8-support) to see if any further changes or fixes are required.

There will be one final cleanup task after this, once .NET 8 is officially released.

### Acceptance Criteria
Update the existing .NET 8 research notes, and branch, if necessary.

### Estimates
M

**Comment by jaffinito** [comment]
No issues found, doc updated.
