### ISSUE TITLE
Add ArtifactBuilder run to CI

### ISSUE THREAD

**Issue by chynesNR** [newrelic/newrelic-dotnet-agent#1971]
When making changes to the Agent that require corresponding installer changes (e.g. new instrumentation), we want to catch problems ahead of time, rather than when we're in the middle of a release. Adding a step somewhere in our CI to run the ArtifactBuilder and report any failures should cover most scenarios. This can either be a scheduled/nightly run or part of the PR workflow.

### Estimates
S/M

**Comment by nrcventura** [comment]
Resolved by #1973
