### ISSUE TITLE
Add integration tests for MySqlConnector instrumentation

### ISSUE THREAD

**Issue by nrcventura** [newrelic/newrelic-dotnet-agent#200]
### Is your feature request related to a problem? Please describe.
#85 recently added out of the box instrumentation support for the MySqlConnector library. We should apply our existing MySql integration test suite to this driver. This will help to prevent regressions in the support of this library.

### Feature Description
Apply the existing MySql integration test suite to the MySqlConnector library.

### Additional context
#128 enables developers to run the existing MySql integration tests against a local dockerized version of the test MySql database so that engineers will not need access to the internal New Relic network to run the tests.

### Priority
Really Want

**Comment by nrcventura** [comment]
Here's a description of a simple way to handle this which should hopefully be low effort.

Our integration tests work by having a "test application" that contains code that exercises an instrumented library. Our integration tests use XUnit where each test class has an "application" fixture. This fixture will spin up a separate `Process` to run the test application. This process will then be instrumented by the locally built agent. Once the application is running the fixture can then send commands to the test app so that the desired library code can be executed. When those commands have finished, the "test application" is shutdown, which triggers the .NET agent to try to send all of the data that it collected to New Relic. Then each XUnit `Fact` method will have the ability to look at the agent logs that were generated while the test application was running so that we can validate that the appropriate data was collected, generated, and sent to New Relic (without needing to query a New Relic service/system). For these tests to run, a developer will need a New Relic account and license key, docker (to run a local dockerized version of the MySql database), and Visual Studio.

Here's an example test class snippet that showcases the fixture and .ctor which defines how the test application should run:

```
    [NetFrameworkTest]
    public class MySqlAsyncTests : IClassFixture<RemoteServiceFixtures.MySqlBasicMvcFixture>
    {
        private readonly RemoteServiceFixtures.MySqlBasicMvcFixture _fixture;

        public MySqlAsyncTests(RemoteServiceFixtures.MySqlBasicMvcFixture fixture, ITestOutputHelper output)
        {
            _fixture = fixture;
            _fixture.TestLogger = output;
            _fixture.Actions
            (
                setupConfiguration: () =>
                {
                    var configPath = fixture.DestinationNewRelicConfigFilePath;
                    var configModifier = new NewRelicConfigModifier(configPath);

                    configModifier.ForceTransactionTraces();

                    CommonUtils.ModifyOrCreateXmlAttributeInNewRelicConfig(configPath, new[] { "configuration", "transactionTracer" }, "explainEnabled", "true");
                    CommonUtils.ModifyOrCreateXmlAttributeInNewRelicConfig(configPath, new[] { "configuration", "transactionTracer" }, "explainThreshold", "1");

                    var instrumentationFilePath = $@"{fixture.DestinationNewRelicExtensionsDirectoryPath}\NewRelic.Providers.Wrapper.Sql.Instrumentation.xml";
                    CommonUtils.SetAttributeOnTracerFactoryInNewRelicInstrumentation(
                       instrumentationFilePath,
                        "", "enabled", "true");
                },
                exerciseApplication: () =>
                {
                    _fixture.GetMySqlAsync();
                }
            );
            _fixture.Initialize();
        }
    }
```
The 2 useful methods defined in the .ctor are for the `setupConfiguration` and `exerciseApplication` parameters that are passed to `_fixture.Actions`. `setupConfiguration` is where we can define any agent or application settings that need to be in place before the test application is started. `exerciseApplication` is where we can send commands to the test application. When `exerciseApplication` completes, the test application will be shutdown.

The integration tests for the agent can be found in [IntegrationTests folder](https://github.com/newrelic/newrelic-dotnet-agent/tree/main/tests/Agent/IntegrationTests). We have 2 categories of integration tests: 1. Integration Tests, and 2. Unbounded Integration Tests. The main difference between these categories is that the Unbounded Integration Tests have external dependencies like databases or message brokers. The MySql tests are considered unbounded tests, so they can be found in the [Unbounded Integration Tests solution](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln). The existing MySqlTests are prefixed with the string "MySql" (https://github.com/newrelic/newrelic-dotnet-agent/blob/main/tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySqlTests.cs is one of these tests). The test application for these tests is [BasicMvcApplication](https://github.com/newrelic/newrelic-dotnet-agent/tree/main/tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication), and in this application there is a [MySqlController](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/MySqlController.cs) which allows us to make calls to an endpoint (from the XUnit test fixture) to the test application to execute the desired library code.

I think that we can simply do the following.

- add the nuget reference to the MySqlConnector library to this test application
- add another controller which is basically a copy of the existing MySqlController (yes I know copy-paste is generally bad but this is just a simple way to communicate an idea) but update using statement at the top to be `using MySqlConnector;` instead of `using MySql.Data.MySqlClient;`. Then you'd also need to update the controller name and test methods to disambiguate the routes and provide a more meaningful name (such as MySqlConnector instead of just MySql).
- add another test fixture or update the [MySqlBasicMvcFixture](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/MySqlBasicMvcFixture.cs) so that it can invoke new MySqlConnector endpoints in the test app.
- add additional test classes or update the existing MySql test classes to use the new or existing test fixture to execute the new MySqlConnector endpoints, and then update the assertions so that we can validate that the same data is being generated for the 2 MySql libraries

The instrumentation uses the same code so I would expect the same data to be collected and generated for the 2 MySql libraries that we now support.

I did a quick experiment to see if we could run the 2 MySql libraries in the same test application, and they seemed to work fine side-by-side in the current test app.

**Comment by nrcventura** [comment]
@bgrainger, this is the new feature request that I opened to add some integration tests for the MySqlConnector library. You'll notice that we are not testing timing information in these tests, because we haven't figured out a way to validate timing in a consistent manner.

@nr-ahemsath, can you add some instructions here so that @bgrainger can get a local environment setup to run the MySql integration tests. I don't think that we'll need to add a new MySql database at this point. I think that we can just reuse the existing MySql database.

**Comment by bgrainger** [comment]
Thanks; that all makes sense from an initial read; I'll try it out and see if I run into any blocking issues.

I currently hit https://github.com/newrelic/newrelic-dotnet-agent/issues/204. I can work around it for now by deleting the reference and the related code, but it may be a blocker for other contributors.

**Comment by bgrainger** [comment]
@nrcventura Using your instructions above and the `docker-compose` instructions from the IntegrationTests README I was able to get a simple copy/pasted test working; I opened #220 to show WIP.
