### ISSUE TITLE
Can't build UnboundedIntegrationTests due to IBM.Data.DB2 dependency

### ISSUE THREAD

**Issue by bgrainger** [newrelic/newrelic-dotnet-agent#204]
**Description**

When I build UnboundedApplicationTests.sln, I get the following compiler errors:

```
9>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "IBM.Data.DB2, Version=9.7.4.4, Culture=neutral, PublicKeyToken=7c307b91aa13d208, processorArchitecture=AMD64". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
...
18>C:\...\newrelic-dotnet-agent\tests\Agent\IntegrationTests\UnboundedIntegrationTests\RemoteServiceFixtures\IbmDb2BasicMvcFixture.cs(9,7,9,10): error CS0246: The type or namespace name 'IBM' could not be found (are you missing a using directive or an assembly reference?)
```

It looks like `UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj` references an IBM.Data.DB2 assembly (from the GAC?) that I don't have:

https://github.com/newrelic/newrelic-dotnet-agent/blob/98735738709a0df2b9563f5a8477c053e46e8625/tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj#L46-L48

Would it be possible to replace this with a NuGet package reference instead? https://www.nuget.org/packages/IBM.Data.DB2/

The only version in NuGet is 10.0.5.5 while the project currently references 9.7.4.4, so it's possible they may not be compatible?

**Comment by nr-ahemsath** [comment]
Sorry, that is an oversight in our documentation for installing requirements for building/running the integration tests, which I will correct shortly.

Regarding why we're not using a NuGet package, I have this text from some internal dev environment setup notes:

"We use IBM Data Server Driver from the IBM Data Server Client installer in our unbounded integration tests for DB2. Unfortunately, simply referencing the appropriate dll in our tests is insufficient. A full install of Data Server Client is required on any machine running our unbounded integration test suite."

I believe this is the right place to download the installer for that: https://www.ibm.com/support/pages/ibm-data-server-client-packages-version-111-mod-4-fix-pack-4

If you don't want to do that (which is understandable), would you be willing to try commenting out all of the DB2-related parts of the unbounded test solution?  It's clunky but it should let you make progress.

**Comment by bgrainger** [comment]
Yes, as I noted at https://github.com/newrelic/newrelic-dotnet-agent/issues/200#issuecomment-691314181 (and should have repeated in this issue), I worked around it locally by deleting the reference and the code that used it. I'll probably keep doing that for now.

You can close this out if the solution is to update the documentation with instructions on installing the necessary dependencies.

**Comment by nr-ahemsath** [comment]
Not sure why this didn't get auto-closed when the docs PR merged.  Anyway, the docs have been updated.  Closing.
