### ISSUE TITLE
appsettings.Production.json is not used when using IIS

### ISSUE THREAD

**Issue by rlarno** [newrelic/newrelic-dotnet-agent#2081]
The .Net agent only uses the `appsettings.{environment}.json` if either the `ASPNETCORE_ENVIRONMENT` or the NewRelic custom `EnvironmentName` environment _variable_ is set. This is in contrast to the [default .NET environment behaviour](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments) where if nothing is set in the environment _variables_, the `IHostEnvironment.EnvironmentName` is by default set to `Production`
> [Production](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.environments.production#microsoft-extensions-hosting-environments-production): The default if DOTNET_ENVIRONMENT and ASPNETCORE_ENVIRONMENT have not been set.

As such, the below code should act the same and thus should add another
```
            if (string.IsNullOrEmpty(environment))
            {
                environment = Environments.Production; // Microsoft.Extensions.Hosting
            }
```

https://github.com/newrelic/newrelic-dotnet-agent/blob/f8dcf184dd98c18601b34c7fc186f7d83d1b90fb/src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs#L52C1-L52C1

**Comment by tippmar-nr** [comment]
@rlarno Thanks for your report. We are reviewing the information you've provided and will get this issue on our backlog soon.
