### ISSUE TITLE
Upgrading agent to 10.19.* from 10.18 impacts MassTransit metrics differently

### ISSUE THREAD

**Issue by vmandic** [newrelic/newrelic-dotnet-agent#2087]
**Description**
After upgrading our agent to v10.19 which now has MassTransit improvements, which can be read from release notes, we are seeing new non-web transactions listed in which we are not interested and are impacting our entity summary chart and anomaly detection negatively in terms that we see data we do not care about but it is evaluated in terms of displaying irrelevant duration of a transaction we are interested in and the automatic anomaly detection can not filter this by transaction type in the workflow configuration.

Filtering the transaction type in the summary chart view does not work as we expect it for the same period we used previously. like 3 days ie. the numbers do not change so we can observe an impact (our transaction of interest runs in hours) so we are not able to filter out the new transaction type even when we select our own transaction type.

**Expected Behavior**
The summary filter to work as expected and that the workflow configuration editor allows us to filter out this new "/Message" transaction type so we are not falsely triggered with automatic anomaly detection alerts.

**[Troubleshooting]**
N/A

**Steps to Reproduce**
Build a dotnet 7 console service which issues messages with MassTransit to RabbitMQ and a worker loop that has its own transaction by SetTransactionName(), issue an unexpectedly big amount of messages in one minute and get triggered with an anomaly alert (when set in default workflow to send to Slack). Try filtering in summary view in NRUI your own transaction of interest and observ that chart does not change exec duration times.

**Your Environment**
.NET 7, agent 10.19.2, Linux

**Additional context**
We are considering downgrading in the meantime as this is causing us irrelevant noise to using NR.

We would like the sumamry chart filter to work with the expected date filter eg. last 3 days to show us expected time exec. spans which we are used to be in hours, as now it is showing in minutes, and the service is processing as expected when we switch the NR view to /apm-features/transactions.

The optimal solution for us would be here if we could globally filter out these transactions to be sent from the agent somehow, is that possible? We have observed they always start with "Message/MassTransit" and "Message/RabbitMQ"?

**Comment by chynesNR** [comment]
Hi @vmandic -- thanks for your report. I'm not sure I understand your exact situation, though. Are you saying you weren't seeing _any_ RabbitMQ instrumentation in 10.18 but you are in 10.19? Or you just don't want to see the new MassTransit instrumentation?

You can remove the `NewRelic.Providers.Wrapper.MassTransit.Instrumentation.xml` file to eliminate the MassTransit instrumentation. Similarly, if you don't want any RabbitMQ instrumentation, you can remove the `NewRelic.Providers.Wrapper.RabbitMq.Instrumentation.xml` file. If you want some of the instrumentation but not all, we may need to edit the instrumentation files instead.

**Comment by Laurence-yau** [comment]
> Hi @vmandic -- thanks for your report. I'm not sure I understand your exact situation, though. Are you saying you weren't seeing _any_ RabbitMQ instrumentation in 10.18 but you are in 10.19? Or you just don't want to see the new MassTransit instrumentation?
> 
> You can remove the `NewRelic.Providers.Wrapper.MassTransit.Instrumentation.xml` file to eliminate the MassTransit instrumentation. Similarly, if you don't want any RabbitMQ instrumentation, you can remove the `NewRelic.Providers.Wrapper.RabbitMq.Instrumentation.xml` file. If you want some of the instrumentation but not all, we may need to edit the instrumentation files instead.

I want to be able to turn off the auto instrumentation as well. Where do you find this XML file?

**Comment by vmandic** [comment]
Hello @chynesNR, thank you for reaching out. 

We started receiving new Transactions starting with "/Message*" in their name. This has impacted reading our summary charts. We were not able to filter them out when we filtered by transaction type (eg. I can select "MyService" apart from the new "Message" one, and the chart will still account for the other transactions. We can observe the expected behavior (we are looking for a duration metric) when we dig into the exact (own) Transaction of our interest. We have now downgraded to 10.18 back to block this new instrumentation.

We would like to block the instrumentation, more precisely we would not like the new MassTransit and RabbitMQ transactions to be reported to NR.

We do not have these files you speak of. What we do is sidecar install the APM agents in our Linux containers next to our web and worker .NET7 services.

The biggest issue we have currently with this is that our Slack channel for NR integration is spammed by anomalies that are false positives for us, ie. we are getting a lot of warnings that _increased non-web throughput_ is observed within a service (and we have quite a few) which is natural and expected within our system (as we rely a lot on MassTransit/RabbitMQ messaging infra.). 

Can you please instruct me on how to add them (this conf files, and where, any examples?) and configure or make this block somehow but using the latest v10.19.* of the agent?

**Comment by chynesNR** [comment]
Hi @vmandic -- the XML files are in the `extensions` directory, which is alongside the other .NET Agent libraries (such as `NewRelic.Agent.Core.dll`) in the root of the installation directory. You don't need to add them, they're already there. They're what drive the auto-instrumentation. It sounds like removing the RabbitMQ and MassTransit files I listed above will do what you're looking for.

**Comment by nrcventura** [comment]
Since you are only interested (at this point) in monitoring RabbitMQ infrastructure-wise, I think that you can just disable the .net agent RabbitMQ instrumentation in the same way you are disabling the MassTransit instrumentation. Disabling it in the.net agent will not disable it in the infrastructure agent.

One of the changes regarding RabbitMQ instrumentation with that release is that MassTransit invokes the RabbitMQ API in a way that the .net agent did not previous instrument. The RabbitMQ instrumentation was updated to handle both the previous call paths and the call path used by MassTransit. If you only use RabbitMQ via MassTransit, then disabling the RabbitMQ instrumentation should not lead to you losing any data that was captured by previous agent releases. If you use RabbitMQ separately from MassTransit, then you might have to update the RabbitMQ instrumentation xml file to have the same contents as the previous release (before the RabbitMQ instrumentation changes).

**Comment by vmandic** [comment]
Thanks, figured so, we will monitor how it goes for a while with both disabled. We can close this now.
