### ISSUE TITLE
Support for net:tcp transport for WCF

### ISSUE THREAD

**Issue by pluppplupp** [newrelic/newrelic-dotnet-agent#209]
### Is your feature request related to a problem? Please describe.
We have a web server running ASP.NET framework. It makes WCF calls with a net.tcp transport to .NET services hosted in IIS . 

From what we understand, reading the manual and asking support, if you use net.tcp you need to transfer the transaction information in a custom header or in the payload.

What we’ve done is that we’ve used the NewRelic API and CreateDistributedTracePayload/AcceptDistributedTracePayload and send the tracepayload information on a custom header.

We have a problem with the receiving side. We've implemented the accept method in a WCFMessageInspector (AfterReceiveRequest). But this doesn't work, we've contacted support and a new relic .net engineer has confirmed that the new relic transaction doesn't get created at that point in the lifecycle, and is only available in the actual endpoint code.

### Feature Description
Make the "built-in" distributed tracing work for WCF with net:tcp transport.

### Priority
We really need this to be able to debug outages in production between our web application and core backend systems.

**Comment by jifeingo** [comment]
Hello pluppplupp!

Thank you for taking the time reach out.  The team has evaluated this request and we have incorporated CAT and DT support into our instrumentation for the NetTCP Binding.  After this release, you should no longer need to use the API to Create/Accept Distributed Tracing payloads, it should happen automatically.

This is scheduled to be released as part of our v8.32 release, which should occur sometime within the next week.

Once this is released, please confirm that it is working as you have expected and let us know if you have any questions.

Thanks,
Jason

**Comment by pluppplupp** [comment]
We would be able to test it!!

**Comment by jifeingo** [comment]
Hey pluppplupp!

We just pushed a release of the .NET Agent v8.32 which should have the changes to support NetTCP CAT and DT.
Please let us know if you have any questions.

Thanks!
Jason

**Comment by jifeingo** [comment]
Hey There!
I just wanted to check in and see if you were able to use the NetTCP WCF instrumentation to see if it met your needs.

Thanks,
Jason

**Comment by magnus-hansson** [comment]
@jifeingo We have tested it and it seems to work. One thing that we are unsure of is service map where the down stream WCF service shows up as an external service, where we expected it to show up as a Service. Is this what we can expect?

Thanks
Magnus & Mattias
