### ISSUE TITLE
Auto instrumentation of Confluent.Kafka causing high memory usage for high throughput

### ISSUE THREAD

**Issue by travislindahl-lytx** [newrelic/newrelic-dotnet-agent#2122]
Version 10.19.0 of the NewRelic agent came with auto instrumentation of Confluent.Kafka. In a use case with high Kafka consumer and producer throughput there were very large spikes in memory usage, OOM errors, and containers crashing.

**Description**
After upgrading to New Relic Agent versions >= 10.19.0 we started seeing containers crashing due to very high memory usage.

**Expected Behavior**
New Relic Agent should be able to be updated to new minor versions without causing performance issues and crashing within our applications.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag/) results**

**Steps to Reproduce**
1. Have an application with > Kafka 20k reads/writes per second.
2. Upgrade to New Relic Agent version 10.19.0.
3. Observe high memory usage.

**Your Environment**
Stable
- .NET 7
- New Relic Agent 10.18.0

Has Issue
- .NET 7
- New Relic Agent 10.19.0

**Additional context**
[Release 10.19.0](https://github.com/newrelic/newrelic-dotnet-agent/releases/tag/v10.19.0)
[Pull Request #1990](https://github.com/newrelic/newrelic-dotnet-agent/pull/1990)
[Commit 9f8d22f](https://github.com/newrelic/newrelic-dotnet-agent/commit/9f8d22fc383020bcee20c12bc2b3321c345ba8d9)

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

_Edited to correct versions (1.18.0 -> 10.18.0, 1.19.0 -> 10.19.0)_

**Comment by nrcventura** [comment]
Thank you for making us aware of this problem. Although we strive to minimize our impact on applications, we are unable to test all application types and scenarios. Providing us with information about your setup can help us with identifying gaps in our testing strategy. Are you seeing the memory problem on both the producers and consumers? Has the amount of messages per second that your system is able to process changed between releases? 

To workaround this issue you can disable the kafka instrumentation by removing the `NewRelic.Providers.Wrapper.Kafka.Instrumentation.xml` and `NewRelic.Providers.Wrapper.Kafka.dll` files from the dotnet agent. The location of these files will vary depending on how you installed the agent.

**Comment by nr-vette** [comment]
I talked with Colin, and they rolled back to version 10.18 of the dotNet agent so they are not being affected anymore by the issue with version 10.19.   Please keep us posted on the progress of resolving that issue and when the new release will be available for them to use.  Thank you.

**Comment by tippmar-nr** [comment]
@travislindahl-lytx I wonder if you can provide some additional details about your particular Kafka configuration? 

We have been trying to reproduce the issue you report but without success -- a relatively simple Kafka producer app running in Docker with New Relic instrumentation enabled has been able to produce more than 90k messages/sec to a local Kafka broker instance (also running in Docker) with no observed memory growth.

Any additional details you can provide would be helpful. Thanks!
