### ISSUE TITLE
Add NoticeError overload for sending full exception along with isExpected parameter

### ISSUE THREAD

**Issue by cgranttm** [newrelic/newrelic-dotnet-agent#2222]
### Is your feature request related to a problem? Please describe.

At the moment to mark an error as expected from inside a .net app you cannot send the full exception. This means that we need to concatenate the exception message and stacktrace to get information about where the error is coming from rather than just sending the exception, which means that we lose information. 

Current method:
        public void NoticeError(string message, IDictionary<string, string>? customAttributes, bool isExpected)

Additional method we would like:
        public void NoticeError(Exception exception, IDictionary<string, string>? customAttributes, bool isExpected)

### Describe Alternatives
Concatenating the error message and stack trace ourselves.

### Additional context
The Java API supports this, it would be really nice if the .net one supported it too.

### Priority
Really Want

Thanks!

**Comment by chynesNR** [comment]
Hi @cgranttm -- thanks for your request! The reason we don't have an option for marking an exception object as expected is that it's already covered by our [error collector](https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#error_collector) options for ignoring errors. Can you achieve what you're looking for using that functionality? Our concern with giving the option to override that behavior with the `NoticeError` API call is that it could lead to confusion.
