### ISSUE TITLE
.NET Lambda Agent should support tags as attributes

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#229]
## Feature Description
Tags on **OpenTracing Spans built with the .NET Lambda Agent** are not currently supported.  This Issue requests that tags be supported. 

## Details
- Tags should be added as UserAttributes. 
- The .NET Lambda Agent currently adds Tags from the RootSpan to the TransactionEvent it creates [here](https://github.com/newrelic/newrelic-dotnet-agent/blob/af0ff00225629e572006f78aa9bf672b6105a8c0/src/AwsLambda/AwsLambdaOpenTracer/Events/TransactionEvent.cs#L38). 
- To implement for Spans, something like `BuildUserAttributes()` used in `TransactionEvent.cs` should be added to [LambdaSpan.cs](https://github.com/newrelic/newrelic-dotnet-agent/blob/af0ff00225629e572006f78aa9bf672b6105a8c0/src/AwsLambda/AwsLambdaOpenTracer/LambdaSpan.cs#L140-L147).

### Additional context
Support for Tags on Spans gathered by the .NET Agent (not Lambda) was added after the internal specs were changed to require them. The .NET Lambda Agent has not been updated since that spec change.

**Comment by angelatan2** [comment]
The .NET Agent Lambda Open Tracer is compatible with .NET Core 3.1 only.  The .NET Core 3.1 has reached EOL (Dec 13, 2022).  Due to the EOL nature of .NET Core 3.1 and Open Trace rolled into Open Telemetry, we will not address this story request.
