### ISSUE TITLE
    Create Integration Tests Matrix Job

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#238]
### Feature Description
This new job will be designed to create several new jobs on the fly to run smaller parts of the integration tests across many servers automatically.
This will speed up the run and help prevent tests from stepping on each other.
The split can be done by class or by namespace.  Class gives the most granularity while namespace is simpler.  I would lean toward class.

Command details:
```
xunit.console.exe
    <assemblyFile>
    -nologo
    -class "Name"
    -namespace "Name"
    -html <filename>
```

- Job will using the matrix strategy https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy
- Decide how to setup the matix: class or namespace
- Test results need to be in html so that they can be uploaded to gh-pages.
- Will need to store artifacts, but name cannot just be <name>_<runid>. Actions does not have an easier value here so find a good approach.
- Avoid spaces in file names

**Comment by nr-ahemsath** [comment]
Here's a command to get a list of unique namespaces in our integration tests:

Run from `tests\Agent\IntegrationTests\IntegrationTests`:
`dir -r -filter "*.cs" |Select-String -Pattern "^namespace" |Select-Object -expand Line -unique`
