### ISSUE TITLE
MicrosoftExtensionsLogging: Context data not present in all logs due to conflicting key in dictionary "OriginalFormat"

### ISSUE THREAD

**Issue by tylerohlsen** [newrelic/newrelic-dotnet-agent#2508]
**Description**  
We are using Microsoft.Extensions.Logging in a Linux container with the Dotnet-Agent installed and not getting context data in all logs.  I downloaded agent logs from a container and I see the below error message.  This is coming from the [agent source code here](https://github.com/newrelic/newrelic-dotnet-agent/blob/705f6244a323bf7262a07f58a993b10bfb915df8/src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs#L69-L118) and I see that it's using `accumulatedKvps.Add` to add the scopes to a dictionary, which blows up if multiple scopes have the same key.  In my case, the key is "OriginalFormat".

I've searched our code and I do not see any occurrence of "OriginalFormat" as a log scope/attribute key, so this is especially worse for us because it must be a dependency that's causing it.

```plaintext
2024-05-24 20:48:47,231 NewRelic   WARN: [pid: 1, tid: 32] Unexpected exception while attempting to get context data. Context data is not supported for this logging framework. Exception: System.ArgumentException: An item with the same key has already been added. Key: {OriginalFormat}
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at NewRelic.Providers.Wrapper.MicrosoftExtensionsLogging.MicrosoftLoggingWrapper.<>c.<GetContextData>b__9_0(Object scopeObject, Dictionary`2 accumulatedKvps)
   at Microsoft.Extensions.Logging.LoggerFactoryScopeProvider.ForEachScope[TState](Action`2 callback, TState state)
   at NewRelic.Providers.Wrapper.MicrosoftExtensionsLogging.MicrosoftLoggingWrapper.GetContextData(ILogger logger, IAgent agent)
```

---

**Expected Behavior**
IMO, it'd be better to detect that conflict, log it as a warning, and then continue by either skipping or overwriting the dictionary value.  Especially since this exception causes the `_contextDataNotSupported` flag to be set and then the agent will never attempt to include context data again.  

Suggestion:
```csharp
if (accumulatedKvps.ContainsKey(kvp.Key))
{
    agent.Logger.Log(Level.Warn, $"Context data has multiple scopes with the same key. Skipping occurrence of key: {kvp.Key}");
    continue;
}
accumulatedKvps.Add(kvp.Key, kvp.Value);
```

---

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag/) results**
See description

---

**Steps to Reproduce**
I don't have exact steps to reproduce, because this is caused by code in a dependency, but I can hypothesize.  

```csharp
using var logScope1 = logger.BeginScope("{MyScopeKey}", "myScopeValue1");
using var logScope2 = logger.BeginScope("{MyScopeKey}", "myScopeValue2");
logger.LogInformation("Anything here as it doesn't matter what's in the log");
```

---

**Your Environment**
.NET 8 running in Linux container with Microsoft.Extensions.Logging for our logging framework.  
The New Relic .NET Agent v10.25.0.0

---

**Additional context**
None

**Comment by tylerohlsen** [comment]
So we found the cause and a workaround for our occurrence of this issue.  When we use the `BeginScope` overload that includes a format message and params args, then the Microsoft logger implicitly adds "OriginalFormat" as another scope key.  So we run into the issue when we call that overload multiple times (even though our code creates separate scope keys).  

```csharp
using var logScope1 = logger.BeginScope("{MyScopeKey1}", "myScopeValue1");
using var logScope2 = logger.BeginScope("{MyScopeKey2}", "myScopeValue2");
logger.LogInformation("Anything here as it doesn't matter what's in the log");  // This blows up the agent
```

If we instead use an overload that passes in a dictionary or a single KeyValuePair, then that implicit "OriginalFormat" isn't added and it successfully continues.

```csharp
using var logScope1 = logger.BeginScope(new KeyValuePair<string, object>("{MyScopeKey1}", "myScopeValue1"));
using var logScope2 = logger.BeginScope(new KeyValuePair<string, object>("{MyScopeKey2}", "myScopeValue2"));
logger.LogInformation("Anything here as it doesn't matter what's in the log");  // This is ok
```

But I would not call this issue as fixed with this workaround.  I'm still walking on egg shells because I have to monitor our codebase and make sure no use of the other overload is used.  And I have to just hope that none of our dependencies uses it.

**Comment by tippmar-nr** [comment]
Thanks for the detailed repro and workaround, @tylerohlsen - your report was quite helpful. 

We've looked at the issue as well and have concluded that the best way to handle it is to take the value from the last context when there are multiple nested contexts - which correlates with what MEL is doing when you have nested scopes.

For example, if you have two scopes with the same key but different values, log messages emitted from the innermost scope will show the value from that scope and log messages emitted from within the outer scope will use the value from the outer scope. 

```
            using (var _ = logger.BeginScope("{ScopeKey1}", "scopeValue1"))
            {
                logger.LogInformation("Outer Scope");

                using (var __ = logger.BeginScope("{ScopeKey1}", "scopeValue2"))
                {
                    logger.LogInformation("Inner Scope");
                }
            }
```

(BTW - the offending key you referenced is actually [coming from MEL](https://github.com/dotnet/runtime/blob/f36a47711032e3564e67bd2fc575b2e923747ded/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LogValuesFormatter.cs#L239), but the same problem would have appeared if your code had multiple nested scopes with the same key... 

We're working on fixing this issue and expect to include it with our next release.
