### ISSUE TITLE
XML Instrumentation casing should not affect Unmanaged Agent logging level

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#262]
**Description**
XML tracer factory method signatures are case sensitive if logging level is “info” or “debug”, but are case insensitive if logging level is “finest” or “all”.

If there is a mismatch in casing between the method signature from the CLR and the signature defined in the instrumentation XML, the instrumentation WILL be applied if the unmanaged agent's logging level is set to "finest" or "all".  The instrumentation WILL NOT be applied if the unmanaged agent's logging level is set to "info" or "debug".

If there are no casing mistakes in the instrumentation files, then it will be correctly applied in all situations.

Workaround is to correct casing mistakes in your instrumentation files.

Tested in 6.24 and 8.18

**Expected Behavior**
Case sensitivity of custom instrumentation should be consistent regardless of profiler logging level.

**Note**: as of now we are unaware of any documented requirement regarding case sensitivity of custom instrumentation; however, C# is case sensitive (`aFoo()` and `AFoo()` are distinct method names within a class) so we are leaning towards having custom instrumentation be case sensitive.

**Steps to Reproduce**
Repro is very simple. With the attached code and instrumentation xml (Notice the casing mistakes in the XML file), set the unmanaged agent's logging level to "info" or "debug".  When the application is run the managed agent will NOT be invoked (no managed agent log is generated).  
[LogLevelRepro.zip](https://github.com/newrelic/newrelic-dotnet-agent/files/5308441/LogLevelRepro.zip)
[LogLevelRepro-CI.xml.txt](https://github.com/newrelic/newrelic-dotnet-agent/files/5308448/LogLevelRepro-CI.xml.txt)
  * Note: LogLevelRepro-CI.xml.txt filename was changed to allow uploading to this Issue. When executing the repro, the '.txt' suffix must be removed.

Change the logging level to "finest" or "all" and the managed agent will be invoked (managed agent log is generated).

**Your Environment**
Repro app targets .NET Framework 4.7.2, but undetermined if this behavior exists in other environments.

** MISC **
[Internal process] [Zendesk](https://newrelic.zendesk.com/agent/tickets/366332)

**Comment by nr-ahemsath** [comment]
I am able to reproduce this issue in version 8.18 as described in the original summary.  With version 8.38, I am no longer able to reproduce the issue.  This issue has been resolved sometime between September 2019 (the date of the original customer ticket) and February 2021.  Closing.
