### ISSUE TITLE
GCSampler - CountData calculated as negative causes exception

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#264]
**Description**

We are unsure of the reason, but the GC Sampler is trying to create a count metric that is a negative value.  As a result, the GC Sampler shuts down (because too many exceptions have been thrown).

Here is where the exception is being thrown from: https://github.com/newrelic/newrelic-dotnet-agent/blob/707a2269b63bd76337597cb439829fed273f1f21/src/Agent/NewRelic/Agent/Core/WireModels/MetricDataWireModel.cs#L117

**Expected Behavior**

Since many of the count values are delta values from the prior value, intercept a negative value and record it as 0 in the event.
When doing so, add a log message (finest) indicating the Metric and requested value that was switched to 0.

**Steps to Reproduce**

Unknown at this point.

**Comment by JoshuaColeman** [comment]
Hey @angelatan2! I have a potential solution for this in [https://github.com/newrelic/newrelic-dotnet-agent/pull/525](url)
