### ISSUE TITLE
Stop relying on dependency injection containers

### ISSUE THREAD

**Issue by nrcventura** [newrelic/newrelic-dotnet-agent#27]
## Summary

The agent uses dependency injection containers to manage the dependencies for all of our objects, as well as starting up our agent. This has lead to multiple bugs during agent startup, it makes it really hard to reason about which things are created when, it makes it hard to know which long running services are started at which point in time, and it's also lead us to create extra code to handle dependency injection (see https://github.com/newrelic/newrelic-dotnet-agent/pull/26 as an example).

## Desired Behaviour

The agent doesn't use a dependency injection container, and the agent startup is more declarative so that we can see exactly what happens and in what order it happens.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

Internal NR only: [slack convo with some more context](https://newrelic.slack.com/archives/G018XDPTX52/p1606934226045200)

**Comment by angelatan2** [comment]
While we probably should have used a different design instead of depending on DI, the value of changing it now is limited compared to the effort.
