### ISSUE TITLE
Agent version 10.29.0 not reporting correctly

### ISSUE THREAD

**Issue by peterkiss1** [newrelic/newrelic-dotnet-agent#2712]
**Description**
Agent version 10.29.0 not reporting correctly:

- some sign of life is visible
- no data about transactions
- or external calls
- and probably a lot more missing

![image](https://github.com/user-attachments/assets/7f3c88a4-c557-40fe-adda-33bfe23b7dbf)

![image](https://github.com/user-attachments/assets/4405f5e4-434c-40bf-a636-57267a18fb0a)

![image](https://github.com/user-attachments/assets/12a7cd61-c07a-41e5-a69a-fb3c7c2032fa)

**Expected Behavior**
These should be there as before, version 10.26.0 works correctly.

**Steps to Reproduce**
Basic .NET app running in container.

**Your Environment**
Runtime image: mcr.microsoft.com/dotnet/aspnet:8.0-noble-chiseled-extra-amd64
The agent is installed from tarball (the original app was based on a Debian image where the agent was installed via package manager).

**Comment by tippmar-nr** [comment]
Hi @peterkiss1 - thanks for your report. It looks like your app might be making calls to Amazon SQS - we recently introduced instrumentation for that library, so it's possible that the behavior you're seeing is related to that instrumentation. 

It would be helpful if you could try v10.29.0 again, but add configuration to disable `AWSSDK.Core` as [documented here](https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#instrumentation-rules) and let us know whether that seems to resolve the unexpected behavior. 

Whether that fixes the issue or not, the best way to get assistance is through our [official support channels](https://support.newrelic.com) - with a support case, you can share more details about your environment, configuration, log files, etc. that aren't appropriate for sharing in public.

**Comment by peterkiss1** [comment]
@tippmar-nr does this mean that the "new behavior" is accepted? I mean it clearly breaks the whole reporting and looks like none of these changes were tested in the real world. I'm somewhat even amazed that instrumentation for a basic AWS service was in such high demand that it had to delivered - if SNS/SQS/S3 and maybe some other services goes down, having issues then the whole region/AZ is ~down, but when they are working then everything is butter smooth.

I understand that some sort of distributed tracing information is being pushed through the messages but i'm not sure if that is actually working fine, for example when:
1. a .NET hosted service runs in the background
2. receives an SQS message which already have tracing information (not the new New Relic one!)
3. which is being used to start a new Activity and continue in a new span within the same trace
4. and during processing a HTTP call is made (nothing special, pure HttpClient in use)
5. the tracing - i guess - overwrites the trace headers in the web request with something other than what it should be extracted from the started Activity previously

Also what i found annoying is that in same cases the installation descriptions aren't in sync with the troubleshooting ones like what sort of permissions do i have to give to specific directories? Or why by default the agent is logging into a directory which is read-only in any linux/unix file system (log files under /usr, also maybe some config files can be changed in some way located here)?

**Comment by tippmar-nr** [comment]
@peterkiss1 Thanks for the follow-up. 

In order to narrow down the scope of the problem, it would be helpful if you could try using v10.29.0 and disabling instrumentation for the `AWS.SDK` assembly as I previously noted. If your application behavior returns to normal, that's definitely an indicator that something may not be quite right with our instrumentation and we would like to look into it further. A simple app that reproduces the behavior would also be greatly helpful. 

As previously mentioned, the best way for us to support you with this issue is through our [official support channels](https://support.newrelic.com/). If you're not able to open a support ticket, the next best route for assistance would be the [New Relic Explorers Hub](https://forum.newrelic.com/s/), which is monitored by our technical support staff.
