### ISSUE TITLE
NewRelic.Agent.Api 8.31.0 Nuget package throws errors on install

### ISSUE THREAD

**Issue by warhammer54** [newrelic/newrelic-dotnet-agent#275]
** Summary **
NewRelic.Agent.Api 8.31.0 Nuget package throws errors on install

**Description**
Using the Visual Studion Nuget Console to Install NewRelic.Agent.Api 8.31.0, errors (three errors) are thrown during install. It appears that the dll in itself does get installed. The error messages look to be more geared at the config file. (see below) It looks like the powershell script is looking for "Web.Config". But that would only work for a web project. Many VS project templates use "app.config". The same thing happened when using the UI to install the packge but the errors nare not displayed. just that a problem occurred.

Manual Install:
---------------

PM> Update-Package NewRelic.Agent.Api -version 8.31.0

Attempting to gather dependency information for multiple packages with respect to project 'SA.Invoice.CompletedBatchExport', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 2.68 sec
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Retrieving package 'NewRelic.Agent.Api 8.31.0' from 'ProGet'.
  CACHE http://packages.serviceautopilot.com/nuget/Default/Packages(Id='NewRelic.Agent.Api',Version='8.31.0')
  GET http://packages.serviceautopilot.com/nuget/Default/package/NewRelic.Agent.Api/8.31.0
Executing script file 'C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.20.262\tools\uninstall.ps1'
Value does not fall within the expected range.
At C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.20.262\tools\uninstall.ps1:3 char:1
+ $config = $project.ProjectItems.Item("Web.Config")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
 
You cannot call a method on a null-valued expression.
At C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.20.262\tools\uninstall.ps1:4 char:1
+ $configPath = $config.Properties.Item("LocalPath").Value
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Get-Content : Cannot bind argument to parameter 'Path' because it is null.
At C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.20.262\tools\uninstall.ps1:5 char:23
+ [xml] $configXml = gc $configPath
+                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Content], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentCommand
 
  OK http://packages.serviceautopilot.com/nuget/Default/package/NewRelic.Agent.Api/8.31.0 206ms
Installing NewRelic.Agent.Api 8.31.0.
Removed package 'NewRelic.Agent.Api 8.20.262' from 'packages.config'
Successfully uninstalled 'NewRelic.Agent.Api 8.20.262' from SA.Invoice.CompletedBatchExport
Adding package 'NewRelic.Agent.Api.8.31.0' to folder 'C:\SA_Code\sa.invoice.batchqboexport\src\packages'
Added package 'NewRelic.Agent.Api.8.31.0' to folder 'C:\SA_Code\sa.invoice.batchqboexport\src\packages'
Added package 'NewRelic.Agent.Api.8.31.0' to 'packages.config'
Executing script file 'C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.31.0\tools\install.ps1'
***Updating the projects .config file with the NewRelic.AppName***
Value does not fall within the expected range.
At C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.31.0\tools\NewRelicHelper.psm1:72 char:2
+     $config = $project.ProjectItems.Item("Web.Config")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
 
You cannot call a method on a null-valued expression.
At C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.31.0\tools\NewRelicHelper.psm1:73 char:2
+     $configPath = $config.Properties.Item("LocalPath").Value
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Get-Content : Cannot bind argument to parameter 'Path' because it is null.
At C:\SA_Code\sa.invoice.batchqboexport\src\packages\NewRelic.Agent.Api.8.31.0\tools\NewRelicHelper.psm1:74 char:24
+     [xml] $configXml = gc $configPath
+                           ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Content], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentCommand
 
***Package install is complete***
Successfully installed 'NewRelic.Agent.Api 8.31.0' to SA.Invoice.CompletedBatchExport
Removing package 'NewRelic.Agent.Api 8.20.262' from folder 'C:\SA_Code\sa.invoice.batchqboexport\src\packages'
Removed package 'NewRelic.Agent.Api 8.20.262' from folder 'C:\SA_Code\sa.invoice.batchqboexport\src\packages'
Executing nuget actions took 5.13 sec
Time Elapsed: 00:00:08.4786821

**Expected Behavior**
My concern is that config entry, which is expected to happen, is not happening.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
See Above

**Steps to Reproduce**
See Above

**Your Environment**
Visual Studio 2017 Professional
Version 15.9.14

**Additional context**
None

**Comment by alanwest** [comment]
Thanks for bringing this to our attention, @warhammer54.

It appears this issue affects projects that use the old `Packages.config` package management format. See this documentation for more information on the two NuGet package management formats https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference.

The `Packages.config` format by convention will run an `install.ps1` script (if present) when installing a NuGet package.

The newer `PackageReference` format does not support running an `install.ps1` script upon installing a package. Given that the `PackageReference` format is becoming the new norm, we will likely not seek to fix the `install.ps1` script. I'm considering removing the script altogether.

To configure your license key in your `app.config` file, all you need to do is add the following:

```xml
...
<appSettings>
    <add key="NewRelic.LicenseKey" value="your_license_key" />
</appSettings>
...
```

**Comment by angelatan2** [comment]
Hello @warhammer54,
Have you tried the suggestion from Oct 8th? 

We do not plan on fixing this issue at this point. The issue will be closed.  We will monitor if others are asking for the same change and reopen as needed.  Thank you again for bringing this to our attention.
