### ISSUE TITLE
OrderingGatewaySvc service fails to respond

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#279]
**Description**
The issue with the newer front-end is that their OrderingGatewaySvc service fails to respond when the agent is present, regardless of the environment or data center. After our last call, we were focusing on examining the memory dumps we collected on the call for this service. These dumps were taken during an iisreset, because the reset was taking a very long time to complete when the agent is present compared to when the agent is disabled. The thought was that there might be something hanging during the reset which could provide a clue as to what’s going on that’s causing the service to fail to respond.

The service is called OrderingGatewaySvc and when the agent is introduced, the endpoint fails to load in a browser. We get a profiler log for the service, and see that the only method that gets instrumented is:

```
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll
```

**Expected Behavior**
[NOTE]: # ( Tell us what you expected to happen. )

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
We never get an agent log for this service, even though a method is being instrumented and the app pool user IDs are identical to other services that work fine and generate agent logs. We also see the profiler and some managed DLLs appear in Process Explorer. Here are the notes that apply to this service which we should focus on going forward:

Disabling New Relic completely allowed the application to start.

Even when we remove the HttpClient instrumentation and confirm that no instrumented methods are getting hit, the application will still fail to load.

We noticed that all of the managed dlls in the process are loaded twice. (We later confirmed this is the case for working services as well).

The application only has 1 app pool and no virtual applications

Even when our instrumentation is removed, our managed agent dll is loaded twice.

Reviewed Procmon logs but couldn’t find any reason (permissions, etc.) that would prevent an agent log from being written.

We did not find anything related to the event logs while reproducing the issue on the call.

**Steps to Reproduce**

**Your Environment**

**Additional context**

** MISC **
New Relic process: 
[Internal only] - [GTSE](https://newrelic.atlassian.net/browse/GTSE-2344)
[Internal only] - [Zendesk](https://newrelic.zendesk.com/agent/tickets/404821)

**Comment by tehbio** [comment]
This issue appears to be very specific to their environment/configuration, and as mentioned in the GTSE last year we will need assistance in producing a reproduction of this issue for us to be able to look into this further.
