### ISSUE TITLE
TransferRequestHandler transactions cause confusion

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#281]
**Description**
If an extensionless URL is requested like "http://mysite.com/" and the application is in Integrated mode, IIS uses the TransferRequestHandler to handle the request:

https://blogs.msdn.microsoft.com/tmarq/2010/05/26/how-extensionless-urls-are-handled-by-asp-net-v4/

This results in a transaction called "WebTransaction/ASP/TransferRequestHandler" which often is very quick, has very little details, and is frequently a high throughput transaction.

This causes confusion for customers and can't be easily ignored due to it being generated almost entirely within IIS. This leaves it affecting their Apdex without being under the customers' control.

**Expected Behavior**
Ideally these IIS pipeline named transactions would not be recorded by default.

**Comment by jaffinito** [comment]
Was not able to reproduce this problem with the latest agent. Previous repro app no longer demonstrate the naming issue.  Attempted to build new app that utilized the TransferRequestHandler and while successful, the naming always came out correct based on what route it eventually end up in. It never even attempted to use the TransferRequestHandler name.

We need a new repro of this problem that occurs using the current agent.

**Comment by angelatan2** [comment]
@jaffinito Would it be possible to share what applications were used to test and also what versions worked?

**Comment by angelatan2** [comment]
Cannot reproduce this issue.
