### ISSUE TITLE
AwsSdkPipelineWrapper: Asynchronous task blocked on a synchronous call

### ISSUE THREAD

**Issue by gjunge** [newrelic/newrelic-dotnet-agent#2855]
**Description**
After upgrading to 10.31.0 from 10.26.0 we have seen on a number of occasions that the CPU spiked to almost 100% and stayed there. After windbg-ing we have seen that we have a race condition in the new `AwsSdkPipelineWrapper` when inserting a new value into the `HashSet<string> _unsupportedRequestTypes`. 
In this one instance we had around 8 threads locked on this call. 

![image](https://github.com/user-attachments/assets/525f3a4a-e07d-4cc5-9d91-97193daea8c8)

![image](https://github.com/user-attachments/assets/5ed55d19-8b45-4a16-bb0f-f501dce4f2ed)

**Steps to Reproduce**
This happened when we have a `[Trace]` attribute on a asynchronous method that lists objects from S3.

```
        [Trace]
        public async Task<IEnumerable<S3Object>> GetFilesInternalAsync(string path)
        {
             var results = new List<S3Object>();
            ListObjectsV2Response s3Response = null;
            do
            {
                s3Response = await _s3client.ListObjectsV2Async(new ListObjectsV2Request() {
                    Prefix = path,
                    BucketName = this.Bucket,
                    ContinuationToken = s3Response?.NextContinuationToken
                }).ConfigureAwait(false);

                results.AddRange(s3Response.S3Objects.Where(f => f.Key != path));

            } while (s3Response.IsTruncated);

            return results;
        }
```

**Your Environment**
.NET 4.8.2 , Agent 10.31.0

**Comment by tippmar-nr** [comment]
@gjunge Thanks for reporting this issue and for submitting a PR to fix it. 

We are reviewing your PR and will likely accept the change via a PR directly on this repo - we need to be able to run our full set of CI workflows, which unfortunately can't run on a fork.

**Comment by gjunge** [comment]
Thanks for the quick response!

**Comment by wr-cdargis** [comment]
Just came on here to report this. So glad it's already addressed.

When will this fix be released? @gjunge @tippmar-nr ?
