### ISSUE TITLE
Support new Couchbase client.

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#290]
### Feature Description
At the current state, the Agent instruments methods in the `Couchbase.CouchbaseBucket` class from the `Couchbase.NetClient` assembly. Starting from the version 2.5.0 and forward, the implementation of `Couchbase.CouchbaseBucket` has changed, which causes the Agent to miss instrumenting calls. Couchbase integration tests fail. Below are issues I found with different versions of Couchbase:

- Starting from ver 2.4.5, the call `Task<IQueryResult<T>> QueryAsync<T>(string query)` causes duplicated instrumented. 

- Starting from the version 2.5.2, the Agent at least misses to instrument this `IDocumentResult<T> Replace<T>(IDocument<T> document)` call due to logic change. There are many more that the agent misses.

- According to the up-to-date  implementation of the [`Couchbase.CouchbaseBucket`]( https://github.com/couchbase/couchbase-net-client/blob/master/src/Couchbase/CouchbaseBucket.cs), there are no longer any method calls that the agent expects to instrument from this class.

A list of methods that the Agent is currently instrumenting for the `Couchbase.CouchbaseBucket` class is in this file.
https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Couchbase/Instrumentation.xml

**Comment by angelatan2** [comment]
@vuqtran88 Thank you for submitting this issue. Could you add more detail around what is not instrumented? This is so community who sees this issue has more specific details.  I would suggest taking explaining what you know already here.

**Comment by vuqtran88** [comment]
> @vuqtran88 Thank you for submitting this issue. Could you add more details around what is not instrumented? This is so a contributor who sees this issue has more specific details. I would suggest explaining what you already know here.

Updated.
