### ISSUE TITLE
Unable to install Release 10.34.1 due to not signed error

### ISSUE THREAD

**Issue by greg737** [newrelic/newrelic-dotnet-agent#2916]
**Description**
I am getting this error when installing the latest version (10.34.1) in Github Actions but have no issue installing the previous version (10.34.0)
![image](https://github.com/user-attachments/assets/66fd6706-8a91-4a4e-80e2-5b75e91e0b98)

**Steps to Reproduce**
Same as the example in the docs:

RUN apt-get update && apt-get install -y wget ca-certificates gnupg \
&& echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
&& wget https://download.newrelic.com/548C16BF.gpg \
&& apt-key add 548C16BF.gpg \
&& apt-get update \
&& apt-get install -y newrelic-dotnet-agent \
&& rm -rf /var/lib/apt/lists/*

**Comment by nr-ahemsath** [comment]
@greg737 Thanks for bringing this to our attention.  This will sound dumb, but could you try the install procedure again?  We *just* released 10.34.1 this afternoon, and it sometimes takes a while for various caches for our package repos to sync up and be happy.

I just tested running the process in the latest `mcr.microsoft.com/dotnet/sdk:9.0` Docker image and it worked as expected.  What kind of host were you running the install on?

**Comment by greg737** [comment]
> @greg737 Thanks for bringing this to our attention. This will sound dumb, but could you try the install procedure again? We _just_ released 10.34.1 this afternoon, and it sometimes takes a while for various caches for our package repos to sync up and be happy.
> 
> I just tested running the process in the latest `mcr.microsoft.com/dotnet/sdk:9.0` Docker image and it worked as expected. What kind of host were you running the install on?

Sure I'll try it again.
We were running it on the `mcr.microsoft.com/dotnet/aspnet:8.0` image

**Comment by nr-ahemsath** [comment]
It also worked as expected for me in `mcr.microsoft.com/dotnet/aspnet:8.0`, FWIW.

**Comment by greg737** [comment]
Yay, its working now.
