### ISSUE TITLE
Instrumentation - Do Not ReJIT methods where instrumentation matches on change

### ISSUE THREAD

**Issue by jifeingo** [newrelic/newrelic-dotnet-agent#292]
### Feature Description
When instrumentation changes, the profiler: 

1. Identifies instrumentation that no longer applies (was instrumented and now isn't) and  removes instruentation that was injected and ReJITs. the method
1. ReJITs all instrumentation points in the new instrumentation list.

This feature request proposes:

1. Identifies instrumentation that no longer applies (was instrumented and now isn't) and  removes instruentation that was injected and ReJITs. the method
1. Compare the new instrumentation points to matching instrumentation in the old set.  Identify places where instrumentation has changed (the xml has changed) and instrument only them.

The goal here would be to minimize the amount of unnecessary reJIT that occurs.  Since reJIT affects all apps running on the server, this can be quite costly in web servers that host many applications.

[Here's the relevant code](https://github.com/newrelic/newrelic-dotnet-agent/blob/88c65f452a3e21ad7aedfc103ad6697e87a66736/src/Agent/NewRelic/Profiler/Profiler/ICorProfilerCallbackBase.h#L484-L518)

### Describe Alternatives
* Continue as is.
* Allow the `newrelic.config` file to specify an "additional instrumentation" folder.  This could be used to have app-specific instrumentation.  Often the instrumentation change is related to a single app on a server that hosts many apps.   This could be a mechanism for a customer to deploy instrumentation as part of their app.

### Additional context
Customer had an instrumentation file with about 15K instrumentation points on an IIS server hosting 30 applications.  They dropped a small instrumentation file, with 3 instrumentation points, targeted for one app.   All 30 applications started rejitting against 15K instrumentation points.

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to Have

**Comment by angelatan2** [comment]
This is a possible change however the value of this change versus the effort is limited.
