### ISSUE TITLE
Support Content-Security-Policy

### ISSUE THREAD

**Issue by bgrainger** [newrelic/newrelic-dotnet-agent#319]
If a site is using `Content-Security-Policy` without `'unsafe-inline'` then inline scripts (such as the Browser Monitoring injected by the NR APM Agent) will not execute.

If the site is already using `Content-Security-Policy 'nonce-BASE64'`, then it would be desirable for https://github.com/newrelic/newrelic-dotnet-agent/blob/3e4d5158f4abdc045fae4ccffd686b7d05d4c10d/src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringScriptMaker.cs#L80 to be able to inject a per-request nonce.

Alternatively, the site could add `script-src 'sha256-...'` to its CSP header if the SHA-256 hash of the script were available from the agent.

As a workaround, the [copy/paste approach](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/install-browser-monitoring-agent#copy-paste-app) can be used (with a nonce dynamically injected into the script by the backend code).

### Priority

Really Want

**Comment by nr-ahemsath** [comment]
Hi @bgrainger, thanks for bringing this one to our attention.  Being fully transparent, this is an area that you appear to understand better than I do.  I'm going to bring this to the attention of our Browser team.  In the meantime, would you be willing to submit a PR to implement the functionality you are looking for?

**Comment by bgrainger** [comment]
The only solutions I can think of will need some interaction between the site and the agent; either a pre-request nonce being transferred from site to agent (some kind of dependency injection?) or a script SHA-256 being pulled from the agent by the site (a static property? but maybe that's per transaction, too?).

Or maybe an overload of [`GetBrowserTimingHeader`](https://docs.newrelic.com/docs/agents/net-agent/net-agent-api/getbrowsertimingheader-net-agent-api) that takes a nonce as a string? That may actually be the simplest approach; I could try to see if that's viable.
