### ISSUE TITLE
.NET 5 GA validation

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#331]
Validate the agent ability to instrument in .NET 5 runtime GA. Areas to cover:
- Existing instrumentation.
- Pay close attention to AspNetCore and HttpClient instrumentation.
- Enable HttpClientInstrumentationNet5.cs  test.

Update the following docs.
 - [x] [Release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes)

- [x] [.NET Core Compatibility matrix](https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core)

~~- [ ] [.NET Framework Compatibility Matrix](https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework)~~ The .Net 5.0 is only relevant for .Net Core space so no need to update this doc.

- [x] Change log

**Comment by angelatan2** [comment]
@vuqtran88 please add updating the following documentation to your list:

- [ ] [Release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes)

- [ ] [.NET Core Compatibility matrix](https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core)

- [ ] [.NET Framework Compatibility Matrix](https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework)

- [ ] Change log

Thank you.
