### ISSUE TITLE
Decommission Jenkins build infrastructure - Phase 1

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#362]
### Feature Description
**IMPORTANT** This story should only be picked up _after_ a second release has been successfully completed since the migration.  First release was done for 8.35.0 on 11/10/2020.

For phase 1 we will be _shutting down_ all of the following servers.  We will not be deleting anything until phase 2 and even then we will not be deleting everything.  Some of these may already be shutdown.

Servers to stop
dn-bld-20200106
dn-bld-agent-01
dn-bld-agent-02
dn-bld-agent-03
dn-bld-agent-04
dn-bld-agent-05
dn-bld-agent-10
dn-bld-agent-13
dn-bld-agent-14
dn-bld-agent-20
dn-bld-agent-xx
dn-bld-agetn-13
dn-bld-exprmt
dn-bld-job-01
dn-bld-job-02
dn-docker-01
dn-docker-02
dn-instTest-351
dn-instTest-400
dn-instTest-452
dn-integ
dn-test-az-01
dn-test-az-02
dn-test-az-03
dn-wrk-01

This is the jenkins server itself, stop this last!!!
dn-jenkins-master

Not stopping since it still has some use:
dn-database-01

### Priority
Blocker

**Comment by nr-ahemsath** [comment]
I think we should also wait to do this until we've ported the workflows to the `net35/main` branch.

**Comment by jaffinito** [comment]
All servers mentioned have been stopped and deallocated (no longer being charged for compute only storage)
