### ISSUE TITLE
Manually verify RabbitMQ versions

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#387]
### Feature Description
After adding UnboundedIntegrationTests for RabbitMQ on .NET Core application, manually change the application's RabbitMQ version and verify tests still pass.

Tests exist for RabbitMQ versions 3.5.2, 5.1.0, and after Issue #381 6.2.1. Other versions of RabbitMQ should be tested (manually is sufficient), such as 5.2.0 and 6.1.0.

### Priority
Nice to Have

**Comment by lspangler584** [comment]
The following combinations of .NET and RabbitMQ.Client were tested successfully on the branch in this [PR](https://github.com/newrelic/newrelic-dotnet-agent/issues/387):

NET461 3.5.2
NET461 5.2.0
NET461 6.2.1
NET471 5.1.0

NET471 6.2.1

NETCOREAPP3.1 6.2.1
NETCOREAPP3.1 5.1.0
NETCOREAPP3.1 5.2.0

**Comment by nr-ahemsath** [comment]
Looks good to me. 💯
