### ISSUE TITLE
Update docs site

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#390]
### Feature Description
Add a section for Messaging support to the [.NET Core compatibility & requirements](https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core) docs page and include RabbitMQ.

### Additional context
See the docs page for [.NET Framework compatibility & requirements](https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework) for format and language.

### Priority
Must Have

**Comment by angelatan2** [comment]
@lspangler584 when we do a release for this milestone, could you add the following statement to our release notes?

Support statement:
New Relic recommends that you upgrade the agent regularly and at a minimum every 3 months. As of this release, the oldest supported version is XXX.

@elucus could you provide the XXX of the last supported version, please?
