### ISSUE TITLE
Feature Request: Expected/Ignored Messages should include wildcard/regex matching pattern

### ISSUE THREAD

**Issue by mkweick** [newrelic/newrelic-dotnet-agent#395]
We are trying to not have these example errors count in the alert error percentage. So we see these errors a lot but are expected errors...

Error Class: System.Web.HttpException
Error Class Message: The file /secure/docs/handler.aspx does not exist.
Error Class Message: The file /secure/ring/edit/classification.aspx does not exist.
Error Class Message: The file /secure/type/upper/test.aspx does not exist.

It's the same error message over and over but with a different unique path/file.
We would like to exclude all these messages in this Error Class with a wildcard like so:

```
<errorCollector enabled="true" captureEvents="true">
    <expectedMessages>
        <errorClass name="System.Web.HttpException">
            <message>The file * does not exist.</message>
        </errorClass>
    </expectedClasses>
</errorCollector>
```

We don't want to exclude the entire error class "System.Web.HttpException" because it provides other valuable error reporting messages that are needed for troubleshooting.

Hoping this will be accepted as feature request to be included in future .NET Agent versions

**Comment by vuqtran88** [comment]
@mkweick Thanks for submitting this feature request. We will discuss with the team to prioritize this.  
@elucus ^

**Comment by lspangler584** [comment]
@mkweick I've taken a look at your request and we have discussed it for prioritization. At this time we are unlikely to undertake this Feature Request. I do, however, have a suggestion that might be 'good enough'. The Agent is able to mark an exception with a message as expected using a substring. For instance, if you were to use the following in your newrelic.config, this might meet your need:

><errorCollector enabled="true" captureEvents="true">
    <expectedMessages>
        <errorClass name="System.Web.HttpException">
            <message>does not exist.</message>
        </errorClass>
    </expectedClasses>
</errorCollector>

**Comment by mkweick** [comment]
I tried this and unfortunately it did not work, the errors were not counted as expected and were still included in the error rate. Question though, what is the minimum .NET agent version that supports <expectedMessages> with the substring <message>? I can check and make sure our current agent version is supported, let me know thanks

**Comment by lspangler584** [comment]
@mkweick Great question. We introduced it in 8.31, then fixed a bug in the feature in 8.34.

**Comment by mkweick** [comment]
Ok I was testing on 8.22, let me upgrade and retest, thank you

**Comment by mkweick** [comment]
Yes this works as expected on 8.37, I see this as expected errors now, great thank you!
