### ISSUE TITLE
.Net Agent supports trimmed self-contained application

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#397]
### Is your feature request related to a problem? Please describe.
Customer reported .NET Agent crashed their application when the application was published as self-contained application with "Trim unused assemblies" flag set to true. 

### Feature Description
There is a feature called “Trim unused assemblies” when publishing a self-contained Core application. Since our agent is loaded at runtime so the compiler did not know the agent depends on some assemblies, so it removes these important assemblies.

[ref1](https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained)
[ref2](https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/)

### Describe Alternatives
- "Trim unused assemblies" flag needs to be disabled.
- https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained#prevent-assemblies-from-being-trimmed

**Comment by Lonli-Lokli** [comment]
Can you consider publishing .NET Agent as a self-contained trimmed too, so it will contain all the required libraries? As it affects only newer versions of .NET, it might be possible to just create a new version for an agent

**Comment by michaelgoin** [comment]
Recommend a separate research spike for this effort.
