### ISSUE TITLE
Add documentation to docs site for existing Environment Variables

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#403]
### Feature Description
The following environment variables are recognized by the Agent, but are not documented. This Issue is to add documentation for them:
  * NEW_RELIC_APP_NAME
  * NEW_RELIC_LICENSE_KEY

### Additional context
[Docs site page](https://docs.newrelic.com/docs/agents/net-agent/configuration/net-agent-configuration#environment-variables) to edit.

### Priority
[~~Nice to Have, Really Want~~, Must Have, ~~Blocker~~]

**Comment by nr-ahemsath** [comment]
I reviewed the draft documentation update and it looks good. 👍
