### ISSUE TITLE
Resolve Server issues for UnboundedIntegrationTests

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#419]
### Feature Description 
The AWSLinux server set up to host the unbounded services for the UnboundedIntegrationTests has issues that cause the tests to fail for reasons other than bugs in the code being tested. As a result, UnboundedIntegrationTests are run locally, targeting other servers. Currently, there are 3 servers available for running the unbounded services:

- local docker containers created using UnboundedServices\linux\docker-compose.yml (127.0.0.1)
- AWSLinux server created for running the tests from GHA (52.42.140.19)
- Azure/Jenkins server formerly used when CI was in Jenkins (172.17.0.13)

These options are necessary in the interim while the AWSLinux server issues persist.

When running the tests locally, the local secrets.json file specifies which server to use for which service. This file is stored in LastPass. There are currently 3 secrets.json files in LastPass, some of which target multiple servers. These files should be the 'source of truth' for the targeted server. One proposal is to have a secrets.json file in LastPass for each of the 3 options mentioned above. Another idea is to have a secrets.json file targeting specific servers for each service based on consistent successful test runs.

Impact: Intermittent test failures and confusion about which server to use cause extended times to verify the tests. This impacts not only the release process, but also inhibits the use of the tests day-to-day which could result in bugs not being discovered in a timely way or at all.

Summary of work:
- cleanup secrets.json files in LastPass
- spread understanding and establish a current, interim best practice of how to use these files to run the tests

### Additional context
Other UnboundedIntegrationTests issues: #361 #359 #239 

### Priority
[~~Nice to Have, Really Want,~~ Must Have, ~~Blocker~~]

**Comment by lspangler584** [comment]
Results of running UnboundedIntegrationTests on this developer's local environment:

secrets file from LastPass | vpn | results |  
-- | -- | -- | --
GHA-Public   Linux-Hosted Integration Tests Secrets | Pdx_split | None passed |  
GHA-Public   Linux-Hosted Integration Tests Secrets | Pdx_full | All passed except       OracleStoredProcedureTests    NServiceBusTests |  
Internal Azure   Secrets for IntegrationTests | Pdx_full | After editing   & processing (see #2 below)   None passed;   Cannot rdp to   server |  
Internal Azure   Secrets for IntegrationTests | Pdx-split |   |  
localhost | n/a | Mssql tests fail   'login failed for user 'sa''.   Multiple tests   fail on 1st run, pass when run separately. |  
  |   |   |  

1. GHA-Public   Linux-Hosted Integration Tests Secrets requires pdx_full VPN access.
2. Internal Azure   Secrets for IntegrationTests in LastPass is stored in preprocessed format, requiring processing as described [here](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/docs/integration-tests.md#secretsjson-file-template). It should be stored in post-processed format, like GHA-Public   Linux-Hosted Integration Tests Secrets.
3. IntegrationTestSecretsBeta in LastPass target server 172.17.0.13, except for Couchbase, RabbitMQ, MongoDB26, which target 172.17.0.15.
4. IntegrationTestSecretsBeta in LastPass contains additional values for Couchbase tests (e.g. ApplicationGatewayResourceId, NewRelicLogFilesUri, ConnectionEndpoint, ServerCertThumbprint, etc.). Are these required?
5. Cannot sign in to InternalAzure, 172.17.0.13 over pdx_full VPN, but can from pdx_split.

**Comment by lspangler584** [comment]
1. Decision: secrets.json files in LastPass will be stored in the pre-processed format. Rationale: secrets in GH are stored in pre-processed format, the GHA CI [pulls those and performs the conversion](https://github.com/newrelic/newrelic-dotnet-agent/blob/cede5f2c53f723b3124e44f29822340bfcef54ff/.github/workflows/all_solutions.yml#L595-L597). This will keep our local testing consistent with GHA CI.
2. Alex will clean up and standardize the secrets.json files stored in LastPass.

**Comment by lspangler584** [comment]
1. Removed `Internal Azure Secrets for IntegrationTests` and `IntegrationTestSecrets (Beta)` from LastPass.
2. Updated `GHA-Public Linux-Hosted Integration Tests Secrets` in LastPass to pre-processed format.

Reviewer:
1. download `GHA-Public Linux-Hosted Integration Tests Secrets` from LastPass.
2. run `dotnet user-secrets` ([instructions](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/docs/integration-tests.md#secretsjson-file-template))
3. Rebuild and run UnboundedIntegrationTests locally.

Tests all passed locally for me, except known [issue ](https://github.com/newrelic/newrelic-dotnet-agent/issues/359)with OracleStoredProcedureTests.

**Comment by nr-ahemsath** [comment]
Reviewed/testing per the instructions in the previous comment and it all worked as expected for me.  Closing.
