### ISSUE TITLE
Update Agent API docs page to include missing APIs

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#428]
### Feature Description
[Agent API docs page](https://docs.newrelic.com/docs/agents/net-agent/net-agent-api) is out of date. For instance, it includes `AddCustomParameter` (deprecated) and does not include `AddCustomAttribute` (replacement). This prevents us from providing a link to customers when discussing API options and may cause customers to use deprecated APIs if they are creating new development.

Deprecated APIs are marked as such on the API-specific page, but it would be helpful to add `(deprecated)` to the main page where all are listed.
Review all available APIs in the Agent and add missing ones to the page.

### Priority
[~~Nice to Have,~~ Really Want, ~~Must Have, Blocker~~]

**Comment by nr-ahemsath** [comment]
PR: https://github.com/newrelic/docs-website/pull/14190
