### ISSUE TITLE
Microsoft.Extensions.Logging LiC (Spike)

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-dotnet-agent#448]
Spike to determine the feasibility of creating a log enricher for [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging?view=dotnet-plat-ext-5.0) using the [ILogger interface](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0). Reference docs [ here](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging) and [here](https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter).

Acceptance criteria:

- Confirm that we can both enrich and format logs
- Build a prototype that works with console or file output (whichever is easier) or identify the blockers preventing implementation
- If successful, estimate production implementation

Aha! Link: https://newrelic.aha.io/features/DOTNET-291

**Comment by angelatan2** [comment]
Internal Spike outcome documented [here](https://docs.google.com/document/d/1_NudTtLLfiTyXkEKVWSgfxyWx_9_L3kLHRvB66iRp8A/edit)

**Comment by jeremysimmons** [comment]
@angelatan2 I'd love to be able to use this. Was the work ever pushed to a branch?

**Comment by angelatan2** [comment]
@jeremysimmons Thanks for pinging!  We have an early support for MEL that is currently looking for customers to assess.  The design is different than what we originally set out to do in this ticket.  We'd love to see if you are willing to try it out, however the program is only available for our existing customers.  Could you confirm if you are customer first?  You can also reach me directly at angelatan@newrelic.com with this information.
