### ISSUE TITLE
Spike: Review the .NET Agent code base and identify breaking changes for 9.0

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#457]
### Feature Description
The last major release that we had was v8.0 released in March 2018.  There were features identified as "Deprecated". 

The first goal of this spike is to document and outline all features marked deprecated so that we can 
1) Communicate again to our customers
2) Remove the functionality.

The second goal of this spike is to identify new features that we plan to deprecate.  An example would be Cross Application Tracing enabled by default.  

Please also look for versions of the .NET framework, Core or 3rd part libraries that we would like to deprecate support.

### Priority
Must Have

**Comment by lspangler584** [comment]
Adding reference to #441 Major Release - Consider removing Deprecations

**Comment by vuqtran88** [comment]
This is completed.
