### ISSUE TITLE
Creates an agent spec for CSP support

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#462]
.Net Agent just got added an overloading api method `GetBrowserTimingHeader(string nonce)` to support CSP. Considers creating a spec for this so that other language agent can reference the work.

**Comment by angelatan2** [comment]
Vu submitted this spec change for review.  4/5

**Comment by vuqtran88** [comment]
[spec PR link](https://source.datanerd.us/agents/agent-specs/pull/555)
