### ISSUE TITLE
Handle OPTIONS requests for asp.net applications

### ISSUE THREAD

**Issue by lspangler584** [newrelic/newrelic-dotnet-agent#463]
Feature Request - HTTP OPTIONS requests (CORS)
[AHA ](https://newrelic.aha.io/ideas/ideas/DOTNET-I-1146)(internal link)
[Original customer ticket](https://newrelic.zendesk.com/agent/tickets/442373) (internal link).

### Feature Description
For OPTIONS requests, in this case CORS preflight requests from browsers, the agent creates the misleadingly named transaction WebTransaction/ASP/. Customer would like these handled differently. 

### Describe Alternatives
Considered the options for resolution as described [here ](https://docs.google.com/document/d/1K9RFr3NXtkeyndzrr0R99om1kVn87p_s4WtMNHs5hag/edit)(internal link).

### Additional context
Why was this considered a [bug](https://source.datanerd.us/dotNetAgent/dotnet_agent/pull/2400) in ASP.NET Core instrumentation?
	- It was creating MGIs

Why was this bug not fixed in ASP.NET instrumentation? (WebApi2, MVC)
	- The application in the original [ticket](https://newrelic.atlassian.net/browse/SUPNET-492) reporting this issue was ASP.NET Core

ASSUMPTIONS:
- The Agent should handle OPTIONS requests consistently for both ASP.NET Core and ASP.NET.
- Affected Agent instrumentation includes WebAPI 2 and MVC. 

RECOMMENDATION:
Ignore OPTIONS requests for ASP.NET requests.

- Pros: 
      - Consistent with ASP.NET Core instrumentation
      - Avoids MGIs
      - OPTIONS requests are not generated by Customer code, they are the result of browser configuration and directed by Customer code.
      - Reduces impact on throughput measurements by not creating 2 transactions for each request (1 for the OPTIONS request and 1 for the actual customer code controller request)
      - Easy/quick to implement

- Cons:
      - No visibility into OPTIONS requests. If there is a problem with the request, or it is taking significantly long, there would be no visibility. Could partially mitigate by logging (finest) when an OPTIONS request is received (and not create a tx for it). This would show that OPTIONS requests are happening, but not how long they are taking.

T-Shirt Size: Small

### Priority
[~~Nice to Have, Really Want~~, Must Have, ~~Blocker~~]

**Comment by angelatan2** [comment]
3/16/2021 Moved from Q4 Bug Smash to FY22Q1 Bug Smash Draft Milestone.
