### ISSUE TITLE
.NET Agent should send configuration settings on Connect event

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#472]
### Feature Description
The agent have not been sending agent settings data in the `settings` element in the CONNECT payload. It has been only sending browser_monitoring.loader_debug and browser_monitoring.loader  under the `settings` element. Because of this, internally we don't have visibility on usage on certain features for support purposes.

refs:
[link1](https://github.com/newrelic/newrelic-dotnet-agent/blob/8eb6d0191762152f8bf1871097994fb8c3b15f93/src/Agent/NewRelic/Agent/Core/DataTransport/ConnectModel.cs#L57)
[link2](https://source.datanerd.us/agents/agent-specs/blob/master/Connect-LEGACY.md#connect-request-fields)

**Comment by elucus** [comment]
@vuqtran88 should we close this issue?

**Comment by vuqtran88** [comment]
> @vuqtran88 should we close this issue?

👍
