### ISSUE TITLE
8T not working in Azure web services

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#479]
**Description**
In an Azure web service, the agent has a problem connecting the NR trace observer and logged out the following messages.

```
2021-03-03 22:49:52,583 NewRelic  DEBUG: [pid: 8852, tid: 5] SpanStreamingService: Timeout creating gRPC channel at endpoint xxxxx-xxx-xxx-xxx.aws-us-east-2.tracing.staging-edge.nr-data.net:443. (attempt 0, timeout 10000ms) 
2021-03-03 22:49:52,587 NewRelic FINEST: [pid: 8852, tid: 5] SpanStreamingService: Backoff for 15000ms before attempting to reconnect.
```
**Expected Behavior**
The agent should be able to connect to NR trace observer to stream data.

**Steps to Reproduce**
1. Create an Azure web service targets .Net Core 2.1 + or .Net Framework 4.8+
2. Install the .NET agent via "Extesions" blade.
3. Configure the agent to instrument the web service.
4. Configure the agent to enable infinite tracing.
5. Exercise the web service.
6. Check the agent logs in Kudu, you will see the above log messages.

**Comment by angelatan2** [comment]
Size: S 
Issue is reproducible.

**Comment by vuqtran88** [comment]
I'm not able to reproduce the issue any more. I tested this with an Azure web service that targets net core 3.1/2.1, net5 and net48.

This issue could be only temporary due Microsoft constantly updated their hosting environment.

Closing this for now.
