### ISSUE TITLE
Virtuoso: Build Windows Environment to host .NET Core apps in two ways

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#495]
Hosting methods:
Windows Service
TaskScheduler

Apps should just host an ASP.NET Core site for simplicity - Virtuoso already has one we could use.

The install configs do not need to be generalized and can be tightly coupled to the scenario.

Base config: https://github.com/newrelic/open-install-library/blob/main/test/manual/definitions/apm/.net/windows/iis-server2019.json

Acceptance Criteria
Preferred Outcome: Produce a new JSON file that setups the apps.
Pushed to open-install-library
Alternate Outcome: We have a working server to test against for the spike only

**Comment by angelatan2** [comment]
Per Jacob, If we need a new server environment, we will create them as part of the feature milestone itself.  Closing this issue.
