### ISSUE TITLE
Build Linux Environment to host .NET Core apps in two ways:

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#496]
Hosting methods:
Systemctl or equivalent
script

Apps should just host an ASP.NET Core site for simplicity - Virtuoso already has one we could use.

The install configs do not need to be generalized and can be tightly coupled to the scenario.

Base config: None, but node has https://github.com/newrelic/open-install-library/blob/main/test/manual/definitions/apm/node/node-linux2.json

Acceptance Criteria
Preferred Outcome: Produce a new JSON file that setups the apps.
Pushed to open-install-library
Alternate Outcome: We have a working server to test against for the spike only

**Comment by angelatan2** [comment]
Moving this back to In Progress after the planning meeting. Let's spend a couple of days to document the spike outcome as well as to finish the the PR [287](https://github.com/newrelic/open-install-library/pull/287).
