### ISSUE TITLE
Virtuoso: Create Windows recipe to install and configure the agent to instrument the installed apps

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#497]
The base recipe does most of the install work already.  The majority of the work will be configuration.

The recipes do not need to be generalized and can be tightly coupled to the scenario.

Base recipe: https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/dotNet/windows/net-install.yml

Acceptance Criteria
---------------------
A valid recipe that instruments as much as possible of the install apps
A dataset covering what worked well, what could have gone better, and what did not work
Pushed to open-install-library

**Comment by angelatan2** [comment]
Closing this ticket.  There are multiple conversations about better agent installs other than Virtuoso for new installs.  We'll open a new ticket if the request comes back.
