### ISSUE TITLE
SPIKE: Are same-named dlls in lib\<framework> dirs of extracted pkgs the same

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#514]
### Feature Description
How does the scanner handle same-named DLLs in different <framework> folders for a package or for different packages?  We get the version automatically from the DLL it self.

Probably need to store the assemblies under a structure the understands framework versions and packages they came from - at least generally.

Acceptance Criteria
- Answer the question
- Create story(s) as needed from results

**Comment by jaffinito** [comment]
While pairing with Vu on a different story ( #515 ), I think we are addressing this with that work.
We will be iterating over each package/version combo serially so that there is no overlap of the key assemblies and the available assemblies for matching remains tied to the package version.  For example, if we are looking at MongoDB, which requires two different packages for some versions, if the packages both have System.Web.dll, it doesn't matter since we only care about the MongoDB assemblies.  

As for the framework folders, we have a few ideas on this. 
- We only look at the latest version of the framework in question.  For example, if there are net45 and net461 folders, we only look in net461.  This could be extended to also check .Net Core or .NET 5.
- We have the ConsoleScanner take another argument that specifies what to look for and it tries to get as close to that as possible with some logic

At this point, we don't need anymore stories since the work will be rolled into #515.  Will be closing this after standup tomorrow

**Comment by angelatan2** [comment]
Closed issue based on the comments from Jacob's and Vu's pairing.
