### ISSUE TITLE
Validate if the agent is compatible with Google.Protobuf ver 3.15.7.

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#520]
Validate if the agent is compatible with Google.Protobuf ver 3.15.7.

**Comment by JcolemanNR** [comment]
In order to validate this, we will need to manually enable Infinite Tracing. Instructions here:
https://docs.newrelic.com/docs/distributed-tracing/infinite-tracing/introduction-infinite-tracing/

**Comment by angelatan2** [comment]
We've updated our agent to    <PackageReference Include="Google.Protobuf" Version="3.20.0" />.  @vuqtran88, is there a reason for validating just a specific version of 3.15.7, or are you referencing the latest at that time?

**Comment by angelatan2** [comment]
This issue was addressed in .NET agent version 10.0.0
