### ISSUE TITLE
Virtuoso: Create/Update the document that shows New Relic Agent Install path/environment

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#521]
This story is for us to update the doc that shows the many combinations that the New Relic agent needs to be able to install and function.  

.NET Framework
.NET Core
.NET

Please update this internal doc [Current .NET Agent supported environment](https://docs.google.com/document/d/1EVopG8v4fkFEqWitg3thpA54tOyWgaf2y4tznI7mjDU/edit?ts=60650c21#heading=h.2z2zo2hs9bv3)

**Comment by jaffinito** [comment]
Updated the doc with current information.
