### ISSUE TITLE
IIS or ASP.NET not installed

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#530]
### Feature Description
Currently, we report an error and exit with a non-zero code when we cannot detect that IIS or ASP.NET is installed. This is not really an error since it just means that the recipe does not match the customers installation environment. Since this is all scripting, we could change this behavior. The following seems like a good approach:

1. Use the existing script for IIS/ASP.NET detection.
2. Change the failure message from Write-Error to Write-Host (easier to see).
3. Change the exit code from 1/2 to a [specific code ](https://github.com/newrelic/open-install-library/blob/main/docs/error-codes.md)from the open install library.

Codes:
- ASP.NET not installed => 2
- IIS not installed => 2

**Comment by nr-ahemsath** [comment]
Should be resolved by https://github.com/newrelic/open-install-library/pull/319

**Comment by nr-ahemsath** [comment]
Closing as the related PR in the `open-install-library` repo has been merged.
