### ISSUE TITLE
Powershell - IIS permissions problems

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#531]
### Feature Description
The recipe doesn't interact with IIS in any meaningful way except to run iisreset and to ask for bindings. If the inital CLI was not run as administrator, iisreset will likely fail. The binding request may as well - I have not tested this out.  If the previous assumptions are correct, then the problem is with powershell and not IIS.  One approach would be to check if powershell is running as administrator and exit.  

Examples are below: (Test this in Powershell 5 and 7, maybe 4?)

```
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
```

OR

```
if ((New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator))
{
  Write-Output "Elevated."
}
else
{
  Write-Output "Not elevated."
}
```

**Comment by nr-ahemsath** [comment]
Should be resolved by https://github.com/newrelic/open-install-library/pull/319

**Comment by nr-ahemsath** [comment]
Closing as the related PR in the `open-install-library` repo has been merged.
