### ISSUE TITLE
Add environment variable configuration options for agent log level and location

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#532]
### Is your feature request related to a problem? Please describe.
Troubleshooting agent issues for customers almost always involves increasing log level to debug or higher and gathering logs.  This is difficult or impossible in deployment environments, e.g. ECS Fargate, that do not allow filesystem access.  Additionally, other cloud deployment environments require configuring an alternative path for agent logs (e.g. [Azure Web Apps](https://docs.newrelic.com/docs/agents/net-agent/azure-installation/install-net-agent-azure-web-apps/#log-linux)), which is difficult to do with the newrelic.config file when deploying using the `NewRelic.Agent` Nuget package (because the contents of the `newrelic` folder are added to your project read-only).

### Feature Description
To solve the above issues, environment variable config options are needed for:
* Agent log level
* Agent log location

### Priority
Priority is "really want" but will move to "must have" as these kinds of deployments become more common.

**Comment by angelatan2** [comment]
5/3 - Sized as S (small effort with high impact for troubleshooting)
