### ISSUE TITLE
Virtuoso - Review the prototype recipe

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#541]
* Review the [prototype](https://github.com/newrelic/open-install-library/pull/292) and the feedback from Virtuoso on it. 
* Code walkthrough.
* Should result in updated stories for the recipes (most of the other stories in this milestone)

## Acceptance Criteria
* Mob understands the code and reason behind it
* Feedback is incorporated into the future work on recipes

**Comment by jaffinito** [comment]
Reviewed this with the team.
