### ISSUE TITLE
 Virtuoso - Build recipe .NET install on AWS Linux 2

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#552]
Take the existing ubuntu .net recipe and either duplicate it and make it compatible with RHEL - tested using AWS Linux 2 - or adjust the recipe to work for both RHEL and DEB distros.

## Acceptance Criteria
* Prompts to install any tools it needs
* Detects running .NET processes
* Determines if they are directly called by a systemd service
* Stops those services
* Uninstalls any previous version of the .NET agent cleanly, preserving existing configuration (global newrelic.config, custom instrumentation)
* Installs the .NET agent
* Configures the service in a non-destructive and reversible way to add the required env vars, including app name set as service name
* Configures the agent for DT, staging and adds app name
* Starts services
* Determines the ports .NET apps are using
* Uses curl to ping the endpoints with ports (or prompt user for endpoint to hit)
* Cleans up any temp files it creates

**Comment by angelatan2** [comment]
PR: https://github.com/newrelic/open-install-library/pull/352
