### ISSUE TITLE
Virtuoso - windows-iis.yml recipe - assert_pre_req is failing with status code 1 in a few case

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#553]
In the windows-iis.yml recipe, the assert_pre_req task is failing with status code 1.  This indicates that something is breaking during the checks.

Investigate ways to address or handle potential problems that could occur during this step.   If a problem cannot be handled, a unique exit code should be used to make it possible to identify in reports

Potential issues:
- Get-WindowsOptionalFeature  does not exist due to Windows version or powershell verison differences
- Get-WindowsOptionalFeature  is succeeding, but due to version differences it is erroneously returning exit 1 instead of 0
- State may not be returning Enabled as expected even if the feature is present
- The feature names are different due to windows or powershell version issues.
- Are we looking at the right feature for ASP.NET 4.5?

Possible approaches
- Use a try-catch to to capture any errors and return meaningful error codes
- Use a try-catch to to capture any false exist code 1 issues and force return 0
- Check for alternate feature names (if this is discovered to be a problem)

**Comment by JcolemanNR** [comment]
Closing as 'assert_pre_req' has already been refactored away in the `windows-iis.yml` recipe
