### ISSUE TITLE
.NET 6 Preview 3 Validation - Functional Regression Testing

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#566]
This story is a placeholder for .NET 6 Preview 3 validation regression testing of agent features.  We need to verify that .NET 6 Preview 3 does not break existing agent behavior.

The approach used in the past has been to re-target as many existing .NET Core integration test applications to the new version (so `net6.0` in this case) and run the tests.  We will continue to use this approach for .NET 6 Preview 3.

**Comment by jaffinito** [comment]
Doc with notes on problems and issues:
https://docs.google.com/document/d/1v-CGipLTSm83HQ3PStnJR8-Pj0mxvClnz2Y5PzTwM_c/edit?usp=sharing

**Comment by nr-ahemsath** [comment]
Issues with retargeting the (core) integration test applications to .NET 6 and running the associated tests are documented in the linked (internal) document above.  None of the issues found point to an issue with the agent being able to instrument .NET 6 applications; the issues are all with the mechanism of the tests themselves.  Closing this issue.
