### ISSUE TITLE
Add .NET 6 to Angler and BMDS

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#573]
We need to make sure we can measure the adoption rate of .NET 6 by our customers.  To that end:

1. Add a supportability metric to the agent for .NET 6
2. Add that supportability metric to [Angler](https://source.datanerd.us/agents/angler/blob/master/src/main/resources/metric_names.txt)
3. Add support for .NET 6 to [BMDS](https://source.datanerd.us/architecture/bmds/blob/master/src/main/java/com/newrelic/bmds/AgentLifecycleEventDotnetTransformer.java)  (which looks at the Environment.Version data passed in the connect payload)

**Comment by nr-ahemsath** [comment]
The first two items have been taken care of.  Updating BMDS is proving to be a little more difficult because of an issue cloning that repo on Windows; I'm working on a solution with that repo's owners.

**Comment by tehbio** [comment]
[BMDS PR here](https://source.datanerd.us/architecture/bmds/pull/111).
