### ISSUE TITLE
.NET 6 Preview X testing - .NET 6 container images

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#577]
Per the .NET 6 preview release notes, there have been improvements related to .NET running in containers, and there are [new .NET 6 container images](https://hub.docker.com/_/microsoft-dotnet-nightly-sdk/) available.  We need to smoke test the agent instrumenting an app running in these containers.

A wild idea: take the [eShopOnContainers reference app](https://github.com/dotnet-architecture/eShopOnContainers) and modify it to use .NET 6 preview container images, and then add the agent to instrument services as appropriate.  This might be a stretch, so getting a simple smoke test app up and running first is essential.

**Comment by JcolemanNR** [comment]
Upgraded eShopOnContainers to .NET 6, and instrumented all the .NET microservices with the Agent. All services reported reasonable metrics and I ended up using the agent to help troubleshoot issues that surfaced in eShopOnContainers during the .Net 6 migration.

Mission Accomplished!
