### ISSUE TITLE
Send app name and source in environment data

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#580]
### Is your feature request related to a problem? Please describe.
One of our support team's largest sources of customer tickets is application naming.  We have a separate and specific public doc for how to name your applications: https://docs.newrelic.com/docs/agents/net-agent/configuration/name-your-net-application/, which is an indication that it's somewhat complicated.

One of the things that makes this issue challenging is that neither a user of the agent nor our support team can tell where an application name is coming from (main `newrelic.config`, app-local `newrelic.config`, app.config, environment variable) without examining the agent log file at a non-default level (DEBUG level at least).  It would be helpful for everybody involved if information about where an application's name came from was always available in a convenient place.

### Feature Description
The source of an application's name should be available in the NR user interface.  An initial proposal will be to put this data in the `Environment` page for each application.  This will mean modifying this part of the agent: https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/Environment.cs  It would also mean having to modify [this code](https://github.com/newrelic/newrelic-dotnet-agent/blob/6271f650dd0e035633a2bc4ef36c272368e8b25a/src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs#L219) to return the source of the application name as well as the name itself.

Potential concern: will the configuration parsing be finished before the environment data is sent to NR?

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by neilpdx** [comment]
+1 on this feature! If we can also send the **file path** of the naming source (when using newrelic.config, app.config, web.config etc.) that would be the most helpful to help users track down exactly where the file is.

**Comment by cbp123** [comment]
I believe this change may not play nicely with .NET Config Builders in .NET Framework: https://docs.microsoft.com/en-us/aspnet/config-builder
We pull the NewRelic.AppName setting in via a config builder, and we noticed that our data started going through to our test account instead of prod account after updating the agent.

**Comment by tehbio** [comment]
Hey @cbp123 couple things -

This change should not have had any effect on the AppSettings the Agent is able to find and use, it only added visibility to the UI on where these might be being pulled from.

But as you've found, the Agent's current AppSettings reading is very limited and does not support things like Configuration Builders. Instead, we suggest you leverage environment variables directly to control these settings, such as `NEW_RELIC_APP_NAME` for Application Name or `NEW_RELIC_LICENSE_KEY` for your account license key. More can be found in our documentation [here](https://docs.newrelic.com/docs/agents/net-agent/configuration/net-agent-configuration/#environment-variables).
