### ISSUE TITLE
.NET 6 Preview 4 - Modify integration tests to target net6.0 where applicable and verify tests pass

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#596]
Modify the integration tests (both regular and unbounded) to target .NET 6 where applicable (i.e. all .NET Core test applications are retargeted to net6.0) and verify all tests pass.

Internal document tracking issues and progress: https://docs.google.com/document/d/1v-CGipLTSm83HQ3PStnJR8-Pj0mxvClnz2Y5PzTwM_c/edit

Branch with this work: https://github.com/newrelic/newrelic-dotnet-agent/tree/net6preview-testchanges

Success criteria:
1. All .NET Core integration test applications retargeted to net6.0
2. All .NET Core integration tests pass.  Exceptions can be noted and accepted if we can document why the failures are not related to changes in .NET 6 Preview 4

**Comment by JcolemanNR** [comment]
@nr-ahemsath this task has been completed with the exception of the unbounded integration tests not being fully run. If we do another round of validation for a RC build we should make sure these get run. The errors we saw, and reasons for them are documented here: https://docs.google.com/document/d/1v-CGipLTSm83HQ3PStnJR8-Pj0mxvClnz2Y5PzTwM_c/edit
