### ISSUE TITLE
.NET 6 Preview X Testing - Stretch Goal - Support for "fast inner loop/hot reload"

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#599]
One of the major themes of .NET 6 is improving developer productivity in the dev/test/debug/fix cycle ("fast inner loop").  One of the main features enabling this is "hot reload", which is the ability to make changes to the source code of a live running application and have those changes applied to the app without recompiling and restarting the application.

While the agent is primarily used for application performance monitoring in production, not development, it would be good to know what would happen if the agent was attached to an application in this hot reload scenario.  At a minimum we should "do no harm", even if we can't produce meaningful data.

**Comment by jaffinito** [comment]
We currently have no impact on this feature.  We will need to retest when they release an update that includes support for Razor pages.
