### ISSUE TITLE
Update GPG signing in linux package deploy scripts to handle GPG 2.x+

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#605]
Summary: the APT/YUM repo signing command used in the scripts that deploy our .deb/.rpm install packages for Linux fails when run on a `debian:stable` system.  We believe the issue is caused by `debian:stable` having a 2.x version of GPG, whereas `debian:jessie` has a 1.x version.

More context: we [recently tried updating](https://github.com/newrelic/newrelic-dotnet-agent/pull/546) the base container image used by the APT/YUM repo deploy process from `debian:jessie` to `debian:stable`; however, the first time we tried deploying the agent to `apt.newrelic.com` and `yum.newrelic.com` with the updated process, the repo signing process failed, causing anybody trying to run `apt-get update` with our repo configured to get an error about an unsigned repo.

The specific error in the output from the [signing command](https://github.com/newrelic/newrelic-dotnet-agent/blob/5a808b374c385659ca834632d094e89017e682a2/deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash#L83) was:
```
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

We've reverted the base container image for this process back to `debian:jessie` for now, but we want to upgrade eventually to mitigate CVEs found in our repo by security scan tools due to using an old, out-of-date version of debian for this process (although note that this container is only used for a deploy process and isn't shipped to any customers with the agent).  In order to upgrade we will have to find a fix for this signing error.

**Comment by tehbio** [comment]
In addition to handling GPG 2x+, this step (and every step in the deployment process) should _not_ silently fail, and any errors or failures _must_ cause the deployment process to fail.

**Comment by SongGithub** [comment]
I suggest to have a non-prod environment to enable e2e test, in order to guard against similar case in future:
- publish to the non-prod env's repo
- run `apt-get install <nr-agent-name>` against the non-prod repo, and assert there is no error when installing
- optionally prove if the NR-agent release is working correctly
- trigger production release if no-error picked up in above steps.

**Comment by angelatan2** [comment]
@SongGithub Thanks for your detail suggestion.  We recognize the gaps in our test and plan to close them to avoid issues like this.  I hope you did not run into issues with our update two days ago.  If you did,  we apologize for the inconvenience and disruption.

**Comment by nr-ahemsath** [comment]
A solution which should get us to "done" (in terms of having a working solution that uses a currently-supported version of Debian for the base container image - this wouldn't address the other goal of preventing the script from failing silently) would be:

1. Change the [container base image tag](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/deploy/linux/container/Dockerfile) from `debian:jessie` to `debian:buster-slim` (if we really wanted to pin a version and make sure nothing changes out from under us we would do `debian:buster-20210511-slim` or whatever the latest version is at the time of the work.  See https://hub.docker.com/_/debian for more info on Debian container image tags.  Per [this wiki](https://wiki.debian.org/LTS), "buster" (or Debian 10) is supported through June 2024.
2. Install `gnupg1` package from apt (so `apt install gnupg1`) so we can continue to use a 1.x version of gpg.
3. Change the [repo signing command line](  gpg -abs --digest-algo SHA256 --keyring gpg-conf/pubring.gpg --secret-keyring gpg-conf/secring.gpg -o "dists/$REPO/Release.gpg" "dists/$REPO/Release") to use `gpg1` instead of `gpg`.

I've verified on an Ubuntu 20.04 VM that `gpg1` works to sign a file the way that we are currently using it in the APT repo deploy process.
