### ISSUE TITLE
Linux Kudu not accessible when .NET agent presents.

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#616]
**Description**
When installing the latest agent on an app specifically targeting .NET 5 on linux azure, Kudu is no longer accessible. When removing the agent, kudu works again. It appears that Kudu was instrumented by the agent and it is unclear why the agent broke Kudu.

This only happens in linux azure. It didn't happen on Windows azure, because the profiler was hardcoded to not instrument the .Net Framework version of Kudu.

This is how the profiler is currently detecting Kudu so that it can ignore Kudu.

https://github.com/newrelic/newrelic-dotnet-agent/blob/2ba99ea91ac20f79af40259e485949c6b3b1aac3/src/Agent/NewRelic/Profiler/Configuration/Configuration.h#L171 . This detection would fail when Kudu is invoked with this command `$: /opt/Kudu/Kudu.Services.Web`.
I suspect Microsoft changed how they invoke Kudu which made our detection no longer works.

A fix would be updating the profiler to detect the kudu process in linux and don't do anything.

We may consider a feature where we could specify name of apps that the agent should not instrument.

**Expected Behavior**
Kudu shouldn't break.

**Comment by heatherzurek** [comment]
A fix was added for no longer instrumenting the Kudu process in [.NET agent version 8.26](https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/net-agent-8266300/), although this was before the .NET 5 release.

>Fixes issue for Azure App Service environments running on Linux that caused both the application and its Kudu process to be instrumented by the agent. The Kudu process is no longer instrumented.

**Comment by vuqtran88** [comment]
> A fix was added for no longer instrumenting the Kudu process in [.NET agent version 8.26](https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/net-agent-8266300/), although this was before the .NET 5 release.
> 
> > Fixes issue for Azure App Service environments running on Linux that caused both the application and its Kudu process to be instrumented by the agent. The Kudu process is no longer instrumented.

This is how the profiler is currently detecting Kudu https://github.com/newrelic/newrelic-dotnet-agent/blob/2ba99ea91ac20f79af40259e485949c6b3b1aac3/src/Agent/NewRelic/Profiler/Configuration/Configuration.h#L171 .Whatever the fix mentioned, it didn't fix the case when Kudu is invoked with this command `$: /opt/Kudu/Kudu.Services.Web` .

**Comment by tehbio** [comment]
Quick fix for this [here](https://github.com/newrelic/newrelic-dotnet-agent/pull/618):
https://github.com/newrelic/newrelic-dotnet-agent/blob/ccb277b8d05e45f29cfb7110d2092a80b676a0e5/src/Agent/NewRelic/Profiler/Configuration/Configuration.h#L171
