### ISSUE TITLE
RavenDb Database Support

### ISSUE THREAD

**Issue by gregorylyons** [newrelic/newrelic-dotnet-agent#621]
### Is your feature request related to a problem? Please describe.
When my code is using RavenDb, I do not see the queries surfaced under the "Database" section of APM in NewRelic.
This makes it difficult to diagnose performance issues.

### Feature Description
Similar to the various SQL integrations, surface RavenDb queries under the "Database" section of APM, for the Raven5.x client.

### Describe Alternatives
Not feasible, the dotnet-agent does not expose the ability to log items into the "Database" section.

### Additional context
More recent versions of RavenDb seem relatively easy to expose the underlying query (without parameters) as a string, leading to a (hopefully) simple implementation. The client's source is easy to view on GitHub: https://github.com/ravendb/ravendb

### Priority
Really Want

**Comment by gregorylyons** [comment]
I am interested in contributing code to implement this functionality.

**Comment by angelatan2** [comment]
Hello @gregorylyons, thanks for filing this issue within the New Relic .NET agent repository.  We welcome contributions from the community especially on frameworks and datastores that we haven't supported.  

We look forward to your PR for this new feature support.  

All,
Any developers coming across this issue,  we would truly appreciate a thumbs-up, if you are using RavenDb.  It will help us assess whether the RavenDb datastore is well adopted by our community in addition to looking at the nugget download site.

**Comment by gregorylyons** [comment]
Just dropping a note to mention I'm not currently working on this. Been beating my head against Raven idiosyncrasies, and currently lack the enthusiasm to work with it in my spare time.

(If anyone picks it up, happy to talk over what my plan was - the internals of the client are very clean, but there's some work in deciding which commands to log, and thinking about how to differentiate queries -  both on static indexes, and auto indexes, without spamming up the newrelic output)

**Comment by angelatan2** [comment]
@gregorylyons thanks for letting us know.  Noted!
