### ISSUE TITLE
APM for Azure Functions running on .NET Core 3.1

### ISSUE THREAD

**Issue by declan4mat** [newrelic/newrelic-dotnet-agent#634]
Hi,

It would be very valuable for us if we could use New Relic APM on our Azure function apps

We use APM for all of our application instances, including our deployed Azure App Service instances and it works great, but there is a gap when it comes to our function apps where we have to use AppInsights.

This would enable us to keep our realtime reporting, exception management and performance optimizations in the same stack

Please see my information here https://discuss.newrelic.com/t/please-help-me-enable-apm-for-a-net-core-3-1-azure-function-application/146659

Thank you!

**Comment by JcolemanNR** [comment]
Hello @declan4mat! 

From what I understand we have an Open Telemetry based product being developed by another team that is used for Azure function apps. Assigning this ticket to @elucus to provide more information.

**Comment by elucus** [comment]
Hi @declan4mat we have another team that is working on this. It's still a WIP but I'm going to transfer this issue to their repo.

**Comment by declan4mat** [comment]
Thanks for the tip, this looks promising - ill take a look!

I see it's a work in progress, so I understand it's possible that this solution might not be the final solution offered by NewRelic

However, if I get it up and running, is it likely to fail at some point in the future if it becomes unsupported?
