### ISSUE TITLE
Using the guided install for Linux customers can still install if a systemd hosted .net app is running outside of the service with the service stopped

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#662]
**Description**
If customer is using systemd to host a .net app and has that service stopped, but is running the app outside as just a process, the logic for detecting apps will break down.  It will detect that a .net process is running, and then detect that a service is hosting a .net process.  It likely gets confused at this point since the PIDs don't line up.

Could add some logic in an existing task or a new task to validate that the detected .net apps are hosted and live in systemd and exit if not.  Would want to exit with a new error code, added to error-codes, so that it can be tracked.  Would be a good metric to determine next features to support.

**Recommendation**
There are some details to iron on this so some experimentation may be needed to get the repro 100%

**Expected Behavior**
The agent should not be installed if .NET apps hosted in systemd are not running via the service, but as standalone apps?

**Steps to Reproduce**
1 possible setup:
1. On a Linux server using systemd services (ubuntu, centos, etc.)
2. Run a .NET app outside of systemd and keep it running
3. Run the .net virtuoso install recipe
4. Errors abound.

**Your Environment**
Linux server using systemd services

**Comment by JcolemanNR** [comment]
resulting state when no dotnet processes could be matched to systemd services is that the agent install 'completes' but not has been instrumented. 

Desired behavior: if we can't match to any running systemd services, fail to install with unique message.

**Comment by JcolemanNR** [comment]
Should use existing exit code 20
