### ISSUE TITLE
Agent support Distributed Tracing Server-Side Configuration

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#675]
When DT Server-Side config is enabled for the .NET Agent ver 9.0+. The agent should honor SSC-DT configuration from Server.

#### Acceptance criterion:
Enable/Disable DT from UI. DT SSC should override the DT local config.

**Comment by michaelgoin** [comment]
Sizing assuming wiring up in UI as well plumbing in the agent. Typically UI requires some features turned on and some other plumbing.
