### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#677]
We want to understand the differences in term of Memory usage, CPU utilization and Response Time in the following case scenarios:

1. We want to know Memory usage, CPU utilization and Response Time differences between the default span reservoir size (1000) and span reservoir size of 2000.

2. We want to know Memory usage, CPU utilization and Response Time differences of the test application when DT used or not used.

Notes: Considers using OATS for these performance tests

**Comment by vuqtran88** [comment]
I created a branch in the OATS repo that can test the .NET agent performance for different span reservoir sizes here https://source.datanerd.us/agents/oats/tree/dotnet-dt-tests. I can run the test locally but this need to be run on a test server for consistent results.

**Comment by RichVanderwal** [comment]
The OATS in GitHub Enterprise has a tracking ticket for this right here: https://source.datanerd.us/agents/oats/issues/106

I'll be keeping it updated while I have time. Feel free to modify it yourselves!

**Comment by vuqtran88** [comment]
Test results were updated in  https://source.datanerd.us/agents/oats/issues/106
