### ISSUE TITLE
.NET Agent supports Npgsql driver v5.x

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#680]
### Feature Description
.NET agent is currently not compatible with Npgsql driver v5.x. Only the following database calls are instrumented by the agent:

```
ExecuteDbDataReader
ExecuteNonQuery
ExecuteScalar
ExecuteDbDataReaderAsync
ExecuteNonQueryAsync
ExecuteScalarAsync
```

Calls such as `NextResult`, `NextResultAsync`, `Read` and `ReadAsync` are not being instrumented in the Npgsql driver 5.x version. This is due to the method signature change in the new driver.

**Comment by jaffinito** [comment]
GTSE that initiated the issue:
https://newrelic.atlassian.net/browse/GTSE-10807

**Comment by jaffinito** [comment]
The NextResult, NextResultAsync, Read and ReadAsync methods are instrumented, but they are disabled by default in the instrumentation xml files due to potential performance issues.

**Comment by vuqtran88** [comment]
> The NextResult, NextResultAsync, Read and ReadAsync methods are instrumented, but they are disabled by default in the instrumentation xml files due to potential performance issues.

Great find @jaffinito, we could potentially have different gaps in supporting Npgsql v5.0.

**Comment by elucus** [comment]
[Internal FR](https://newrelic.aha.io/ideas/ideas/DOTNET-I-1191)

**Comment by alexeyshockov** [comment]
Hey there, any news on the topic? Npgsql 4.x is very outdated (7.0 is on its way, to be released later this year).

If the main concern is the performance, I think many users will be OK with losing a bit of speed but have their queries instrumented.
