### ISSUE TITLE
Profiler does not log the release version on startup when the platform is Linux

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#713]
### Feature Description
During a recent GTSE investigation, @nr-ahemsath noted that the profiler did not log the agent version number on startup as expected.  The customer's environment was an Azure App Service with Linux hosting.  Based on a quick reading of the profiler code, it looks like the code that logs the agent version number is completely bypassed on Linux:
https://github.com/newrelic/newrelic-dotnet-agent/blob/c3545e8cb2962f1916222c0e024c343aac48cd66/src/Agent/NewRelic/Profiler/Profiler/ICorProfilerCallbackBase.h#L1019

(the `#ifdef PAL_STDCPP_COMPAT` block is what is built for the Linux version of the profiler, instead of the `#else` block).

This is likely because the API being used to read the agent core DLL's file version info is Windows-specific: https://stackoverflow.com/questions/38094316/getfileversioninfo-equivalent-in-linux

Depending on the effort to implement the equivalent functionality in Linux, I think it would be worth it, since the GTSE issue in question caused a couple days of effort to be spent troubleshooting something which would have been completely obvious if the version of the profiler code running had been apparent from reading the log file.

This will help Customers, GTS, and Engineering while using the agent.

**Comment by angelatan2** [comment]
Move to Q2 Technical Debt Milestone.
