### ISSUE TITLE
Virtuoso: Update Linux recipe Preinstall to check of .NET processes are hosted in systemd

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#714]
We are seeing a spike in "failures" for [.NET on Linux](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/dotNet/linux-systemd.yml) due to exit code 20 being counted as a failuire instead of "unsupported".  Exit code 20 indicates that either systemd is missing or that we found .NET process, but they were not hosted in systemd.

After discussing this with the Virtuoso team, we are going to duplicate much of the scripting in the introspector and gather_services tasks in the preinstall task.  We would leave the tasks in the main recipe since we need to outputs of those tasks for later installation steps.  We currently cannot save any outputs from the preinstall task.

When setting up the new scripting, we should be able to streamline it a bit since we won't be operating across different tasks.  We don't want to break the existing code in the preinstall task!

Acceptance criteria:

* Existing code in the introspector and gather_services tasks is still in place
* Existing code in the preintall task still works
* preinstall task has new code that checks that any running .NET processes are being hosted in systemd services.
* Exit code should still be 20 when discovered processes are not in systemd (same as current tasks)
* preinstall code should be designed to minimize any output to the console (same as with most recipe work)

**Comment by angelatan2** [comment]
This is a duplicate issue. See #750
