### ISSUE TITLE
Consistent naming of agent environment variables that start with "NEW_RELIC" (or "NEWRELIC")

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#718]
### Is your feature request related to a problem? Please describe.

The agent has a number of configuration options that can be set with environment variables.  The names of some/many of these environment variables start with either `NEW_RELIC_` or `NEWRELIC_`.  For the sake of consistency, it would ideal if we could pick one or the other.

I did a survey of all the other agents' configuration documentation, and all other New Relic language agents that support config via environment variables use the `NEW_RELIC_` prefix, so I think that is what we should standardize on.

It would be great if we could eventually get to where the Java agent is, where we can just describe a simple rule for translating config file setting names to environment variable names: https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file#Environment_Variables  However, this is beyond the scope of this issue.

Since this would be a breaking change for customers using variables with whatever prefix we decide to deprecate, we would a) need to announce this change in advance per our standard deprecation policy, and b) only make this change in a future major version release.

Some of these might be in the profiler, see the list below for most of the different ones we offer.  See here for list of env vars: https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#optional-environment-variables

### Feature Description

All agent config environment variable names that start with `NEWRELIC_` are renamed to start with `NEW_RELIC_`.

### Describe Alternatives
We could potentially soften the transition for our customers by allowing the deprecated env var names to continue to work, but log a warning message asking the user to update to the new name.  This would add some complexity but it should be isolated to the method that looks for environment variables when determining agent config.

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have]

**Comment by JcolemanNR** [comment]
Suggestion: perhaps support both patterns, with a preference for one, and standardize all our documentation to that convention

**Comment by michaelgoin** [comment]
For this specific issue, we are assuming the adding of the `NEW_RELIC` as an additional option to avoid breaking change.
