### ISSUE TITLE
Spike: NServiceBus v6+ support

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#730]
### Feature Description
As a customer, I would like the New Relic .NET agent to support versions 6 and 7 of NServiceBus out of the box, so that I have observability in to these areas of my system.

### Describe Alternatives
A customer could hypothetically create a custom instrumentation xml, or use the New Relic Agent API to create transactions, but this is not very realistic.

### Additional context
We currently instrument NServiceBus version 5. In versions 6+ of NServiceBus, the methods we use to observe NServiceBus have been refactored/removed.

[Internal working document](https://docs.google.com/document/d/1q9_QjEwT9O8dOYM9lsgJonPDDjPO0W2KR7Iu_9Knazc/edit#)

### Priority
[Must Have]

**Comment by nr-ahemsath** [comment]
Spike is complete, closing.
