### ISSUE TITLE
Support for Azure Functions with the .NET agent

### ISSUE THREAD

**Issue by neilpdx** [newrelic/newrelic-dotnet-agent#732]
### Is your feature request related to a problem? Please describe.
New Relic does not provide official support for instrumenting Azure Functions.

### Feature Description
Customer would like to use the .NET agent to instrument Azure Functions:

* https://azure.microsoft.com/en-us/services/functions/

### Describe Alternatives
Some discussion of getting Azure Functions to work in the forums:

* https://discuss.newrelic.com/t/installing-the-new-relic-agent-in-an-azure-functions-net-project/153216/4

### Additional context
Although some customers have gotten the agent to work with Azure Functions we do not list this as a supported environment and do not provide any documentation on this, nor do we test in this environment so it's considered unsupported.

### Priority
"Really want."

**Comment by elucus** [comment]
This issue has been transferred to the Serverless Team.

[Internal Link](https://newrelic.aha.io/ideas/ideas/DOTNET-I-1200)

**Comment by ishepherd** [comment]
Hello @elucus, please tell us has there been any movement on that internal ticket?

Azure Functions is a popular option for serverless patterns in Azure

Not knowing your code, but it does not seem like it should be a heavy lift.
Just need to discover methods with the `Microsoft.Azure.WebJobs.FunctionNameAttribute` and inject transactions around those, like you already do with ASP.NET Core.
