### ISSUE TITLE
Add support for overriding App Names per Transaction / Trace.

### ISSUE THREAD

**Issue by dabalakov** [newrelic/newrelic-dotnet-agent#749]
### Is your feature request related to a problem? Please describe.
We're unable to use the multiple app names to control where the transactions from our website land within NewRelic. Our IIS website serves multiple tenants and we want to split each tenant into their own NewRelic App. This in combination with the existing "Multiple App Names" feature would allow us to see APM data from multiple viewpoints (By Tenant, By IIS Web Site across the cluster, By cluster as a whole)

### Feature Description
The reason we need this feature is to be able to diagnose tenant specific issues. The aggregates obscure the issues on the tenant level, because it may only be one tenant that's having issues. We'd like to use the APM New Relic pages to explore the APM data on a tenant by tenant basis that's being served from the same shared infrastructure.

We'd like to see the "multiple app names" feature be able to set it for the transaction instead of for the entire app. This way each request can be routed appropriately instead of affecting other requests that may be in progress at the same time and are for other tenants.

### Describe Alternatives
- Tried the "multiple app names" feature in the .net agent but it works on the agent level and affects all data from the IIS website instead of just controlling the current transaction. This results in transactions appearing under the wrong APM application within New Relic.
- Tried submitting custom attributes with the transaction and that doesn't help since the APM pages don't allow you to filter by a custom attribute across all their pages.
- Tried using the custom attribute to create dashboards, but this doesn't reproduce the same functionality that's been given in the APM New Relic feature, where you can dig into slow sections, and see transactions, and then see the logs related to that. We'd prefer to just use the APM pages new relic offers but be able to filter down to a specific tenant.

### Additional context
We keep getting pitched that custom dashboards is the solution, however we don't agree. We feel that multi-tenant support within New Relic can be achieved and would be beneficial for any SAAS customer of NewRelic's. Not all SAAS businesses create dedicated infrastructure per tenant. Some like us, use shared infrastructure to change the cost model to affect margins and also reduce waste in idle resources and reduce management overhead.

### Priority
This is a Must Have. Without this, we would be looking at alternatives to NewRelic. Ones that would support Multi-Tenanted applications better.

**Comment by elucus** [comment]
Although this is a reasonable feature request, it goes against our New Relic cross-agent specifications. That doesn't mean we would never consider it, but it's not on our short-term roadmap (for agents). 

However,  I've discussed this with our APM UI team, and they are considering adding support for filtering the APM pages by [Tags](https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/use-tags-help-organize-find-your-data/#add-tags-apm-agents).

**Comment by dabalakov** [comment]
@elucus , do tags work on a transaction level, or an agent level? If it's on the agent level then that also won't work for us since one web server is handle several clients at the same time (i.e. a typical multi-tenant web server). We would need tags to work on the transaction level and I currently don't see an API for that. Is that something the dotnet agent team would add support for?
