### ISSUE TITLE
CosmosDB Performance testing

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/newrelic-dotnet-agent#761]
### Feature Description
Performance testing.

We would like to get a good idea of the overhead of our instrumentation. We would like test results with and without instrumentation for comparison.

The Azure cosmos DB instance will be hosted in Azure. The test runner will be hosted in Azure as well.

We should capture the following metrics at a minimum:
- CPU
- Memory
- Azure Cosmos requests/second (or some similar statistic)

We will make a test application that creates Cosmos requests, it should be able to support low->mid->high requests rates to Cosmos.

### Acceptance Criteria
- Report of findings
- Understanding agent overhead instrumenting CosmosDB
-

**Comment by JcolemanNR** [comment]
We used the [Cosmos Performance Benchmark](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Tools/Benchmark) application to perform 1 Million document inserts and observed the CPU/memory load and total document throughput. 

General results are that the agent, and our new instrumentation did not slow the Cosmos Benchmark application down with regards to document insertion rates, but the CPU overhead for the agent (even without cosmos instrumentation) is notable. Peak CPU usage jumped from 39% -> 72% just by enabling the agent without the new cosmos instrumentation. The new cosmos instrumentation increased CPU usage from 72% -> 78% which seems reasonable. The document insertion throughput actually was higher with the agent attached which indicates that we are not slowing things down (as long as there is CPU available).

We performed the following tests:
- No agent attached
- Agent attached but without the new Cosmos instrumentation
- Agent attached and with the new Cosmos instrumentation

**No Agent:**
Average documents inserted per second: 7291.44
CPU peak usage: 39.4%
Memory impact: Negligible
![No Agent](https://user-images.githubusercontent.com/83677148/140560220-cc62b4e7-71fa-42c4-b30d-55f0a8599ecd.png)

**Agent without new Cosmos instrumentation:**
Average documents inserted per second: 7337.83
CPU peak usage: 72.1%
Memory impact: Negligible
![Agent - no cosmos instrumentation](https://user-images.githubusercontent.com/83677148/140560402-2e4e4b03-a41a-4ecd-b792-ba3b23118172.PNG)

**Agent with new Cosmos instrumentation:**
Average documents inserted per second: 7447.15
CPU peak usage: 78.4%
Memory impact: Negligible
![Agent - with cosmos instrumentation](https://user-images.githubusercontent.com/83677148/140560610-8131c13c-9394-418e-a65f-6df188a28745.PNG)

**Comment by JcolemanNR** [comment]
As requested by @vuqtran88, here are the changes made to the Cosmos Benchmark Application to allow the agent to trace the activity:
https://github.com/Azure/azure-cosmos-dotnet-v3/compare/master...JcolemanNR:jcoleman/instrument-benchmark-app
