### ISSUE TITLE
Create/Revive Agent installation tests in GHA CI checks

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#773]
**Description:**
We generate but do not test several installers in our GHA steps run during a pull request. It would be good to test this. 

We should reasonably test different installation options. For example, the windows installers have options to globally enable instrumentation on a system.

**Acceptance Criteria:**
(This should be negotiated before starting work)
1. Windows x86 MSI installer is tested
2. Windows x64 MSI installer is tested
4. Debian x64 installer is tested
5. Debian ARM installer is tested
5. RPM x64 installer is tested
6. RPM ARM installer is tested

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):* P4
*Suggested T-Shirt size (S, M, L, XL, Unknown):* L

**Comment by nr-ahemsath** [comment]
The team feels at this point that the value that installer-logic-specific tests would provide would not be worth the effort required.  The installer content verification testing we added in the past year is sufficient to prevent any additional installer bugs of the kind we've had in the past three years or longer.
