### ISSUE TITLE
Add support for API Gateway HTTP APIs (v2) for .NET 3.1 and above

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#775]
AWS has updated their API Gateway APIs resulting in our Lambda SDK no longer picking up API Gateway calls.
They have changed the type names as well as how the APIs function.
THey have moved away from REST to HTTP, but this may not affect our instrumentation, just a heads up.

Code:
https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/AwsLambda/AwsLambdaWrapper/IOParser.cs#L38-L67

Link to article:
https://aws.amazon.com/blogs/developer/one-month-update-to-net-core-3-1-lambda/

GTSE ticket:
https://newrelic.atlassian.net/browse/GTSE-11894

**Comment by kngo10** [comment]
Hi @angelatan2 @elucus 

Can we please prioritize this ticket? currently we couldn't  see our Lambda API performance in new relic. 

Thanks
Regards
