### ISSUE TITLE
[.NET 6] Thread safety issue in access to HTTP headers collection in HttpClient on .Net 6

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#803]
We've been informed by Microsoft that New Relic is causing exceptions in some customer applications due to our access to the HTTP headers collection in HttpClient: https://github.com/microsoft/reverse-proxy/issues/1337.

We will want to fix this one way or another before announcing support for .NET 6 in the .NET agent.

**Comment by arthurlockman** [comment]
Can confirm, we’re seeing this in prod on all of our apps that we upgraded to .NET 6. We can reliably reproduce it if need be.

**Comment by arthurlockman** [comment]
Addibg a few ways this manifests so others don’t stumble around in the dark for 4 days like we did trying to find this.

```
System.​NullReferenceException: Object reference not set to an instance of an object.​
   at System.​Net.​Http.​Headers.​HttpHeaders.​ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex)
```

```
System.​IndexOutOfRangeException: Index was outside the bounds of the array.​
   at System.​Net.​Http.​Headers.​HttpHeaders.​ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex)
```

**Comment by amweiss** [comment]
Any ideas on a timeline for release since this blocks upgrading to .NET 6 for customers?

**Comment by angelatan2** [comment]
@amweiss Barring any unexpected event cropping up, the plan is to release sometime this week.

**Comment by angelatan2** [comment]
@amweiss @karelz @MihaZupan please note that the .NET Agent v9.2.0 contains this fix.

**Comment by john--** [comment]
Quick question. We use NR on all our apps including .NET Framework to .NET core. 
I've upgraded our .NET core (.NET 6) app's Agent within it's project to NewRelic.Agent.Api (9.3.0), and I still encounter this issue.
However, I know there is an NR Agent running on the server itself. Does that need to be upgraded as well?

**Comment by JoshuaColeman** [comment]
The Api nuget package is just a thin layer of the agent. The agent deployed on your hosting environment needs to be upgraded. The method to upgrade the agent will depend on how it was installed initially. I'm guessing you deployed via MSI since you are using Framework and .NET Core apps

**Comment by john--** [comment]
> The Api nuget package is just a thin layer of the agent. The agent deployed on your hosting environment needs to be upgraded. The method to upgrade the agent will depend on how it was installed initially. I'm guessing you deployed via MSI since you are using Framework and .NET Core apps

Perfect, thank you for the confirmation!
