### ISSUE TITLE
YUM Upgrade does not maintain newrelic.config or setenv.sh files

### ISSUE THREAD

**Issue by jifeingo** [newrelic/newrelic-dotnet-agent#81]
**Description**
When upgrading agent via YUM, it does not maintain the existing global `newrelic.config`.  This is problematic as customers may use the global `newrelic.config` to set their license key, and or to configure options like Distributed Tracing.
 
**Expected Behavior**
When upgrading using YUM, if there is an existing `newrelic.config` file, it would be maintained, not overwritten.

**Steps to Reproduce**
* Create a CentOS VM and/or container
* Using these [instructions](https://docs.newrelic.com/docs/agents/net-agent/installation/install-net-agent-linux#clamshell_centos_rhel_oracle) as a guide, install an older version of the agent.  You'll need to install an older version so that you can upgrade it.

```sudo rpm -Uvh http://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm
cat << REPO | sudo tee "/etc/yum.repos.d/newrelic-netcore20-agent.repo"
[newrelic-netcore20-agent-repo]
name=New Relic .NET Core packages for Enterprise Linux
baseurl=http://yum.newrelic.com/pub/newrelic/el7/\$basearch
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-NewRelic
REPO
```  
In this example, install the v8.28 version of the agent (current release is v8.30).
```
sudo yum install newrelic-netcore20-agent-8.28.0.0-1
```

* Modify the `newrelic.config` file.  In this example, the licence key was modified, distributed tracing service was enabled, and Cross Application Tracing was disabled.
```<!-- Copyright (c) 2008-2020 New Relic, Inc.  All rights reserved. -->
<!-- For more information see: https://newrelic.com/docs/dotnet/dotnet-agent-configuration -->
<configuration xmlns="urn:newrelic-config" agentEnabled="true">
        <service licenseKey="HERES MY NEW LICENCE KEY" />
        <application>
                <name>My Application</name>
        </application>
        <log level="info"/>
        <transactionTracer enabled="true"
                transactionThreshold="apdex_f"
                stackTraceThreshold="500"
                recordSql="obfuscated"
                explainEnabled="false"
                explainThreshold="500"/>
        <crossApplicationTracer enabled="false"/>
        <distributedTracing enabled="true"/>
        <errorCollector enabled="true">
                <ignoreErrors>
                        <exception>System.IO.FileNotFoundException</exception>
                        <exception>System.Threading.ThreadAbortException</exception>
                </ignoreErrors>
                <ignoreStatusCodes>
                        <code>401</code>
                        <code>404</code>
                </ignoreStatusCodes>
        </errorCollector>
        <browserMonitoring autoInstrument="true" />
        <threadProfiling>
                <ignoreMethod>System.Threading.WaitHandle:InternalWaitOne</ignoreMethod>
                <ignoreMethod>System.Threading.WaitHandle:WaitAny</ignoreMethod>
        </threadProfiling>
</configuration>
```

* Using these [instructions](https://docs.newrelic.com/docs/agents/net-agent/installation/update-net-agent#yum), update the agent to the current version
```
sudo yum update newrelic-netcore20-agent
```

* Re-open the system wide newrelic.config file.  Notice that it has been overwritten.
 
**Your Environment**
CentOS virtual machine.

**Comment by nr-ahemsath** [comment]
This issue will be fixed in the next release.
