### ISSUE TITLE
Fix existing NSB 5 integration tests

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#817]
* Test works locally with locally installed NServiceBus.
* Fails in GHA
* Unable to test in GHA until we land the work to re-enable unbounded tests in GHA (can run tests in different repo as needed.)

**Comment by nr-ahemsath** [comment]
Also see issue #361 for context and history of my (failed) attempts to fix the problem by making this test use console applications only.

**Comment by jaffinito** [comment]
I have checked out the latest runs and the problem no longer occurs.
Closing out the issue.
