### ISSUE TITLE
Support EventSource

### ISSUE THREAD

**Issue by Lucy0** [newrelic/newrelic-dotnet-agent#819]
Is there plans to support Event Source that invokes a .Net lambda function? This is available for Node/Java lambda functions. 
https://newrelic.com/blog/how-to-relic/debugging-event-sources-aws-lambda

**Comment by nr-ahemsath** [comment]
Hello @Lucy0!  Thanks for submitting this issue to us.  At the moment we do not have any concrete plans to support event source, but we will consider adding this feature in an upcoming Lambda-related milestone.
