### ISSUE TITLE
Agent does not report GC metrics for .NET 6 applications

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#872]
**Description**

Several customers have reported that they stopped seeing GC metric data after upgrading their applications to .NET 6. After performing some manual testing and reviewing integration tests, it appears that .NET 6 applications report GC metrics, but they are always 0.

**Expected Behavior**
Garbage collection is faithfully reported for .NET 6 applications.

**Steps to Reproduce**
1. Have a .NET 6 application that can manually trigger garbage collection running with the agent attached.
2. Trigger garbage collection multiple times
3. In the NR1 Metrics Explorer, review `GC/Gen0/Collections` with the `count` function.
4. Note that no garbage collection information is reported

**Comment by tehbio** [comment]
@visdmin we have a PR currently being reviewed to fix this issue [here](https://github.com/newrelic/newrelic-dotnet-agent/pull/874).

**Comment by JcolemanNR** [comment]
@visdmin We have merged the PR containing a fix for this, and plan to release this (and other goodness) within the next few weeks.
