### ISSUE TITLE
Allow for proxy configuration via environment variables

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#878]
@Julien4218 is looking to implement support for proxy server configuration in the Virtuoso guided install of the .NET Agent. For Windows, this is accomplished via modification of the global `newrelic.config` file. For Linux, the only configurability point currently leveraged is environment variables. As such, it would be nice to allow proxy configuration via environment variable.

### Feature Description
Add environment variable(s) to allow for proxy functionality configuration in the .NET Agent.

There will likely need to be multiple different environment variables due to some of the advanced configuration options (proxy domain, etc).

### Alternatives
Virtuoso could just directly modify the global `newrelic.config`, but this breaks the pattern of using primarily environment variables for Linux usage of the .NET Agent. I believe the team has a desire to expand the environment variable API as well, so adding new env vars for proxy configuration synergizes with that goal.

### Priority
Nice to have. This will allow the .NET agent to be more fully configured in Linux guided installs.

**Comment by MikeNislick** [comment]
Does the NR Agent not respond to standard HTTP_PROXY and HTTPS_PROXY environment variables today? If not I would like to upvote this issue. Thanks!

**Comment by JcolemanNR** [comment]
Thanks for pointing this out! I don't believe anyone has tested this. It would be very convenient if this works for the agent.
