### ISSUE TITLE
The .Net Agent alongside usage of HttpClient is causing Unknown Socket Error in the .Net runtime

### ISSUE THREAD

**Issue by sliderhouserules** [newrelic/newrelic-dotnet-agent#897]
**Description**

We have a .Net 5/6 application that is experiencing an inordinate number of `SocketExceptions`. We use a Web API base template and implement background processing that interacts heavily with AWS resources. We are using New Relic functionality extensively throughout.

Removing any and all calls to the New Relic Agent, and all New Relic instrumentation, has alleviated the issue almost completely.

We have an issue filed directly with Microsoft that details the issue [here](https://github.com/dotnet/runtime/issues/64305).

**Expected Behavior**

The NR .Net Agent should play nice with the usage of `HttpClient` and the `IHttpClientFactory` and not contribute to, or cause `SocketExceptions` deep in the .Net runtime.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag/) results**

We have gone through our code intensively to make sure we are properly using the `IHttpClientFactory` which uses pooling under the hood to correctly use `HttpClient`/`HttpRequestMessage`. This is able to be plugged into all of the AWS clients so they are using it properly as well. We have removed all (other) 3rd party libraries that we can determine do not properly use these patterns. The errors persist.

Since we use New Relic extensively, we refrained from removing it. Until I found [this](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Core/DataTransport/HttpCollectorWire.cs#L157). You are apparently using `WebRequest`, which has been deprecated and is recommended to not be used, as it is known to cause socket exhaustion and `SocketExceptions`.

Once we completely removed all calls to the agent, and any references to NR namespaces and projects, _the problems have ceased_. Several hours of load testing has confirmed this.

**Steps to Reproduce**

I don't have a sample application to share with you, I can only suggest that:
- a basic Web API project (`dotnet create webapi`) be created
- some background processing implemented in `IHostedService`s that:
interacts with external web resources (using GETs, PUTs, and POSTs to match our use case)
properly uses either singleton `HttpClient` or the `IHttpClientFactory`
- test both with and without usage of the NR agent integrated in there somewhere (preferably liberally)

The above _should_ reproduce the error. Test targeting both .Net 5 and 6 and you _should_ see the errors increase in frequency with .Net 6.

**Your Environment**

- .Net 5/6
- New Relic .Net agent v9.x (various versions tried)
- Linux in containers (Ubuntu 20.04)
- Kubernetes

**Additional context**

Again, reference [this](https://github.com/dotnet/runtime/issues/64305) issue on the dotnet/runtime board for more detail. I can also answer questions directly here.

Please let me know what else I can do.

**Comment by vuqtran88** [comment]
@sliderhouserules 
Thanks for bringing this to our attention. The next step for us is trying to repro the issue based on the information you shared.

Regarding to the usage of `WebRequest`, it's still unclear to me whether or it is the real issue because `HttpClient` is used under the hood in .Net Core, so if we switched to use `HttpClient`, i think this issue would still occur.

**Comment by sliderhouserules** [comment]
Yeah, I've been working with MS, but that root cause that they discovered for the other person that had a similar issue/symptoms isn't my issue, I don't think. When I remove all New Relic calls from my application, the errors go away. When I put the calls back in, the SocketException occurs.

I will be able to get back to testing this and attempting to solve it soon, and would love your assistance. But for now, I am not able to do anything with this due to other higher priority items in my work queue.

If you get to it in the meantime, I can try to provide more information as you need it.

**Comment by angelatan2** [comment]
From @vuqtran88:
One of the approach to address this issue without a reproduction is to replace WebRequest with HttpClient and get feedback from customers:

The main drivers for this change are these issues [issue #1]|(https://github.com/newrelic/newrelic-dotnet-agent/issues/897, [issue #2]|(https://github.com/newrelic/newrelic-dotnet-agent/issues/1202) that were reported. There weren’t definitive conclusions about whether or not using WebRequest directly caused these reported issues, but my recommendation is we should replace WebRequest with HttpClient. The reasons are:
Microsoft has encouraged developers to move away from WebRequest and use HttpClient for new developments. In fact, MSFT [marked WebRequest as deprecated](https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated) in .NET 6.0 . Even though MSFT still keeps WebRequest for .NET FW developments, but I believe it is mainly for backward compatibility purposes.

For development/testing purposes only: https://github.com/newrelic/newrelic-dotnet-agent/tree/use-httpclient-proto
