### ISSUE TITLE
NewRelic.AppName not being read from the correct appsettings.{environment}.json file

### ISSUE THREAD

**Issue by bernienowel** [newrelic/newrelic-dotnet-agent#9]
## Description

Setting the Microsoft recommended `ASPNETCORE_ENVIRONMENT` system environment variable doesn't work for the NewRelic .Net Core Agent v 8.29.0.0 in a .Net Core 3.x project.

It appears that the New Relic Agent looks at a different `EnvironmentName` environment variable to determine which overriding `appsettings.{environment}.json` file to use for the `NewRelic.AppName` configuration setting.

### Reading the `Environment` System Environment Variables

https://github.com/newrelic/newrelic-dotnet-agent/blob/0dcbe0005a5af58277cc428754a20d9882ada263/src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs#L29

### Overridding the `appsettings.json` Settings per Environment

https://github.com/newrelic/newrelic-dotnet-agent/blob/b4918c4454286732fd97376fec6e5dc907e54d8d/src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs#L35

## Steps to Reproduce

In a .Net Core 3.x application using `appsettings.*.json` files to specify the `NewRelic.AppName`:

In `appsettings.json` specify:

```json
{
  "NewRelic.AppName": "Local"
}
```

In `appsettings.Staging.json` specify:

```json
{
  "NewRelic.AppName": "Staging"
}
```

Deploy to an environment with the Environment variable `ASPNETCORE_ENVIRONMENT` = `Staging` set.

See that the value for `NewRelic.AppName` will be `Local` instead of the correct `Staging` value.

## Expected Behaviour

I would expect that the Microsoft recommended `ASPNETCORE_ENVIRONMENT` would define the environment instead of the current `EnvironmentName` being used.

```csharp
            // Something like this should provide backwards compatibility for people using EnvironmentName
            var environment = env.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
            if (string.IsNullOrEmpty(environment))
                environment = env.GetEnvironmentVariable("EnvironmentName");
```

## Your Environment

Running a .Net Core 3.x Web Application on a Windows Server using IIS as an InProc site.

**Comment by elucus** [comment]
Hi @bernienowel thanks for submitting an issue. We'll review this soon.

**Comment by elucus** [comment]
Hi @bernienowel, sorry for the delay on this. We have reviewed and at this point we are unable to commit to a timeline for this fix.  Would you be willing to submit a PR with the intended fix?

**Comment by StummeJ** [comment]
Can't you just use microsoft's configuration package?  The, poorly written, docs make it sound like it should be but in reality it looks like you're reading the files directly.  It also looks like you're using a convention that is non-standard to dotnet as well as with the appsettings.json you should put your configs under a `newrelic` object.
