### ISSUE TITLE
Dotnet core agent - old installation binary is removed from download site

### ISSUE THREAD

**Issue by rasodu** [newrelic/newrelic-dotnet-agent#91]
**Description**
New relic download [site](https://download.newrelic.com/dot_net_agent/latest_release/) only has the latest version of deb file for dotnet agent installation. We have the docker build that download and install the the agent using the file. Old version installation files are removed upon release of new version of the installation file and that breaks our docker build. 

**Expected Behavior**
Keep the old version of dotnet agent installation file on download site.

**Steps to Reproduce**
As of now I see [newrelic-netcore20-agent_8.30.0.0_amd64.deb](https://download.newrelic.com/dot_net_agent/latest_release/newrelic-netcore20-agent_8.30.0.0_amd64.deb) listed  on the download site. It will disappear once a new version of agent is released.

**Comment by jifeingo** [comment]
Hello Abhijit,
Thanks for reaching out.  I believe you can find prior versions of our installs at  [https://download.newrelic.com/dot_net_agent/previous_releases](https://download.newrelic.com/dot_net_agent/previous_releases).  Would this cover your need?

Thanks,
Jason

**Comment by rasodu** [comment]
Thanks @jifeingo 
Yes, it would solve the problem if we can get previously released installer for the agent. We we change our docker image build step to pull the file from new location.
Ideally, we would like to utilize the latest version of the release. But we may run a version or two behind at a time. So, it would help if the latest version of agent are also added at the same time they are released on the main download section. 

At this point I don't see "deb" file. Is it something that will be added at some point?

**Comment by nr-ahemsath** [comment]
Hello Abhijit,

Which previous version of the .deb installer package were you looking for?  For example, the 8.29.0.0 (https://download.newrelic.com/dot_net_agent/previous_releases/8.29.0/) version can be found here: https://download.newrelic.com/dot_net_agent/previous_releases/8.29.0/newrelic-netcore20-agent_8.29.0.0_amd64.deb

Thanks,
Alex

**Comment by rasodu** [comment]
I had [this](https://github.com/rasodu/AspnetCoreOnHerokuSample/blob/74432058b7b4dfdd05626b3a3dd562c5c8df4d9d/scripts/install-new-relic.sh#L7) install script. The script broke my automatic deployment because it is no longer finding the file. The version script was downloading is newrelic-netcore20-agent_8.21.34.0_amd64.deb

I am looking for a streamlined way to fetch the installer file of a specific version. So, my CD pipeline doesn't break in the future.

**Comment by rasodu** [comment]
I see file: https://download.newrelic.com/dot_net_agent/previous_releases/8.30.0/newrelic-netcore20-agent_8.30.0.0_amd64.deb

I can use the URL to ensure that builds are reproducible. Thanks all

**Comment by nr-ahemsath** [comment]
What you're looking for is pretty straightforward, although there is a complication due to the fact that we recently tweaked the agent's versioning to adopt Semantic Versioning (which only has three digits of versioning, e.g. 8.29.0), but the .deb installer package continues to use four digits (and the last digit will always be 0).

For versions prior to 8.29.0, e.g. 8.21.34.0:
```
agent_version='8.21.34.0'
wget -O newrelic-netcore20-agent.deb "https://download.newrelic.com/dot_net_agent/previous_releases/${agent_version}/newrelic-netcore20-agent_${agent_version}_amd64.deb"
```

For versions 8.29.0 and greater:
```
agent_version='8.29.0'
wget -O newrelic-netcore20-agent.deb "https://download.newrelic.com/dot_net_agent/previous_releases/${agent_version}/newrelic-netcore20-agent_${agent_version}.0_amd64.deb"
```
(Note the extra .0 on the end of ${agent_version} in the downloaded filename.)

I see that you've already closed this, but I wanted to make sure you knew about this complication.  Thanks for reaching out to us!

**Comment by rasodu** [comment]
Understood. This will help pull out the agent version into a variable.
Most likely I will just jump to latest version.
Thanks for a quick turnaround.
