### ISSUE TITLE
Local Log Decoration log4net Performance testing

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#915]
### Feature Description

- My initial tests indicated:
  - Adding the instrumentation did little to affect performance - adding to a dictionary is pretty fast
  - Pulling the new value out in the log4net config and writing to disk added  between 20 to 45 MS to the 100 MS transaction.  This appears to be quite bad, so we need to better understand this increase.
  - How does this new work compare to the existing log enrichers?  Is it worse, better, the same, or something different?

Acceptance Criteria

- We understand and can articulate the performance impacts of performing the decoration.

**Comment by nr-ahemsath** [comment]
Results of overhead testing for log4net log forwarding and local log decoration...

Summary: for an application with typical logging characteristics of 2000 log messages/minute and ~500Kb/message, there is no significant increase in agent overhead (CPU and memory usage) when comparing the current released agent (9.5.1) with the `logsinst-feature-branch` agent.

More details:
1. I'm performing testing on Windows 10 with a .NET 6.0 console application, using log4net 2.0.14.  The application runs for five minutes and logs messages at a configurable rate (messages/minute).  The method which logs messages is decorated with the agent API's `[Transaction]` attribute, so the logged messages will have logs-in-context data (trace/span ID) when decorated or forwarded by the agent.  log4net is configured to use a PatternLayout with the following pattern: `<conversionPattern value="%date [%thread] %-5level %logger - %message %property{NR_LINKING_METADATA} %newline" />`
2. Performance data was gathered using the `dotnet-counters` tool (https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters).  This produces samples of performance counters at a given interval; the numbers reported below are the average of each counter for the (five minute) duration of each test case.

| Agent Version   | Forwarding Enabled | Local Decoration Enabled | CPU Usage (%) | Working Set (MB) | GC Heap Size (MB) |
| ---------------   | ---------------------- | ---------------------------- | ----------------- | ------------------- | --------------- | 
| 9.5.1                 | N/A                           | N/A                                   | 0.11                   | 85.2                      | 14.7                 |
| Feature Branch | Yes                            | No                                     | 0.12                   | 87.2                      | 15.6                 |
| Feature Branch | No                            | Yes                                     | 0.14                   | 84.1                      | 14.5                 |
| Feature Branch | Yes                            | Yes                                    | 0.13                   | 86.3                      | 14.8                 |

Regarding what @jaffinito said initially about "pulling the new value out in the log4net config and writing to disk added between 20 to 45 MS to the 100 MS transaction": more targeted benchmark testing found that any access to the `Properties` dictionary in a log4net layout causes a significant performance hit, regardless of whether our agent is involved or not.  This is documented in the log4net project itself: https://issues.apache.org/jira/browse/LOG4NET-429

I also tested using the 9.5.1 agent with the [existing Log Enrichers layout for log4net](https://github.com/newrelic/newrelic-logenricher-dotnet/tree/main/src/NewRelic.LogEnrichers.Log4Net) and the numbers were completely similar to the above.
