### ISSUE TITLE
Update Async Timing Calculations

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#93]
**Description**
The agent does not deduct the duration of asynchronous methods from parent span/segment/methods' exclusive duration, which leads to misleading durations reported when those asynchronous child methods are called in a synchronous manner.

One such scenario is ASP.NET Web API. We instrument `ExecuteRequestHandler` that calls `System.Web.Http.Controllers.ApiControllerActionInvoker.InvokeActionAsync` which we also instrument. `InvokeActionAsync` is an async method, so the agent does not deduct its time from the time of `ExecuteRequestHandler`. Since we know `ExecuteRequestHandler` actually does block on `InvokeActionAsync` it probably makes sense to special case these types of scenarios.

**Expected Behavior**
The reported exclusive duration of common ASP.NET middleware pipeline steps like `ExecuteRequestHandler` should not include the time spent in blocking async child methods like `InvokeActionAsync`.

Internal NR only:
[ref1](https://newrelic.atlassian.net/browse/DOTNET-4633)
[ref2](https://newrelic.zendesk.com/agent/tickets/407105)
[ref3](https://docs.google.com/drawings/d/1eSncVm2WvbHHVldSFL3nGeC3IqVuAjpCXMoWzPW0OaI/edit?ts=5d533145)

**Comment by angelatan2** [comment]
This update was resolved in 8.36.
