### ISSUE TITLE
Update configuration documentation to include host (endpoint) configuration details

### ISSUE THREAD

**Issue by jaffinito** [newrelic/newrelic-dotnet-agent#947]
### Feature Description

- Update configuration documentation to include using the "host" attribute on the "service" element.
- Include details on the corresponding environment variable
- Include detail that this is on for FEDRAMP accounts and how to set the option for FEDRAMP. 
  - Please be very clear that this setting is not something customers need to mess with outside of that very specific scenario

### Priority
Really Want

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/947?planning-poker) with Zenhub @jaffinito @JcolemanNR @tippmar-nr

**Comment by angelatan2** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/947?planning-poker) with Zenhub @nr-ahemsath

**Comment by nr-ahemsath** [comment]
This appears to have been done: https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#service-host
