### ISSUE TITLE
Some supportability metrics should only be sent once per agent lifecycle

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#952]
See this TODO in the AgentHealthReporter: https://github.com/newrelic/newrelic-dotnet-agent/blob/20f024b2a9e48514f1215dabf2f69b3f691b1722/src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs#L609

The following supportability metrics are currently sent once per harvest cycle, i.e. every 60 seconds:

- ReportAgentVersion(AgentInstallConfiguration.AgentVersion);
  - `Supportability/AgentVersion/$version`
- ReportIfHostIsLinuxOs();
  - `Supportability/OS/Linux`
- ReportDotnetVersion();
  - `Supportability/Dotnet/{NetFramework|NetCore}/$version` 
- ReportAgentInfo();
  - `Supportability/Dotnet/Install/$installmethod`

Before merging the logging feature branch to main we should resolve this TODO one way or other:
1. If we get a decision one way or another, update the code appropriately (either make them one time metrics, or comment why we can't and remove the TODO)
2. If we can't get a decision in time, remove the TODO comment anyway and move this story back to the backlog and out of the milestone.

**Comment by JcolemanNR** [comment]
After discussing as a team, moving these existing metrics to once per agent lifecycle would break existing usage in Angler.
