### ISSUE TITLE
Useful supportability metrics

### ISSUE THREAD

**Issue by tytyhibye** [newrelic/newrelic-dotnet-agent#966]
Hey gang, I support the Node Agent and we have a useful [supportability metric](https://github.com/newrelic/node-newrelic/blob/c4a7066f00934c4e872f59dea2fd71ce41777f57/lib/stats/index.js#L71) that increments the call count for any methods used from our [Agent API](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api/). This gives us better insight into their custom instrumentation specifically letting us know if their environment's logic is invoking the method correctly. An example would be the customer is using [noticeError()](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api/#noticeError) from our Node Agent API to monitor an error that isn't reporting in their UI. They say they're calling this method but we don't see a correlating [supportability metric](https://github.com/newrelic/node-newrelic/blob/main/api.js#L422). This let's us know that their applications logic isn't correctly targeting this call without us needing to see their source code or get on a screen share.
I think this type of metric could be useful for all APM agents and wanted to get it on your radar, thank you!

**Comment by nr-ahemsath** [comment]
We actually already do this in the .NET agent: https://github.com/newrelic/newrelic-dotnet-agent/blob/60d375ae337d0211e09055e317290a611c9f8d54/src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs#L64
