### ISSUE TITLE
Integration tests for Serilog local decoration

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-dotnet-agent#976]
Implement integration tests for Serilog local log decoration.

TBD: pattern to follow from log4net (not done yet at this time this issue is being created)

TBD: what Serilog local logging scenarios are supported.  Serilog has "sinks" (i.e. where log data is going: a file, a database...see https://github.com/serilog/serilog/wiki/Provided-Sinks) and "formatters" (how data is rendered: https://github.com/serilog/serilog/wiki/Formatting-Output)  At a minimum, test the File sink with plain text and JSON formatters.

**Comment by angelatan2** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dotnet-Agent-61560f15ddd6a90010ada14e/issues/newrelic/newrelic-dotnet-agent/976?planning-poker) with ZenHub @nr-ahemsath @jaffinito
