### ISSUE TITLE
Add environment variables for allowAllHeaders configuration options

### ISSUE THREAD

**Issue by StacySimmons** [newrelic/newrelic-dotnet-agent#979]
### Feature Description
Allow the configuration of request header collection through environment variables in cases where the application is deployed in a managed application service and the configuration file is obscured/not editable.

**Comment by JcolemanNR** [comment]
Hello @StacySimmons,

Thanks for the feature request! We have been discussing exposing more configuration via environment variables recently to support use cases like yours. 

Just to make sure we understand the ask, are you interested in using the following configuration options via environment variables? 
https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#capture_http_request_headers
