### ISSUE TITLE
Create internal test/demo app for log forwarding

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/newrelic-dotnet-agent#986]
### Feature Description
There is a desire to create an common internal test application that can be used by product, agent, and UI teams to develop/explore the log forwarding feature.

This should be a simple app that has constant low load and generates logs.

Some requests should have errors with traces to allow people to explore the usefulness/functionality of the log forwarding feature.

This app should be deployed in azure and report to staging. 

Source code should also be available via GHE for developers/TSEs/PMs that want to experiment on their own.

**Comment by jaffinito** [comment]
This is not something we are going to be doing. Closing.
